import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  title: 'Options',
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    accessories: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['variant04', 'variant03', 'variant02', 'variant01'],
      },
      default: ['variant04', 'variant03', 'variant02', 'variant01'],
      examples: [['variant04'], ['variant03'], ['variant02'], ['variant01']],
    },
    accessoriesColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['gold01', 'gold02', 'gold03', 'silver01', 'silver02'],
      examples: [
        ['gold01'],
        ['gold02'],
        ['gold03'],
        ['silver01'],
        ['silver02'],
      ],
    },
    accessoriesProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    beard: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    beardProbability: { type: 'integer', minimum: 0, maximum: 100, default: 5 },
    clothing: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant23'],
        ['variant22'],
        ['variant21'],
        ['variant20'],
        ['variant19'],
        ['variant18'],
        ['variant17'],
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    clothingColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'blue01',
        'blue02',
        'blue03',
        'green01',
        'green02',
        'green03',
        'red01',
        'red02',
        'red03',
        'yellow01',
        'yellow02',
        'yellow03',
      ],
      examples: [
        ['blue01'],
        ['blue02'],
        ['blue03'],
        ['green01'],
        ['green02'],
        ['green03'],
        ['red01'],
        ['red02'],
        ['red03'],
        ['yellow01'],
        ['yellow02'],
        ['yellow03'],
      ],
    },
    eyes: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    eyesColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
        'variant06',
      ],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
        ['variant06'],
      ],
    },
    glasses: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'light07',
          'light06',
          'light05',
          'light04',
          'light03',
          'light02',
          'light01',
          'dark07',
          'dark06',
          'dark05',
          'dark04',
          'dark03',
          'dark02',
          'dark01',
        ],
      },
      default: [
        'light07',
        'light06',
        'light05',
        'light04',
        'light03',
        'light02',
        'light01',
        'dark07',
        'dark06',
        'dark05',
        'dark04',
        'dark03',
        'dark02',
        'dark01',
      ],
      examples: [
        ['light07'],
        ['light06'],
        ['light05'],
        ['light04'],
        ['light03'],
        ['light02'],
        ['light01'],
        ['dark07'],
        ['dark06'],
        ['dark05'],
        ['dark04'],
        ['dark03'],
        ['dark02'],
        ['dark01'],
      ],
    },
    glassesColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['black01', 'black02', 'black03', 'blue01', 'green01', 'red01'],
      examples: [
        ['black01'],
        ['black02'],
        ['black03'],
        ['blue01'],
        ['green01'],
        ['red01'],
      ],
    },
    glassesProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 20,
    },
    hair: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'short24',
          'short23',
          'short22',
          'short21',
          'short20',
          'short19',
          'short18',
          'short17',
          'short16',
          'short15',
          'short14',
          'short13',
          'short12',
          'short11',
          'short10',
          'short09',
          'short08',
          'short07',
          'short06',
          'short05',
          'short04',
          'short03',
          'short02',
          'short01',
          'long21',
          'long20',
          'long19',
          'long18',
          'long17',
          'long16',
          'long15',
          'long14',
          'long13',
          'long12',
          'long11',
          'long10',
          'long09',
          'long08',
          'long07',
          'long06',
          'long05',
          'long04',
          'long03',
          'long02',
          'long01',
        ],
      },
      default: [
        'short24',
        'short23',
        'short22',
        'short21',
        'short20',
        'short19',
        'short18',
        'short17',
        'short16',
        'short15',
        'short14',
        'short13',
        'short12',
        'short11',
        'short10',
        'short09',
        'short08',
        'short07',
        'short06',
        'short05',
        'short04',
        'short03',
        'short02',
        'short01',
        'long21',
        'long20',
        'long19',
        'long18',
        'long17',
        'long16',
        'long15',
        'long14',
        'long13',
        'long12',
        'long11',
        'long10',
        'long09',
        'long08',
        'long07',
        'long06',
        'long05',
        'long04',
        'long03',
        'long02',
        'long01',
      ],
      examples: [
        ['short24'],
        ['short23'],
        ['short22'],
        ['short21'],
        ['short20'],
        ['short19'],
        ['short18'],
        ['short17'],
        ['short16'],
        ['short15'],
        ['short14'],
        ['short13'],
        ['short12'],
        ['short11'],
        ['short10'],
        ['short09'],
        ['short08'],
        ['short07'],
        ['short06'],
        ['short05'],
        ['short04'],
        ['short03'],
        ['short02'],
        ['short01'],
        ['long21'],
        ['long20'],
        ['long19'],
        ['long18'],
        ['long17'],
        ['long16'],
        ['long15'],
        ['long14'],
        ['long13'],
        ['long12'],
        ['long11'],
        ['long10'],
        ['long09'],
        ['long08'],
        ['long07'],
        ['long06'],
        ['long05'],
        ['long04'],
        ['long03'],
        ['long02'],
        ['long01'],
      ],
    },
    hairColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
        'variant06',
        'variant07',
        'variant08',
        'variant09',
        'variant10',
        'variant11',
      ],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
        ['variant06'],
        ['variant07'],
        ['variant08'],
        ['variant09'],
        ['variant10'],
        ['variant11'],
      ],
    },
    mouth: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'sad10',
          'sad09',
          'sad08',
          'sad07',
          'sad06',
          'sad05',
          'sad04',
          'sad03',
          'sad02',
          'sad01',
          'happy13',
          'happy12',
          'happy11',
          'happy10',
          'happy09',
          'happy08',
          'happy07',
          'happy06',
          'happy05',
          'happy04',
          'happy03',
          'happy02',
          'happy01',
        ],
      },
      default: [
        'sad10',
        'sad09',
        'sad08',
        'sad07',
        'sad06',
        'sad05',
        'sad04',
        'sad03',
        'sad02',
        'sad01',
        'happy13',
        'happy12',
        'happy11',
        'happy10',
        'happy09',
        'happy08',
        'happy07',
        'happy06',
        'happy05',
        'happy04',
        'happy03',
        'happy02',
        'happy01',
      ],
      examples: [
        ['sad10'],
        ['sad09'],
        ['sad08'],
        ['sad07'],
        ['sad06'],
        ['sad05'],
        ['sad04'],
        ['sad03'],
        ['sad02'],
        ['sad01'],
        ['happy13'],
        ['happy12'],
        ['happy11'],
        ['happy10'],
        ['happy09'],
        ['happy08'],
        ['happy07'],
        ['happy06'],
        ['happy05'],
        ['happy04'],
        ['happy03'],
        ['happy02'],
        ['happy01'],
      ],
    },
    mouthColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['variant01', 'variant02', 'variant03', 'variant04'],
      examples: [['variant01'], ['variant02'], ['variant03'], ['variant04']],
    },
    skinColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
        'variant06',
        'variant07',
        'variant08',
      ],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
        ['variant06'],
        ['variant07'],
        ['variant08'],
      ],
    },
  },
  additionalProperties: false,
};
