import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  title: 'Options',
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    row1: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      },
      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      examples: [
        ['xooox'],
        ['xxoxx'],
        ['xoxox'],
        ['oxxxo'],
        ['xxxxx'],
        ['oxoxo'],
        ['ooxoo'],
      ],
    },
    row2: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      },
      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      examples: [
        ['xooox'],
        ['xxoxx'],
        ['xoxox'],
        ['oxxxo'],
        ['xxxxx'],
        ['oxoxo'],
        ['ooxoo'],
      ],
    },
    row3: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      },
      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      examples: [
        ['xooox'],
        ['xxoxx'],
        ['xoxox'],
        ['oxxxo'],
        ['xxxxx'],
        ['oxoxo'],
        ['ooxoo'],
      ],
    },
    row4: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      },
      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      examples: [
        ['xooox'],
        ['xxoxx'],
        ['xoxox'],
        ['oxxxo'],
        ['xxxxx'],
        ['oxoxo'],
        ['ooxoo'],
      ],
    },
    row5: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      },
      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
      examples: [
        ['xooox'],
        ['xxoxx'],
        ['xoxox'],
        ['oxxxo'],
        ['xxxxx'],
        ['oxoxo'],
        ['ooxoo'],
      ],
    },
    rowColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'red',
        'amber',
        'blue',
        'blueGray',
        'brown',
        'cyan',
        'deepOrange',
        'deepPurple',
        'green',
        'grey',
        'indigo',
        'lightBlue',
        'lightGreen',
        'lime',
        'orange',
        'pink',
        'purple',
        'teal',
        'yellow',
      ],
      examples: [
        ['red'],
        ['amber'],
        ['blue'],
        ['blueGray'],
        ['brown'],
        ['cyan'],
        ['deepOrange'],
        ['deepPurple'],
        ['green'],
        ['grey'],
        ['indigo'],
        ['lightBlue'],
        ['lightGreen'],
        ['lime'],
        ['orange'],
        ['pink'],
        ['purple'],
        ['teal'],
        ['yellow'],
      ],
    },
  },
  additionalProperties: false,
};
