import type { StyleSchema } from '@dicebear/core';
	export const schema: StyleSchema = {
	  title: 'Options',
	  $schema: 'http://json-schema.org/draft-07/schema#',
	  properties: {
	    row1: {
	      type: 'array',
	      items: {
	        type: 'string',
	        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      },
	      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      examples: [
	        ['xooox'],
	        ['xxoxx'],
	        ['xoxox'],
	        ['oxxxo'],
	        ['xxxxx'],
	        ['oxoxo'],
	        ['ooxoo'],
	      ],
	    },
	    row2: {
	      type: 'array',
	      items: {
	        type: 'string',
	        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      },
	      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      examples: [
	        ['xooox'],
	        ['xxoxx'],
	        ['xoxox'],
	        ['oxxxo'],
	        ['xxxxx'],
	        ['oxoxo'],
	        ['ooxoo'],
	      ],
	    },
	    row3: {
	      type: 'array',
	      items: {
	        type: 'string',
	        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      },
	      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      examples: [
	        ['xooox'],
	        ['xxoxx'],
	        ['xoxox'],
	        ['oxxxo'],
	        ['xxxxx'],
	        ['oxoxo'],
	        ['ooxoo'],
	      ],
	    },
	    row4: {
	      type: 'array',
	      items: {
	        type: 'string',
	        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      },
	      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      examples: [
	        ['xooox'],
	        ['xxoxx'],
	        ['xoxox'],
	        ['oxxxo'],
	        ['xxxxx'],
	        ['oxoxo'],
	        ['ooxoo'],
	      ],
	    },
	    row5: {
	      type: 'array',
	      items: {
	        type: 'string',
	        enum: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      },
	      default: ['xooox', 'xxoxx', 'xoxox', 'oxxxo', 'xxxxx', 'oxoxo', 'ooxoo'],
	      examples: [
	        ['xooox'],
	        ['xxoxx'],
	        ['xoxox'],
	        ['oxxxo'],
	        ['xxxxx'],
	        ['oxoxo'],
	        ['ooxoo'],
	      ],
	    },
	    rowColor: {
	      type: 'array',
	      items: {
	        type: 'string',
	        pattern:
	          '^#([a-fA-F0-9]{3}|[a-fA-F0-9]{4}|[a-fA-F0-9]{6}|[a-fA-F0-9]{8})$',
	      },
	      default: [
	        'e53935',
	        'ffb300',
	        '1e88e5',
	        '546e7a',
	        '6d4c41',
	        '00acc1',
	        'f4511e',
	        '5e35b1',
	        '43a047',
	        '757575',
	        '3949ab',
	        '039be5',
	        '7cb342',
	        'c0ca33',
	        'fb8c00',
	        'd81b60',
	        '8e24aa',
	        '00897b',
	        'fdd835',
	      ],
	    },
	  },
	  additionalProperties: false,
	};
