import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  title: 'Options',
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    eyes: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    mouth: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant18'],
        ['variant17'],
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    nose: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
  },
  additionalProperties: false,
};
