//! Walks a style's element tree and turns it into the final SVG markup.
//!
//! The renderer is single-use: it accumulates `<defs>` entries and per-render
//! caches across method calls, so a fresh instance is required per avatar. Any
//! circular color reference encountered during resolution surfaces as an
//! [`Error`] from [`Renderer::render`].

use std::collections::{BTreeSet, HashMap, HashSet};
use std::hash::{BuildHasher, Hasher, RandomState};
use std::sync::LazyLock;

use indexmap::IndexMap;
use regex::Regex;

use crate::error::Error;
use crate::prng::fnv1a;
use crate::resolver::Resolver;
use crate::style::{
    Animation, AnimationKeyframe, Canvas, Component, DynValue, Easing, Element, Style,
};
use crate::utils::{initials, license, number, xml};

/// The canonical track order, outermost wrapper to innermost. It mirrors the
/// usual translate → rotate → scale transform composition. Every port must
/// wrap in this exact order for the outputs to stay byte-identical.
const TRACK_ORDER: [&str; 6] = [
    "translateX",
    "translateY",
    "rotate",
    "scaleX",
    "scaleY",
    "opacity",
];

pub struct Renderer<'a> {
    style: &'a Style,
    resolver: &'a Resolver<'a>,
    defs: IndexMap<String, String>,
    cached_seed_hash: Option<String>,
    cached_initials: Option<String>,
    cached_animation_hash: Option<String>,
    keyframes_css: Vec<String>,
    animation_css: Vec<String>,
    keyframes_by_content: HashMap<String, String>,
    keyframes_counter: usize,
    animation_class_counter: usize,
}

impl<'a> Renderer<'a> {
    pub fn new(style: &'a Style, resolver: &'a Resolver<'a>) -> Self {
        Self {
            style,
            resolver,
            defs: IndexMap::new(),
            cached_seed_hash: None,
            cached_initials: None,
            cached_animation_hash: None,
            keyframes_css: Vec::new(),
            animation_css: Vec::new(),
            keyframes_by_content: HashMap::new(),
            keyframes_counter: 0,
            animation_class_counter: 0,
        }
    }

    /// Builds the complete SVG document for the avatar.
    pub fn render(&mut self) -> Result<String, Error> {
        let style = self.style;
        let resolver = self.resolver;
        let canvas = style.canvas();

        let background = self.render_background(canvas)?;
        let mut body = self.render_elements(canvas.elements())?;

        // Order matters: scale and flip around center, then rotate, translate,
        // and finally clip with border radius (outermost wrapper).
        body = self.apply_scale(body, canvas);
        body = self.apply_flip(body, canvas);
        body = self.apply_rotate(body, canvas);
        body = self.apply_translate(body, canvas);
        body = self.apply_border_radius(format!("{background}{body}"), canvas);

        self.register_animation_style();

        let metadata = license::xml(style.meta());
        let defs = if self.defs.is_empty() {
            String::new()
        } else {
            format!(
                "<defs>{}</defs>",
                self.defs.values().cloned().collect::<String>()
            )
        };

        // Resolve size before title and the root attributes so the resolver memo
        // records the keys in the same order as the other ports — the
        // JSON envelope emits the resolved options in first-recorded order.
        let size = resolver.size();

        let escaped_title = resolver.title().map(|t| xml::escape(&t));

        let mut attrs = vec![
            "xmlns=\"http://www.w3.org/2000/svg\"".to_string(),
            format!(
                "viewBox=\"0 0 {} {}\"",
                number::format(canvas.width()),
                number::format(canvas.height())
            ),
        ];

        let root_attributes = self.render_attributes(style.root_attributes())?;
        if !root_attributes.is_empty() {
            attrs.push(root_attributes.trim_start().to_string());
        }

        match &escaped_title {
            Some(title) => {
                attrs.push("role=\"img\"".to_string());
                attrs.push(format!("aria-label=\"{title}\""));
            }
            None => attrs.push("aria-hidden=\"true\"".to_string()),
        }

        if let Some(size) = size {
            let size = number::format(size);
            attrs.push(format!("width=\"{size}\""));
            attrs.push(format!("height=\"{size}\""));
        }

        let title_element = match &escaped_title {
            Some(title) => format!("<title>{title}</title>"),
            None => String::new(),
        };

        let svg = format!(
            "<svg {}><!-- Generated by DiceBear (https://www.dicebear.com) -->{metadata}{defs}{title_element}{body}</svg>",
            attrs.join(" ")
        );

        Ok(if resolver.id_randomization() {
            randomize_ids(&svg)
        } else {
            svg
        })
    }

    fn apply_flip(&self, body: String, canvas: &Canvas) -> String {
        let flip = self.resolver.flip();

        if flip == "none" {
            return body;
        }

        let w = number::format(canvas.width());
        let h = number::format(canvas.height());

        let transform = match flip.as_str() {
            "horizontal" => format!("translate({w}, 0) scale(-1, 1)"),
            "vertical" => format!("translate(0, {h}) scale(1, -1)"),
            "both" => format!("translate({w}, {h}) scale(-1, -1)"),
            _ => return body,
        };

        format!("<g transform=\"{transform}\">{body}</g>")
    }

    fn apply_scale(&self, body: String, canvas: &Canvas) -> String {
        let scale = self.resolver.scale();

        if scale == 1.0 {
            return body;
        }

        let cx = canvas.width() / 2.0;
        let cy = canvas.height() / 2.0;

        format!(
            "<g transform=\"translate({}, {}) scale({}) translate({}, {})\">{body}</g>",
            number::format(cx),
            number::format(cy),
            number::format(scale),
            number::format(-cx),
            number::format(-cy)
        )
    }

    fn apply_border_radius(&mut self, body: String, canvas: &Canvas) -> String {
        let radius = self.resolver.border_radius();
        let id = format!("clip-{}", self.hash_seed());
        let rx = number::format(radius / 100.0 * canvas.width());
        let ry = number::format(radius / 100.0 * canvas.height());

        self.defs.insert(
            id.clone(),
            format!(
                "<clipPath id=\"{id}\"><rect width=\"{}\" height=\"{}\" rx=\"{rx}\" ry=\"{ry}\"/></clipPath>",
                number::format(canvas.width()),
                number::format(canvas.height())
            ),
        );

        format!("<g clip-path=\"url(#{id})\">{body}</g>")
    }

    fn apply_rotate(&self, body: String, canvas: &Canvas) -> String {
        let rotate = self.resolver.rotate();

        if rotate == 0.0 {
            return body;
        }

        let cx = canvas.width() / 2.0;
        let cy = canvas.height() / 2.0;

        format!(
            "<g transform=\"rotate({}, {}, {})\">{body}</g>",
            number::format(rotate),
            number::format(cx),
            number::format(cy)
        )
    }

    fn apply_translate(&self, body: String, canvas: &Canvas) -> String {
        let tx = self.resolver.translate_x();
        let ty = self.resolver.translate_y();

        if tx == 0.0 && ty == 0.0 {
            return body;
        }

        let x = number::format(tx / 100.0 * canvas.width());
        let y = number::format(ty / 100.0 * canvas.height());

        format!("<g transform=\"translate({x}, {y})\">{body}</g>")
    }

    fn render_background(&mut self, canvas: &Canvas) -> Result<String, Error> {
        if self.resolver.color("background")?.is_empty() {
            return Ok(String::new());
        }

        let fill = xml::escape(&self.resolve_color_reference("background")?);

        Ok(format!(
            "<rect width=\"{}\" height=\"{}\" fill=\"{fill}\"/>",
            number::format(canvas.width()),
            number::format(canvas.height())
        ))
    }

    fn render_elements(&mut self, elements: &[Element]) -> Result<String, Error> {
        let mut out = String::new();

        for element in elements {
            out.push_str(&self.render_element(element)?);
        }

        Ok(out)
    }

    fn render_element(&mut self, element: &Element) -> Result<String, Error> {
        match element.kind() {
            "element" => self.render_svg_element(element),
            "text" => Ok(self.render_text_element(element)),
            "component" => self.render_component_element(element),
            _ => Ok(String::new()),
        }
    }

    fn render_svg_element(&mut self, element: &Element) -> Result<String, Error> {
        let Some(name) = element.name().filter(|n| !n.is_empty()) else {
            return Ok(String::new());
        };

        // The special `defs` name diverts children into the shared <defs> block.
        if name == "defs" {
            for child in element.children() {
                let rendered = self.render_element(child)?;

                if !rendered.is_empty() {
                    let key = match child.attributes().and_then(|a| a.get("id")) {
                        Some(DynValue::Str(id)) => id.clone(),
                        _ => format!("_{}", self.defs.len()),
                    };

                    self.defs.insert(key, rendered);
                }
            }

            return Ok(String::new());
        }

        let stripped = self.attributes_without_animated_opacity(element);
        let attrs = self.render_attributes(stripped.as_ref().or(element.attributes()))?;
        let children = self.render_elements(element.children())?;

        if children.is_empty() {
            // A wrapper whose children all rendered to nothing, because an
            // optional component came up empty, has no content left to group.
            // It draws nothing either way, but a masked group without content
            // has an empty bounding box, and strict SVG parsers reject the
            // whole document over it. Wrappers that carry an id stay, so
            // references keep resolving.
            let has_id = element.attributes().and_then(|a| a.get("id")).is_some();

            if !element.children().is_empty() && !has_id {
                return Ok(String::new());
            }

            return Ok(self.apply_animations(format!("<{name}{attrs}/>"), element));
        }

        Ok(self.apply_animations(format!("<{name}{attrs}>{children}</{name}>"), element))
    }

    fn render_text_element(&mut self, element: &Element) -> String {
        match element.value() {
            Some(value) => xml::escape(&self.resolve_value(value)),
            None => String::new(),
        }
    }

    fn render_component_element(&mut self, element: &Element) -> Result<String, Error> {
        let Some(component_name) = element.name() else {
            return Ok(String::new());
        };

        let Some(variant_name) = self.resolver.variant(component_name) else {
            return Ok(String::new());
        };

        let style = self.style;
        let Some(component) = style.components().get(component_name) else {
            return Ok(String::new());
        };
        let Some(variant) = component.variants().get(&variant_name) else {
            return Ok(String::new());
        };

        let id = format!(
            "{}-{}-{}",
            component.source_name(),
            variant_name,
            self.hash_seed()
        );

        if !self.defs.contains_key(&id) {
            let body = self.render_elements(variant.elements())?;
            self.defs
                .insert(id.clone(), format!("<g id=\"{id}\">{body}</g>"));
        }

        let transforms = self.build_transforms(component);
        let stripped = self.attributes_without_animated_opacity(element);
        let user_attributes = stripped.as_ref().or(element.attributes());

        let merged = if transforms.is_empty() {
            user_attributes.cloned()
        } else {
            let mut merged = user_attributes.cloned().unwrap_or_default();
            let user_transform = match user_attributes.and_then(|a| a.get("transform")) {
                Some(DynValue::Str(t)) if !t.is_empty() => Some(t.clone()),
                _ => None,
            };

            let all_parts: Vec<String> = match user_transform {
                Some(user) => std::iter::once(user).chain(transforms).collect(),
                None => transforms,
            };

            // Insert updates in place if `transform` already exists (keeping its
            // position) or appends it, matching the JS object spread.
            merged.insert("transform".to_string(), DynValue::Str(all_parts.join(" ")));
            Some(merged)
        };

        let attrs = self.render_attributes(merged.as_ref())?;

        Ok(self.apply_animations(format!("<use{attrs} href=\"#{id}\"/>"), element))
    }

    /// The per-component `transform` fragments (translate, rotate, scale),
    /// ordered so that — once joined — scale is the innermost transform.
    fn build_transforms(&self, component: &Component) -> Vec<String> {
        let (rotate, translate_x, translate_y, scale) =
            self.resolver.component_transform(component.name());

        if translate_x == 0.0 && translate_y == 0.0 && rotate == 0.0 && scale == 1.0 {
            return Vec::new();
        }

        let mut transforms = Vec::new();
        let cx = component.width() / 2.0;
        let cy = component.height() / 2.0;
        let cx_value = number::format(cx);
        let cy_value = number::format(cy);

        if translate_x != 0.0 || translate_y != 0.0 {
            let x = number::format(translate_x / 100.0 * component.width());
            let y = number::format(translate_y / 100.0 * component.height());
            transforms.push(format!("translate({x}, {y})"));
        }

        if rotate != 0.0 {
            transforms.push(format!(
                "rotate({}, {cx_value}, {cy_value})",
                number::format(rotate)
            ));
        }

        if scale != 1.0 {
            transforms.push(format!(
                "translate({cx_value}, {cy_value}) scale({}) translate({}, {})",
                number::format(scale),
                number::format(-cx),
                number::format(-cy)
            ));
        }

        transforms
    }

    fn render_attributes(
        &mut self,
        attributes: Option<&IndexMap<String, DynValue>>,
    ) -> Result<String, Error> {
        let Some(attributes) = attributes else {
            return Ok(String::new());
        };

        let mut parts: Vec<String> = Vec::new();

        for (key, value) in attributes {
            let resolved = self.resolve_attribute_value(value)?;
            parts.push(format!("{key}=\"{}\"", xml::escape(&resolved)));
        }

        Ok(if parts.is_empty() {
            String::new()
        } else {
            format!(" {}", parts.join(" "))
        })
    }

    fn resolve_attribute_value(&mut self, value: &DynValue) -> Result<String, Error> {
        match value {
            DynValue::Str(s) => Ok(s.clone()),
            DynValue::Ref(reference) if reference.kind() == "color" => {
                self.resolve_color_reference(reference.name())
            }
            DynValue::Ref(reference) => Ok(self.resolve_variable(reference.name())),
        }
    }

    /// Resolves a named color into a hex string (solid / single color) or a
    /// `url(#…)` gradient reference, registering the gradient in `<defs>`.
    fn resolve_color_reference(&mut self, name: &str) -> Result<String, Error> {
        let colors = self.resolver.color(name)?;
        let fill = self.resolver.color_fill(name);

        if fill == "solid" || colors.len() <= 1 {
            return Ok(colors
                .into_iter()
                .next()
                .unwrap_or_else(|| "none".to_string()));
        }

        Ok(self.build_gradient_def(name, &colors, &fill))
    }

    fn build_gradient_def(&mut self, name: &str, colors: &[String], fill: &str) -> String {
        let rotation = self.resolver.color_angle(name);
        let id = format!("{name}-color-{}", self.hash_seed());
        let tag = if fill == "linear" {
            "linearGradient"
        } else {
            "radialGradient"
        };

        let rotate_attr = if rotation == 0.0 {
            String::new()
        } else {
            format!(
                " gradientTransform=\"rotate({}, 0.5, 0.5)\"",
                number::format(rotation)
            )
        };

        let last = colors.len() as f64 - 1.0;
        let mut stops = String::new();
        for (i, color) in colors.iter().enumerate() {
            let offset = number::format((i as f64 / last) * 100.0);
            stops.push_str(&format!(
                "<stop offset=\"{offset}%\" stop-color=\"{}\"/>",
                xml::escape(color)
            ));
        }

        self.defs.insert(
            id.clone(),
            format!("<{tag} id=\"{id}\"{rotate_attr}>{stops}</{tag}>"),
        );

        format!("url(#{id})")
    }

    fn resolve_value(&mut self, value: &DynValue) -> String {
        match value {
            DynValue::Str(s) => s.clone(),
            DynValue::Ref(reference) if reference.kind() == "variable" => {
                self.resolve_variable(reference.name())
            }
            DynValue::Ref(_) => String::new(),
        }
    }

    fn resolve_variable(&mut self, name: &str) -> String {
        match name {
            "initial" => self
                .initials()
                .chars()
                .next()
                .map(String::from)
                .unwrap_or_default(),
            "initials" => self.initials(),
            "fontWeight" => number::format(self.resolver.font_weight()),
            "fontFamily" => self.resolver.font_family(),
            _ => String::new(),
        }
    }

    fn initials(&mut self) -> String {
        self.cached_initials
            .get_or_insert_with(|| initials::from_seed(&self.resolver.seed()))
            .clone()
    }

    /// Returns the FNV-1a hex hash of the style source name and the seed,
    /// cached after the first call. The style name is part of the hash
    /// because styles share component and variant names: two avatars of
    /// different styles with the same seed would otherwise produce identical
    /// ids and steal each other's `<defs>` when inlined on one page.
    fn hash_seed(&mut self) -> String {
        self.cached_seed_hash
            .get_or_insert_with(|| {
                let source_name = self
                    .style
                    .meta()
                    .and_then(|meta| meta.source().name())
                    .unwrap_or("");
                fnv1a::hex(&format!("{}:{}", source_name, self.resolver.seed()))
            })
            .clone()
    }

    /// Returns the FNV-1a hex hash namespacing the animation class and
    /// keyframe names, cached after the first call. Extends the
    /// [`Self::hash_seed`] input with the animation speed and, for a by-name
    /// selection, the sorted names: two renders of the same avatar with
    /// different speeds or selections inlined on one page must not select
    /// each other's rules, while identical renders sharing identical rules is
    /// harmless deduplication. `true` adds no name suffix, so enabling all
    /// animations hashes as before.
    fn animation_hash(&mut self) -> String {
        self.cached_animation_hash
            .get_or_insert_with(|| {
                let source_name = self
                    .style
                    .meta()
                    .and_then(|meta| meta.source().name())
                    .unwrap_or("");
                let selection = self.resolver.animation();
                let names = match selection.names() {
                    Some(names) => {
                        let sorted: BTreeSet<&str> = names.iter().map(String::as_str).collect();

                        format!(":{}", sorted.into_iter().collect::<Vec<_>>().join(","))
                    }
                    None => String::new(),
                };

                fnv1a::hex(&format!(
                    "{}:{}:{}{}",
                    source_name,
                    self.resolver.seed(),
                    number::format(self.resolver.animation_speed()),
                    names
                ))
            })
            .clone()
    }

    /// Wraps an element's rendered markup in one `<g class="…">` per animation
    /// track and queues the matching CSS. A no-op when the `animation` option
    /// is off, the element carries no animations, or its markup rendered to
    /// nothing (the empty-wrapper pruning then also prunes the animation).
    ///
    /// Wrapper nesting is block 0 outermost, and within a block the canonical
    /// track order (translate before rotate before scale, opacity innermost) —
    /// the composition contract the Figma plugin maps onto node transforms.
    ///
    /// The element's own `opacity` rides on the innermost opacity wrapper as
    /// the resting value the keyframes then override.
    fn apply_animations(&mut self, markup: String, element: &Element) -> String {
        if markup.is_empty() {
            return markup;
        }

        let animations = element.animations();

        // The element check comes first: only styles that carry declarative
        // animations may touch the `animation` option, so the resolved-options
        // snapshot of every other avatar stays free of it.
        if animations.is_empty() {
            return markup;
        }

        let selection = self.resolver.animation();

        if selection.off() {
            return markup;
        }

        let mut classes: Vec<String> = Vec::new();
        let mut opacity_wrapper: Option<usize> = None;

        for animation in animations {
            // `true` plays every timeline. A name selection plays only the
            // timelines carrying one of those names, so unnamed timelines
            // stay static then.
            if !selection.matches(animation.name()) {
                continue;
            }

            for track in TRACK_ORDER {
                if let Some(track_data) = animation.tracks().get(track) {
                    if track == "opacity" {
                        opacity_wrapper = Some(classes.len());
                    }

                    classes.push(self.build_animation_css(
                        animation,
                        track,
                        track_data.keyframes(),
                    ));
                }
            }
        }

        let resting_opacity = match element.attributes().and_then(|a| a.get("opacity")) {
            Some(value) if opacity_wrapper.is_some() => {
                let mut only: IndexMap<String, DynValue> = IndexMap::new();
                only.insert("opacity".to_string(), value.clone());

                // The value comes from the same validated definition as every
                // other attribute, so a render error here is impossible.
                self.render_attributes(Some(&only)).unwrap_or_default()
            }
            _ => String::new(),
        };

        let mut result = markup;

        for (index, class) in classes.iter().enumerate().rev() {
            let opacity = if Some(index) == opacity_wrapper {
                resting_opacity.as_str()
            } else {
                ""
            };

            result = format!("<g class=\"{class}\"{opacity}>{result}</g>");
        }

        result
    }

    /// Strips the `opacity` attribute an animated opacity track takes over.
    ///
    /// A track writes the opacity the author means, not a factor on top of the
    /// element's own value: an element hidden with `opacity="0"` is a resting
    /// state the animation replaces, the way a CSS animation on the element
    /// itself would. The attribute therefore moves to the animating wrapper
    /// (see [`Self::apply_animations`]), where the keyframes override it. With
    /// the animation off no wrapper exists and the attribute stays where it is.
    ///
    /// Returns `None` when nothing is stripped, so the caller keeps using the
    /// element's own list.
    fn attributes_without_animated_opacity(
        &mut self,
        element: &Element,
    ) -> Option<IndexMap<String, DynValue>> {
        let attributes = element.attributes()?;

        // The element check comes first: only styles that carry declarative
        // animations may touch the `animation` option, so the resolved-options
        // snapshot of every other avatar stays free of it.
        if !attributes.contains_key("opacity") || element.animations().is_empty() {
            return None;
        }

        let selection = self.resolver.animation();

        if selection.off() {
            return None;
        }

        for animation in element.animations() {
            if !selection.matches(animation.name()) {
                continue;
            }

            if animation.tracks().contains_key("opacity") {
                let mut rest = attributes.clone();
                rest.shift_remove("opacity");

                return Some(rest);
            }
        }

        None
    }

    /// Generates the `@keyframes` block (deduplicated by content, so identical
    /// tracks on many elements share one block) and the class rule for a
    /// single track, and returns the class name.
    fn build_animation_css(
        &mut self,
        animation: &Animation,
        track: &str,
        keyframes: &[AnimationKeyframe],
    ) -> String {
        let body = keyframes_body(track, keyframes, animation.easing());

        let keyframes_name = match self.keyframes_by_content.get(&body) {
            Some(name) => name.clone(),
            None => {
                let name = format!("dbk-{}-{}", self.animation_hash(), self.keyframes_counter);

                self.keyframes_counter += 1;
                self.keyframes_css
                    .push(format!("@keyframes {name}{{{body}}}"));
                self.keyframes_by_content.insert(body, name.clone());
                name
            }
        };

        let speed = self.resolver.animation_speed();
        let duration = number::format(animation.duration() / speed);
        let delay = number::format(animation.delay() / speed);
        let iterations = match animation.iterations() {
            Some(count) => number::format(count),
            None => "infinite".to_string(),
        };
        let direction = direction_css(animation.direction());
        let fill = animation.fill();

        // Only rotate and scale pivot around a point. Translation and opacity
        // need no origin, so their rules skip the transform-box prefix.
        let origin_css = if track == "rotate" || track == "scaleX" || track == "scaleY" {
            let (x, y) = animation.origin();

            format!(
                "transform-box:fill-box;transform-origin:{}% {}%;",
                number::format(x),
                number::format(y)
            )
        } else {
            String::new()
        };

        let class_name = format!(
            "dba-{}-{}",
            self.animation_hash(),
            self.animation_class_counter
        );

        self.animation_class_counter += 1;

        // The name comes last in the shorthand so it can never be mistaken for
        // a keyword. All seven tokens are always emitted so every port
        // serializes the same string.
        self.animation_css.push(format!(
            ".{class_name}{{{origin_css}animation:{duration}s {} {delay}s {iterations} {direction} {fill} {keyframes_name}}}",
            easing_css(animation.easing())
        ));

        class_name
    }

    /// Registers the accumulated animation CSS as a single `<style>` entry in
    /// the shared `<defs>` block, wrapped in a reduced-motion media query so
    /// users who prefer reduced motion get the static avatar. A no-op when no
    /// animation CSS was produced.
    fn register_animation_style(&mut self) {
        if self.keyframes_css.is_empty() {
            return;
        }

        self.defs.insert(
            "animation-style".to_string(),
            format!(
                "<style>@media (prefers-reduced-motion:no-preference){{{}{}}}</style>",
                self.keyframes_css.concat(),
                self.animation_css.concat()
            ),
        );
    }
}

/// Serializes a track's keyframes to a `@keyframes` body. Endpoints are padded
/// with copies of the nearest keyframe so the resting value holds outside the
/// keyframed span, matching Figma's hold semantics. A keyframe's easing shapes
/// the segment to the next keyframe and is emitted only when it differs from
/// the block default (the rule's timing function covers the rest). The last
/// keyframe has no following segment, so its easing is never emitted.
fn keyframes_body(
    track: &str,
    keyframes: &[AnimationKeyframe],
    default_easing: Option<&Easing>,
) -> String {
    let mut list: Vec<(f64, f64, Option<&Easing>)> = keyframes
        .iter()
        .map(|keyframe| (keyframe.at(), keyframe.value(), keyframe.easing()))
        .collect();

    if let Some(&(at, value, _)) = list.first() {
        if at > 0.0 {
            list.insert(0, (0.0, value, None));
        }
    }

    if let Some(&(at, value, _)) = list.last() {
        if at < 100.0 {
            list.push((100.0, value, None));
        }
    }

    let default_css = easing_css(default_easing);
    let mut body = String::new();

    for (index, &(at, value, easing)) in list.iter().enumerate() {
        let css = match easing {
            Some(easing) if index < list.len() - 1 => easing_css(Some(easing)),
            _ => default_css.clone(),
        };
        let timing = if css == default_css {
            String::new()
        } else {
            format!(";animation-timing-function:{css}")
        };

        body.push_str(&format!(
            "{}%{{{}{timing}}}",
            number::format(at),
            track_declaration(track, value)
        ));
    }

    body
}

/// Returns the CSS declaration animating one track at one keyframe value.
fn track_declaration(track: &str, value: f64) -> String {
    let v = number::format(value);

    match track {
        "translateX" => format!("transform:translateX({v}px)"),
        "translateY" => format!("transform:translateY({v}px)"),
        "rotate" => format!("transform:rotate({v}deg)"),
        "scaleX" => format!("transform:scaleX({v})"),
        "scaleY" => format!("transform:scaleY({v})"),
        _ => format!("opacity:{v}"),
    }
}

/// Serializes an easing to its CSS form. `hold` renders as `step-end`. The
/// absent default is `linear`.
fn easing_css(easing: Option<&Easing>) -> String {
    match easing {
        Some(Easing::Keyword(keyword)) => match keyword.as_str() {
            "ease" => "ease",
            "easeIn" => "ease-in",
            "easeOut" => "ease-out",
            "easeInOut" => "ease-in-out",
            "hold" => "step-end",
            _ => "linear",
        }
        .to_string(),
        Some(Easing::Bezier(bezier)) => format!(
            "cubic-bezier({}, {}, {}, {})",
            number::format(bezier.x1),
            number::format(bezier.y1),
            number::format(bezier.x2),
            number::format(bezier.y2)
        ),
        None => "linear".to_string(),
    }
}

/// Maps a definition direction to its CSS keyword (`alternateReverse` is the
/// only one whose spellings differ). The absent default is `normal`.
fn direction_css(direction: Option<&str>) -> &'static str {
    match direction {
        Some("reverse") => "reverse",
        Some("alternate") => "alternate",
        Some("alternateReverse") => "alternate-reverse",
        _ => "normal",
    }
}

/// Suffixes every `id` declaration and reference with a random hex string so
/// that multiple instances of the same avatar do not collide in a shared
/// document. Uses process randomness intentionally — a PRNG-derived suffix
/// would produce the same ID for the same seed.
fn randomize_ids(svg: &str) -> String {
    // `(?-u:\b)` is the ASCII word boundary. JavaScript counts only
    // [A-Za-z0-9_] as word characters, so the reference collects an `id="` that
    // follows a letter such as `é`, while the Unicode-aware boundary of the
    // `regex` crate skips it. The suffixed id sets have to be identical, so the
    // narrower boundary wins.
    static ID_DECL: LazyLock<Regex> =
        LazyLock::new(|| Regex::new(r#"(?-u:\b)id="([^"]+)""#).unwrap());

    let random = RandomState::new().build_hasher().finish();
    let suffix = format!("{:06x}", (random as u32) & 0x00ff_ffff);

    let mut seen = HashSet::new();
    let mut ids: Vec<String> = Vec::new();
    for caps in ID_DECL.captures_iter(svg) {
        let id = caps[1].to_string();
        if seen.insert(id.clone()) {
            ids.push(id);
        }
    }

    if ids.is_empty() {
        return svg.to_string();
    }

    let alternation = ids
        .iter()
        .map(|id| regex::escape(id))
        .collect::<Vec<_>>()
        .join("|");
    let pattern = format!(r##"(id="|url\(#|href="#)({alternation})("|\))"##);
    let re = Regex::new(&pattern).unwrap();

    re.replace_all(svg, |caps: &regex::Captures| {
        format!("{}{}-{suffix}{}", &caps[1], &caps[2], &caps[3])
    })
    .into_owned()
}
