/**
 * Do not change this file manually! This file was generated with the "Dicebear Exporter"-Plugin for Figma.
 *
 * Plugin: https://www.figma.com/community/plugin/1005765655729342787
 * File: https://www.figma.com/file/XXfL2r5Wylk623KpxDt7gO
 */

import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    backgroundColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern: '^(transparent|[a-fA-F0-9]{6})$',
      },
      default: ['f2d3b1', 'ecad80', '9e5622', '763900'],
    },
    eyebrows: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
        ],
      },
      default: [
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
      ],
    },
    eyes: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
    glasses: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['variant01', 'variant02', 'variant03', 'variant04', 'variant05'],
      },
      default: [
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
      ],
    },
    glassesProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    mouth: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant30',
          'variant29',
          'variant28',
          'variant27',
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant30',
        'variant29',
        'variant28',
        'variant27',
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
  },
};
