import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  title: 'Options',
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    backgroundColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['variant02', 'variant03', 'variant04', 'variant05'],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
      ],
    },
    eyebrows: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
        ],
      },
      default: [
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
      ],
      examples: [
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
      ],
    },
    eyes: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant26'],
        ['variant25'],
        ['variant24'],
        ['variant23'],
        ['variant22'],
        ['variant21'],
        ['variant20'],
        ['variant19'],
        ['variant18'],
        ['variant17'],
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    features: {
      type: 'array',
      items: { type: 'string', enum: ['blush', 'birthmark', 'freckles'] },
      default: ['blush', 'birthmark', 'freckles'],
      examples: [['blush'], ['birthmark'], ['freckles']],
    },
    featuresProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 5,
    },
    glasses: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['variant01', 'variant02', 'variant03', 'variant04', 'variant05'],
      },
      default: [
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
      ],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
      ],
    },
    glassesProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    mouth: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant30',
          'variant29',
          'variant28',
          'variant27',
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant30',
        'variant29',
        'variant28',
        'variant27',
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant30'],
        ['variant29'],
        ['variant28'],
        ['variant27'],
        ['variant26'],
        ['variant25'],
        ['variant24'],
        ['variant23'],
        ['variant22'],
        ['variant21'],
        ['variant20'],
        ['variant19'],
        ['variant18'],
        ['variant17'],
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
  },
  additionalProperties: false,
};
