/**
 * Do not change this file manually! This file was generated with the "Dicebear Exporter"-Plugin for Figma.
 *
 * Plugin: https://www.figma.com/community/plugin/1005765655729342787
 * File: https://www.figma.com/file/WTcivb1XPf5ODtyv7ZNnU9
 */

import { escape } from '@dicebear/core';
import type { ComponentGroup, ComponentPickCollection, ColorPickCollection } from '../types.js';

export const beard: ComponentGroup = {
  'variant08': (components: ComponentPickCollection, colors: ColorPickCollection) => `<mask id="beardVariant08-a" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="3" y="6" width="10" height="6"><path opacity=".9" d="M3 6h1v3h8V6h1v5h-1v1H4v-1H3V6Z" fill="${escape.xml(`${colors.hair}`)}"/></mask><g mask="url(#beardVariant08-a)"><path fill="${escape.xml(`${colors.hair}`)}" d="M0 0h16v16H0z"/><path fill="#fff" fill-opacity=".3" d="M0 0h16v16H0z"/></g>`,
  'variant07': (components: ComponentPickCollection, colors: ColorPickCollection) => `<mask id="beardVariant07-a" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="3" y="9" width="10" height="3"><path opacity=".9" d="M3 9v2h1v1h8v-1h1V9H3Z" fill="${escape.xml(`${colors.hair}`)}"/></mask><g mask="url(#beardVariant07-a)"><path fill="${escape.xml(`${colors.hair}`)}" d="M0 0h16v16H0z"/><path fill="#fff" fill-opacity=".3" d="M0 0h16v16H0z"/></g>`,
  'variant06': (components: ComponentPickCollection, colors: ColorPickCollection) => `<mask id="beardVariant06-a" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="3" y="9" width="10" height="3"><path opacity=".9" d="M3 9h3v1h4V9h3v2h-1v1H4v-1H3V9Z" fill="${escape.xml(`${colors.hair}`)}"/></mask><g mask="url(#beardVariant06-a)"><path fill="${escape.xml(`${colors.hair}`)}" d="M0 0h16v16H0z"/><path fill="#fff" fill-opacity=".3" d="M0 0h16v16H0z"/></g>`,
  'variant05': (components: ComponentPickCollection, colors: ColorPickCollection) => `<mask id="beardVariant05-a" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="3" y="6" width="10" height="6"><path opacity=".9" d="M3 6h1v2h1v1h6V8h1V6h1v5h-1v1H4v-1H3V6Z" fill="${escape.xml(`${colors.hair}`)}"/></mask><g mask="url(#beardVariant05-a)"><path fill="${escape.xml(`${colors.hair}`)}" d="M0 0h16v16H0z"/><path fill="#fff" fill-opacity=".3" d="M0 0h16v16H0z"/></g>`,
  'variant04': (components: ComponentPickCollection, colors: ColorPickCollection) => `<mask id="beardVariant04-a" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="6" y="11" width="4" height="1"><path opacity=".9" fill="${escape.xml(`${colors.hair}`)}" d="M6 11h4v1H6z"/></mask><g mask="url(#beardVariant04-a)"><path fill="${escape.xml(`${colors.hair}`)}" d="M0 0h16v16H0z"/><path fill="#fff" fill-opacity=".3" d="M0 0h16v16H0z"/></g>`,
  'variant03': (components: ComponentPickCollection, colors: ColorPickCollection) => `<mask id="beardVariant03-a" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="3" y="9" width="10" height="5"><path opacity=".9" d="M3 9h2v1h6V9h2v2h-1v2h-1v1H5v-1H4v-2H3V9Z" fill="${escape.xml(`${colors.hair}`)}"/></mask><g mask="url(#beardVariant03-a)"><path fill="${escape.xml(`${colors.hair}`)}" d="M0 0h16v16H0z"/><path fill="#fff" fill-opacity=".3" d="M0 0h16v16H0z"/></g>`,
  'variant02': (components: ComponentPickCollection, colors: ColorPickCollection) => `<mask id="beardVariant02-a" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="5" y="11" width="6" height="3"><path opacity=".9" d="M5 11h6v1h-1v1H9v1H7v-1H6v-1H5v-1Z" fill="${escape.xml(`${colors.hair}`)}"/></mask><g mask="url(#beardVariant02-a)"><path fill="${escape.xml(`${colors.hair}`)}" d="M0 0h16v16H0z"/><path fill="#fff" fill-opacity=".3" d="M0 0h16v16H0z"/></g>`,
  'variant01': (components: ComponentPickCollection, colors: ColorPickCollection) => `<mask id="beardVariant01-a" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="3" y="8" width="10" height="4"><path opacity=".9" d="M3 8h2v1h1v1h4V9h1V8h2v3h-1v1H4v-1H3V8Z" fill="${escape.xml(`${colors.hair}`)}"/></mask><g mask="url(#beardVariant01-a)"><path fill="${escape.xml(`${colors.hair}`)}" d="M0 0h16v16H0z"/><path fill="#fff" fill-opacity=".3" d="M0 0h16v16H0z"/></g>`,
}
