import defaults from "./defaults";

export default {
  ...defaults,
  style: {
    type: "select",
    values: ["transparent", "circle"],
    defaultValue: "transparent",
  },
  mode: {
    type: "select",
    values: ["include", "exclude"],
    defaultValue: "include",
  },
  top: {
    type: "checkbox",
    values: ["longHair", "shortHair", "eyepatch", "hat", "hijab", "turban"],
    defaultValue: [],
  },
  topChance: {
    type: "range",
    values: [0, 100],
    defaultValue: 90,
  },
  hatColor: {
    type: "checkbox",
    values: [
      "black",
      "blue",
      "gray",
      "heather",
      "pastel",
      "pink",
      "red",
      "white",
    ],
    defaultValue: [],
  },
  hairColor: {
    type: "checkbox",
    values: [
      "auburn",
      "black",
      "blonde",
      "brown",
      "pastel",
      "platinum",
      "red",
      "gray",
    ],
    defaultValue: [],
  },
  accessories: {
    type: "checkbox",
    values: [
      "kurt",
      "prescription01",
      "prescription02",
      "round",
      "sunglasses",
      "wayfarers",
    ],
    defaultValue: [],
  },
  accessoriesChance: {
    type: "range",
    values: [0, 100],
    defaultValue: 10,
  },
  accessoriesColor: {
    type: "checkbox",
    values: [
      "black",
      "blue",
      "gray",
      "heather",
      "pastel",
      "pink",
      "red",
      "white",
    ],
    defaultValue: [],
  },
  facialHair: {
    type: "checkbox",
    values: [
      "medium",
      "light",
      "majestic",
      "fancy",
      "magnum",
      "pastel",
      "gray",
    ],
    defaultValue: [],
  },
  facialHairChance: {
    type: "range",
    values: [0, 100],
    defaultValue: 10,
  },
  facialHairColor: {
    type: "checkbox",
    values: [
      "auburn",
      "black",
      "blonde",
      "brown",
      "pastel",
      "platinum",
      "red",
      "gray",
    ],
    defaultValue: [],
  },
  clothes: {
    type: "checkbox",
    values: ["blazer", "sweater", "shirt", "hoodie", "overall"],
    defaultValue: [],
  },
  clothesColor: {
    type: "checkbox",
    values: [
      "black",
      "blue",
      "gray",
      "heather",
      "pastel",
      "pink",
      "red",
      "white",
    ],
    defaultValue: [],
  },
  eyes: {
    type: "checkbox",
    values: [
      "close",
      "cry",
      "default",
      "dizzy",
      "roll",
      "happy",
      "hearts",
      "side",
      "squint",
      "surprised",
      "wink",
      "winkWacky",
    ],
    defaultValue: [],
  },
  eyebrow: {
    type: "checkbox",
    values: [
      "angry",
      "default",
      "flat",
      "raised",
      "sad",
      "unibrow",
      "up",
      "frown",
    ],
    defaultValue: [],
  },
  mouth: {
    type: "checkbox",
    values: [
      "concerned",
      "default",
      "disbelief",
      "eating",
      "grimace",
      "sad",
      "scream",
      "serious",
      "smile",
      "tongue",
      "twinkle",
      "vomit",
    ],
    defaultValue: [],
  },
  skin: {
    type: "checkbox",
    values: [
      "tanned",
      "yellow",
      "pale",
      "light",
      "brown",
      "darkBrown",
      "black",
    ],
    defaultValue: [],
  },
};
