import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  title: 'Options',
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    baseColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['transparent'],
      examples: [['transparent'], ['white']],
    },
    beard: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['variant05', 'variant04', 'variant03', 'variant02', 'variant01'],
      },
      default: [
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    beardProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    eyes: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    face: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    mouth: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant18'],
        ['variant17'],
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    mustache: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['variant04', 'variant03', 'variant02', 'variant01'],
      },
      default: ['variant04', 'variant03', 'variant02', 'variant01'],
      examples: [['variant04'], ['variant03'], ['variant02'], ['variant01']],
    },
    mustacheProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    nose: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    top: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant30',
          'variant29',
          'variant28',
          'variant27',
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant30',
        'variant29',
        'variant28',
        'variant27',
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant30'],
        ['variant29'],
        ['variant28'],
        ['variant27'],
        ['variant26'],
        ['variant25'],
        ['variant24'],
        ['variant23'],
        ['variant22'],
        ['variant21'],
        ['variant20'],
        ['variant19'],
        ['variant18'],
        ['variant17'],
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    topColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['yellow', 'purple', 'red', 'blue', 'green', 'black'],
      examples: [
        ['yellow'],
        ['purple'],
        ['red'],
        ['blue'],
        ['green'],
        ['black'],
      ],
    },
  },
  additionalProperties: false,
};
