package render

import (
	"fmt"
	"math/rand/v2"
	"regexp"
	"strings"

	"github.com/dicebear/dicebear-go/v10/internal/initials"
	"github.com/dicebear/dicebear-go/v10/internal/num"
	"github.com/dicebear/dicebear-go/v10/internal/prng"
	"github.com/dicebear/dicebear-go/v10/internal/style"
)

// renderer walks a style's element tree and turns it into the final SVG markup.
//
// The renderer is single-use: it accumulates <defs> entries and per-render
// caches across method calls, so a fresh instance is required per avatar. A
// circular color reference encountered during resolution surfaces as an error
// from render.
type renderer struct {
	style               *style.Style
	resolver            *resolver
	defs                *orderedDefs
	cachedSeedHash      *string
	cachedInitials      *string
	cachedAnimationHash *string
	keyframesCss        []string
	animationCss        []string
	keyframesByContent  map[string]string
	keyframesCounter    int
	animationCounter    int
}

func newRenderer(s *style.Style, res *resolver) *renderer {
	return &renderer{
		style:              s,
		resolver:           res,
		defs:               newOrderedDefs(),
		keyframesByContent: map[string]string{},
	}
}

// render builds the complete SVG document for the avatar.
func (r *renderer) render() (string, error) {
	cv := r.style.Canvas()

	background, err := r.renderBackground(cv)
	if err != nil {
		return "", err
	}
	body, err := r.renderElements(cv.Elements)
	if err != nil {
		return "", err
	}

	// Order matters: scale and flip around center, then rotate, translate, and
	// finally clip with border radius (outermost wrapper).
	body = r.applyScale(body, cv)
	body = r.applyFlip(body, cv)
	body = r.applyRotate(body, cv)
	body = r.applyTranslate(body, cv)
	body = r.applyBorderRadius(background+body, cv)

	r.registerAnimationStyle()

	metadata := licenseXML(r.style.Meta())

	defs := ""
	if r.defs.len() > 0 {
		defs = "<defs>" + r.defs.values() + "</defs>"
	}

	// Resolve size before title and the root attributes so the resolver memo
	// records the keys in the same order as the other ports — the JSON envelope
	// emits the resolved options in first-recorded order.
	size := r.resolver.size()

	var escapedTitle *string
	if t, ok := r.resolver.title(); ok {
		e := escapeXML(t)
		escapedTitle = &e
	}

	attrs := []string{
		`xmlns="http://www.w3.org/2000/svg"`,
		`viewBox="0 0 ` + num.Format(cv.Width) + " " + num.Format(cv.Height) + `"`,
	}

	rootAttributes, err := r.renderAttributes(r.style.RootAttributes())
	if err != nil {
		return "", err
	}
	if rootAttributes != "" {
		attrs = append(attrs, strings.TrimPrefix(rootAttributes, " "))
	}

	if escapedTitle != nil {
		attrs = append(attrs, `role="img"`, `aria-label="`+*escapedTitle+`"`)
	} else {
		attrs = append(attrs, `aria-hidden="true"`)
	}

	if size != nil {
		sv := num.Format(*size)
		attrs = append(attrs, `width="`+sv+`"`, `height="`+sv+`"`)
	}

	titleElement := ""
	if escapedTitle != nil {
		titleElement = "<title>" + *escapedTitle + "</title>"
	}

	svg := "<svg " + strings.Join(attrs, " ") + ">" + "<!-- Generated by DiceBear (https://www.dicebear.com) -->" + metadata + defs + titleElement + body + "</svg>"

	if r.resolver.idRandomization() {
		svg = randomizeIDs(svg)
	}

	return svg, nil
}

func (r *renderer) applyFlip(body string, cv *style.Canvas) string {
	flip := r.resolver.flip()
	if flip == "none" {
		return body
	}

	w := num.Format(cv.Width)
	h := num.Format(cv.Height)

	var transform string
	switch flip {
	case "horizontal":
		transform = "translate(" + w + ", 0) scale(-1, 1)"
	case "vertical":
		transform = "translate(0, " + h + ") scale(1, -1)"
	case "both":
		transform = "translate(" + w + ", " + h + ") scale(-1, -1)"
	default:
		return body
	}

	return `<g transform="` + transform + `">` + body + "</g>"
}

func (r *renderer) applyScale(body string, cv *style.Canvas) string {
	scale := r.resolver.scale()
	if scale == 1 {
		return body
	}

	cx := cv.Width / 2
	cy := cv.Height / 2

	return `<g transform="translate(` + num.Format(cx) + ", " + num.Format(cy) +
		") scale(" + num.Format(scale) + ") translate(" + num.Format(-cx) + ", " +
		num.Format(-cy) + `)">` + body + "</g>"
}

func (r *renderer) applyBorderRadius(body string, cv *style.Canvas) string {
	radius := r.resolver.borderRadius()
	id := "clip-" + r.hashSeed()
	rx := num.Format(radius / 100 * cv.Width)
	ry := num.Format(radius / 100 * cv.Height)

	r.defs.set(id, `<clipPath id="`+id+`"><rect width="`+num.Format(cv.Width)+
		`" height="`+num.Format(cv.Height)+`" rx="`+rx+`" ry="`+ry+`"/></clipPath>`)

	return `<g clip-path="url(#` + id + `)">` + body + "</g>"
}

func (r *renderer) applyRotate(body string, cv *style.Canvas) string {
	rotate := r.resolver.rotate()
	if rotate == 0 {
		return body
	}

	cx := cv.Width / 2
	cy := cv.Height / 2

	return `<g transform="rotate(` + num.Format(rotate) + ", " + num.Format(cx) + ", " +
		num.Format(cy) + `)">` + body + "</g>"
}

func (r *renderer) applyTranslate(body string, cv *style.Canvas) string {
	tx := r.resolver.translateX()
	ty := r.resolver.translateY()
	if tx == 0 && ty == 0 {
		return body
	}

	x := num.Format(tx / 100 * cv.Width)
	y := num.Format(ty / 100 * cv.Height)

	return `<g transform="translate(` + x + ", " + y + `)">` + body + "</g>"
}

func (r *renderer) renderBackground(cv *style.Canvas) (string, error) {
	colors, err := r.resolver.color("background")
	if err != nil {
		return "", err
	}
	if len(colors) == 0 {
		return "", nil
	}

	ref, err := r.resolveColorReference("background")
	if err != nil {
		return "", err
	}

	return `<rect width="` + num.Format(cv.Width) + `" height="` + num.Format(cv.Height) +
		`" fill="` + escapeXML(ref) + `"/>`, nil
}

func (r *renderer) renderElements(elements []style.Element) (string, error) {
	var b strings.Builder
	for i := range elements {
		s, err := r.renderElement(&elements[i])
		if err != nil {
			return "", err
		}
		b.WriteString(s)
	}
	return b.String(), nil
}

func (r *renderer) renderElement(el *style.Element) (string, error) {
	switch el.Type {
	case "element":
		return r.renderSvgElement(el)
	case "text":
		return r.renderTextElement(el), nil
	case "component":
		return r.renderComponentElement(el)
	default:
		return "", nil
	}
}

func (r *renderer) renderSvgElement(el *style.Element) (string, error) {
	if el.Name == nil || *el.Name == "" {
		return "", nil
	}
	name := *el.Name

	// The special `defs` name diverts children into the shared <defs> block.
	if name == "defs" {
		for i := range el.Children {
			child := &el.Children[i]
			rendered, err := r.renderElement(child)
			if err != nil {
				return "", err
			}
			if rendered == "" {
				continue
			}

			key := fmt.Sprintf("_%d", r.defs.len())
			if id, ok := child.Attributes.Get("id"); ok && !id.IsRef() {
				key = id.Str()
			}
			r.defs.set(key, rendered)
		}
		return "", nil
	}

	attrs, err := r.renderAttributes(r.attributesWithoutAnimatedOpacity(el))
	if err != nil {
		return "", err
	}
	children, err := r.renderElements(el.Children)
	if err != nil {
		return "", err
	}

	if children == "" {
		// A wrapper whose children all rendered to nothing, because an optional
		// component came up empty, has no content left to group. It draws
		// nothing either way, but a masked group without content has an empty
		// bounding box, and strict SVG parsers reject the whole document over
		// it. Wrappers that carry an id stay, so references keep resolving.
		if _, hasID := el.Attributes.Get("id"); len(el.Children) > 0 && !hasID {
			return "", nil
		}

		return r.applyAnimations("<"+name+attrs+"/>", el), nil
	}
	return r.applyAnimations("<"+name+attrs+">"+children+"</"+name+">", el), nil
}

func (r *renderer) renderTextElement(el *style.Element) string {
	if el.Value == nil {
		return ""
	}
	return escapeXML(r.resolveValue(*el.Value))
}

func (r *renderer) renderComponentElement(el *style.Element) (string, error) {
	if el.Name == nil {
		return "", nil
	}
	componentName := *el.Name

	variantName, ok := r.resolver.variant(componentName)
	if !ok {
		return "", nil
	}

	comp, ok := r.style.Components()[componentName]
	if !ok {
		return "", nil
	}

	variant, ok := comp.Variants()[variantName]
	if !ok {
		return "", nil
	}

	id := comp.SourceName() + "-" + variantName + "-" + r.hashSeed()

	if !r.defs.has(id) {
		body, err := r.renderElements(variant.Elements)
		if err != nil {
			return "", err
		}
		r.defs.set(id, `<g id="`+id+`">`+body+"</g>")
	}

	transforms := r.buildTransforms(comp)

	own := r.attributesWithoutAnimatedOpacity(el)

	var merged *style.AttrList
	if len(transforms) == 0 {
		if !own.IsEmpty() {
			merged = own
		}
	} else {
		userTransform := ""
		if v, ok := own.Get("transform"); ok && !v.IsRef() && v.Str() != "" {
			userTransform = v.Str()
		}

		var allParts []string
		if userTransform != "" {
			allParts = append([]string{userTransform}, transforms...)
		} else {
			allParts = transforms
		}

		m := own.WithTransform(strings.Join(allParts, " "))
		merged = &m
	}

	attrs, err := r.renderAttributes(merged)
	if err != nil {
		return "", err
	}

	return r.applyAnimations("<use"+attrs+` href="#`+id+`"/>`, el), nil
}

// buildTransforms returns the per-component transform fragments (translate,
// rotate, scale), ordered so that — once joined — scale is the innermost
// transform.
func (r *renderer) buildTransforms(comp *style.Component) []string {
	rotate, translateX, translateY, scale := r.resolver.componentTransform(comp.Name())

	if translateX == 0 && translateY == 0 && rotate == 0 && scale == 1 {
		return nil
	}

	var transforms []string
	cx := comp.Width() / 2
	cy := comp.Height() / 2
	cxValue := num.Format(cx)
	cyValue := num.Format(cy)

	if translateX != 0 || translateY != 0 {
		x := num.Format(translateX / 100 * comp.Width())
		y := num.Format(translateY / 100 * comp.Height())
		transforms = append(transforms, "translate("+x+", "+y+")")
	}

	if rotate != 0 {
		transforms = append(transforms, "rotate("+num.Format(rotate)+", "+cxValue+", "+cyValue+")")
	}

	if scale != 1 {
		transforms = append(transforms, "translate("+cxValue+", "+cyValue+") scale("+
			num.Format(scale)+") translate("+num.Format(-cx)+", "+num.Format(-cy)+")")
	}

	return transforms
}

func (r *renderer) renderAttributes(attributes *style.AttrList) (string, error) {
	if attributes.IsEmpty() {
		return "", nil
	}

	entries := attributes.Entries()
	parts := make([]string, 0, len(entries))
	for _, entry := range entries {
		resolved, err := r.resolveAttributeValue(entry.Value)
		if err != nil {
			return "", err
		}
		parts = append(parts, entry.Key+`="`+escapeXML(resolved)+`"`)
	}

	if len(parts) == 0 {
		return "", nil
	}
	return " " + strings.Join(parts, " "), nil
}

func (r *renderer) resolveAttributeValue(value style.DynValue) (string, error) {
	if !value.IsRef() {
		return value.Str(), nil
	}
	if value.RefKind() == "color" {
		return r.resolveColorReference(value.RefName())
	}
	return r.resolveVariable(value.RefName()), nil
}

// resolveColorReference resolves a named color into a hex string (solid /
// single color) or a url(#…) gradient reference, registering the gradient in
// <defs>.
func (r *renderer) resolveColorReference(name string) (string, error) {
	colors, err := r.resolver.color(name)
	if err != nil {
		return "", err
	}
	fill := r.resolver.colorFill(name)

	if fill == "solid" || len(colors) <= 1 {
		if len(colors) > 0 {
			return colors[0], nil
		}
		return "none", nil
	}

	return r.buildGradientDef(name, colors, fill), nil
}

func (r *renderer) buildGradientDef(name string, colors []string, fill string) string {
	rotation := r.resolver.colorAngle(name)
	id := name + "-color-" + r.hashSeed()

	tag := "radialGradient"
	if fill == "linear" {
		tag = "linearGradient"
	}

	rotateAttr := ""
	if rotation != 0 {
		rotateAttr = ` gradientTransform="rotate(` + num.Format(rotation) + `, 0.5, 0.5)"`
	}

	last := float64(len(colors)) - 1
	var stops strings.Builder
	for i, c := range colors {
		offset := num.Format((float64(i) / last) * 100)
		stops.WriteString(`<stop offset="` + offset + `%" stop-color="` + escapeXML(c) + `"/>`)
	}

	r.defs.set(id, "<"+tag+` id="`+id+`"`+rotateAttr+">"+stops.String()+"</"+tag+">")

	return "url(#" + id + ")"
}

func (r *renderer) resolveValue(value style.DynValue) string {
	if !value.IsRef() {
		return value.Str()
	}
	if value.RefKind() == "variable" {
		return r.resolveVariable(value.RefName())
	}
	return ""
}

func (r *renderer) resolveVariable(name string) string {
	switch name {
	case "initial":
		runes := []rune(r.initials())
		if len(runes) > 0 {
			return string(runes[0])
		}
		return ""
	case "initials":
		return r.initials()
	case "fontWeight":
		return num.Format(r.resolver.fontWeight())
	case "fontFamily":
		return r.resolver.fontFamily()
	default:
		return ""
	}
}

func (r *renderer) initials() string {
	if r.cachedInitials == nil {
		v := initials.FromSeed(r.resolver.seed())
		r.cachedInitials = &v
	}
	return *r.cachedInitials
}

// hashSeed returns the FNV-1a hex hash of the style source name and the
// seed, cached after the first call. The style name is part of the hash
// because styles share component and variant names: two avatars of different
// styles with the same seed would otherwise produce identical ids and steal
// each other's <defs> when inlined on one page.
func (r *renderer) hashSeed() string {
	if r.cachedSeedHash == nil {
		sourceName := ""
		if meta := r.style.Meta(); meta != nil && meta.Source.Name != nil {
			sourceName = *meta.Source.Name
		}
		v := prng.Hex(sourceName + ":" + r.resolver.seed())
		r.cachedSeedHash = &v
	}
	return *r.cachedSeedHash
}

// orderedDefs is an insertion-ordered string map for <defs> entries. Updating an
// existing key keeps its original position, matching the JS Map semantics.
type orderedDefs struct {
	keys []string
	m    map[string]string
}

func newOrderedDefs() *orderedDefs {
	return &orderedDefs{m: map[string]string{}}
}

func (d *orderedDefs) has(key string) bool {
	_, ok := d.m[key]
	return ok
}

func (d *orderedDefs) set(key, value string) {
	if _, ok := d.m[key]; !ok {
		d.keys = append(d.keys, key)
	}
	d.m[key] = value
}

func (d *orderedDefs) len() int {
	return len(d.keys)
}

func (d *orderedDefs) values() string {
	var b strings.Builder
	for _, k := range d.keys {
		b.WriteString(d.m[k])
	}
	return b.String()
}

// randomizeIDs suffixes every id declaration and reference with a random hex
// string so that multiple instances of the same avatar do not collide in a
// shared document. Process randomness is intentional — a PRNG-derived suffix
// would produce the same ID for the same seed.
func randomizeIDs(svg string) string {
	// % 0xffffff yields 0..0xfffffe, matching JS Math.floor(random()*0xffffff)
	// (exclusive upper bound) rather than a masked 0..0xffffff.
	suffix := fmt.Sprintf("%06x", rand.Uint32()%0xffffff)

	seen := map[string]struct{}{}
	var ids []string
	for _, m := range reIDDecl.FindAllStringSubmatch(svg, -1) {
		id := m[1]
		if _, ok := seen[id]; !ok {
			seen[id] = struct{}{}
			ids = append(ids, id)
		}
	}

	if len(ids) == 0 {
		return svg
	}

	escaped := make([]string, len(ids))
	for i, id := range ids {
		escaped[i] = regexp.QuoteMeta(id)
	}
	pattern := `(id="|url\(#|href="#)(` + strings.Join(escaped, "|") + `)("|\))`
	re := regexp.MustCompile(pattern)

	return re.ReplaceAllString(svg, "${1}${2}-"+suffix+"${3}")
}

var reIDDecl = regexp.MustCompile(`\bid="([^"]+)"`)
