"""Walks a style's element tree and turns it into the final SVG markup."""

from __future__ import annotations

import random
import re
from typing import Any

from .prng import Fnv1a
from .resolver import Resolver
from .style import Style
from .style.canvas import Canvas
from .style.component import Component
from .style.element import Element
from .utils.initials import Initials
from .utils.license import License
from .utils.number import Number
from .utils.xml import Xml

# JavaScript counts only [A-Za-z0-9_] as word characters, Python's `\b`
# is Unicode-aware. The lookbehind spells out the reference set so that an
# id preceded by a letter such as `é` is collected here too.
_ID_PATTERN = re.compile(r'(?<![A-Za-z0-9_])id="([^"]+)"')

# The canonical track order, outermost wrapper to innermost. It mirrors the
# usual translate → rotate → scale transform composition. Every port must wrap
# in this exact order for the outputs to stay byte-identical.
_TRACK_ORDER = ("translateX", "translateY", "rotate", "scaleX", "scaleY", "opacity")

_DIRECTION_CSS = {
    "normal": "normal",
    "reverse": "reverse",
    "alternate": "alternate",
    "alternateReverse": "alternate-reverse",
}

_EASING_KEYWORD_CSS = {
    "linear": "linear",
    "ease": "ease",
    "easeIn": "ease-in",
    "easeOut": "ease-out",
    "easeInOut": "ease-in-out",
    "hold": "step-end",
}


class Renderer:
    """Walks a style's element tree and turns it into the final SVG markup.

    The renderer is single-use: it accumulates ``<defs>`` entries and per-render
    caches across method calls, so a fresh instance is required per avatar.
    """

    def __init__(self, style: Style, resolver: Resolver) -> None:
        self._style = style
        self._resolver = resolver
        self._defs: dict[str, str] = {}
        self._cached_seed_hash: str | None = None
        self._cached_initials: str | None = None
        self._cached_animation_hash: str | None = None
        self._cached_random_suffix: str | None = None
        self._keyframes_css: list[str] = []
        self._animation_css: list[str] = []
        self._keyframes_by_content: dict[str, str] = {}
        self._keyframes_counter = 0
        self._animation_class_counter = 0

    def render(self) -> str:
        """Build the complete SVG document for the avatar."""
        canvas = self._style.canvas()
        background = self._render_background(canvas)
        body = self._render_elements(canvas.elements())

        # Order matters: scale and flip around center, then rotate, translate,
        # and finally clip with border radius (outermost wrapper).
        body = self._apply_scale(body, canvas)
        body = self._apply_flip(body, canvas)
        body = self._apply_rotate(body, canvas)
        body = self._apply_translate(body, canvas)
        body = self._apply_border_radius(background + body, canvas)

        self._register_animation_style()

        metadata = License.xml(self._style.meta())
        defs = "<defs>" + "".join(self._defs.values()) + "</defs>" if self._defs else ""
        size = self._resolver.size()

        title = self._resolver.title()
        escaped_title = Xml.escape(title) if title is not None else None

        width = Number.format(canvas.width())
        height = Number.format(canvas.height())
        attrs = [
            'xmlns="http://www.w3.org/2000/svg"',
            f'viewBox="0 0 {width} {height}"',
        ]

        root_attributes = self._render_attributes(self._style.attributes())

        if root_attributes != "":
            attrs.append(root_attributes.lstrip())

        if escaped_title is not None:
            attrs.append('role="img"')
            attrs.append(f'aria-label="{escaped_title}"')
        else:
            attrs.append('aria-hidden="true"')

        if size is not None:
            attrs.append(f'width="{Number.format(size)}"')
            attrs.append(f'height="{Number.format(size)}"')

        title_element = (
            f"<title>{escaped_title}</title>" if escaped_title is not None else ""
        )

        svg = (
            "<svg "
            + " ".join(attrs)
            + ">"
            + "<!-- Generated by DiceBear (https://www.dicebear.com) -->"
            + metadata
            + defs
            + title_element
            + body
            + "</svg>"
        )

        if self._resolver.id_randomization():
            svg = self._randomize_ids(svg)

        return svg

    def _apply_flip(self, body: str, canvas: Canvas) -> str:
        """Wrap ``body`` in a flip transform when ``flip`` is not ``'none'``."""
        flip = self._resolver.flip()

        if flip == "none":
            return body

        w = Number.format(canvas.width())
        h = Number.format(canvas.height())

        transform = {
            "horizontal": f"translate({w}, 0) scale(-1, 1)",
            "vertical": f"translate(0, {h}) scale(1, -1)",
            "both": f"translate({w}, {h}) scale(-1, -1)",
        }[flip]

        return f'<g transform="{transform}">{body}</g>'

    def _apply_scale(self, body: str, canvas: Canvas) -> str:
        """Wrap ``body`` in a uniform scale around center when scale != 1."""
        scale = self._resolver.scale()

        if scale == 1:
            return body

        cx = canvas.width() / 2
        cy = canvas.height() / 2
        cx_value = Number.format(cx)
        cy_value = Number.format(cy)
        scale_value = Number.format(scale)
        neg_cx = Number.format(-cx)
        neg_cy = Number.format(-cy)

        return (
            f'<g transform="translate({cx_value}, {cy_value}) '
            f"scale({scale_value}) "
            f'translate({neg_cx}, {neg_cy})">{body}</g>'
        )

    def _apply_border_radius(self, body: str, canvas: Canvas) -> str:
        """Clip ``body`` to the (rounded) canvas rectangle via a ``clipPath``.

        The clip is always applied so transformed content cannot bleed past the
        canvas bounds, regardless of the consumer's overflow setting.
        """
        radius = self._resolver.border_radius()
        id_ = "clip-" + self._hash_seed()

        rx = Number.format((radius / 100) * canvas.width())
        ry = Number.format((radius / 100) * canvas.height())
        width = Number.format(canvas.width())
        height = Number.format(canvas.height())

        self._defs[id_] = (
            f'<clipPath id="{id_}"><rect width="{width}" height="{height}" '
            f'rx="{rx}" ry="{ry}"/></clipPath>'
        )

        return f'<g clip-path="url(#{id_})">{body}</g>'

    def _apply_rotate(self, body: str, canvas: Canvas) -> str:
        """Wrap ``body`` in a rotation around center when ``rotate`` is non-zero."""
        rotate = self._resolver.rotate()

        if rotate == 0:
            return body

        cx = Number.format(canvas.width() / 2)
        cy = Number.format(canvas.height() / 2)
        rotate_value = Number.format(rotate)

        return f'<g transform="rotate({rotate_value}, {cx}, {cy})">{body}</g>'

    def _apply_translate(self, body: str, canvas: Canvas) -> str:
        """Wrap ``body`` in a translate when translateX/translateY is non-zero.

        Offsets are interpreted as percentages of the canvas dimensions.
        """
        tx = self._resolver.translate_x()
        ty = self._resolver.translate_y()

        if tx == 0 and ty == 0:
            return body

        x = Number.format((tx / 100) * canvas.width())
        y = Number.format((ty / 100) * canvas.height())

        return f'<g transform="translate({x}, {y})">{body}</g>'

    def _render_background(self, canvas: Canvas) -> str:
        """Return a ``<rect>`` with the resolved background color, or ``''``."""
        colors = self._resolver.color("background")

        if len(colors) == 0:
            return ""

        fill = Xml.escape(self._resolve_color_reference("background"))
        width = Number.format(canvas.width())
        height = Number.format(canvas.height())

        return f'<rect width="{width}" height="{height}" fill="{fill}"/>'

    def _random_suffix(self) -> str:
        """Return the hex string that separates this render from every other
        one under ``idRandomization``, drawn once and cached.

        Uses ``random`` intentionally — a PRNG-derived value would repeat for
        the same seed.
        """
        if self._cached_random_suffix is None:
            # randrange yields 0..0xFFFFFE, matching the exclusive upper bound
            # of the JS reference's floor(random() * 0xffffff).
            self._cached_random_suffix = format(random.randrange(0xFFFFFF), "06x")

        return self._cached_random_suffix

    def _randomize_ids(self, svg: str) -> str:
        """Suffix every ``id`` declaration and reference with the render's
        random suffix.

        The animation class and keyframe names carry the same suffix through
        :meth:`_animation_hash`.
        """
        suffix = self._random_suffix()

        ids = list(dict.fromkeys(_ID_PATTERN.findall(svg)))

        if len(ids) == 0:
            return svg

        escaped = [re.escape(i) for i in ids]
        pattern = re.compile(r'(id="|url\(#|href="#)(' + "|".join(escaped) + r')("|\))')

        return pattern.sub(
            lambda m: m.group(1) + m.group(2) + "-" + suffix + m.group(3), svg
        )

    def _render_elements(self, elements: list[Element]) -> str:
        """Render a list of elements and concatenate their markup."""
        return "".join(self._render_element(el) for el in elements)

    def _render_element(self, element: Element) -> str:
        """Dispatch a single element to the renderer for its type."""
        element_type = element.type()

        if element_type == "element":
            return self._render_svg_element(element)

        if element_type == "text":
            return self._render_text_element(element)

        if element_type == "component":
            return self._render_component_element(element)

        return ""

    def _render_svg_element(self, element: Element) -> str:
        """Render an SVG element; the special ``defs`` name diverts children.

        Element and attribute names are not escaped here — they are validated by
        StyleValidator against a strict allowlist schema. Values are escaped via
        :meth:`Xml.escape`.
        """
        name = element.name()

        if name is None:
            return ""

        if name == "defs":
            for child in element.children():
                rendered = self._render_element(child)

                if len(rendered) > 0:
                    attrs = child.attributes()
                    child_id = attrs.get("id") if attrs is not None else None
                    key = (
                        child_id
                        if isinstance(child_id, str)
                        else "_" + str(len(self._defs))
                    )
                    self._defs[key] = rendered

            return ""

        attrs_str = self._render_attributes(
            self._attributes_without_animated_opacity(element.attributes(), element)
        )
        children = self._render_elements(element.children())

        if len(children) == 0:
            # A wrapper whose children all rendered to nothing, because an
            # optional component came up empty, has no content left to group.
            # It draws nothing either way, but a masked group without content
            # has an empty bounding box, and strict SVG parsers reject the
            # whole document over it. Wrappers that carry an id stay, so
            # references keep resolving.
            own_attributes = element.attributes()

            if len(element.children()) > 0 and (
                own_attributes is None or "id" not in own_attributes
            ):
                return ""

            return self._apply_animations(f"<{name}{attrs_str}/>", element)

        return self._apply_animations(
            f"<{name}{attrs_str}>{children}</{name}>", element
        )

    def _render_text_element(self, element: Element) -> str:
        """Render a text element by escaping its resolved value."""
        value = element.value()

        return Xml.escape(self._resolve_value(value)) if value is not None else ""

    def _render_component_element(self, element: Element) -> str:
        """Resolve a component reference to a variant and emit a ``<use>``.

        Aliases of the same source component sharing a variant — and identical
        components referenced more than once — produce a single ``<defs>`` entry
        referenced by every ``<use>``. A user-supplied ``transform`` is prepended
        to the per-component transforms.
        """
        component_name = element.name()

        if not isinstance(component_name, str):
            return ""

        variant_name = self._resolver.variant(component_name)

        if variant_name is None:
            return ""

        component = self._style.components().get(component_name)

        if component is None:
            return ""

        variant = component.variants().get(variant_name)

        if variant is None:
            return ""

        id_ = f"{component.source_name()}-{variant_name}-{self._hash_seed()}"

        if id_ not in self._defs:
            body = self._render_elements(variant.elements())
            self._defs[id_] = f'<g id="{id_}">{body}</g>'

        transforms = self._build_transforms(component)
        user_attributes = self._attributes_without_animated_opacity(
            element.attributes(), element
        )
        merged_attributes: dict[str, Any] | None = user_attributes

        if len(transforms) > 0:
            user_transform = (
                user_attributes.get("transform") if user_attributes else None
            )
            if isinstance(user_transform, str) and user_transform != "":
                all_parts = [user_transform, *transforms]
            else:
                all_parts = transforms

            merged_attributes = {
                **(user_attributes or {}),
                "transform": " ".join(all_parts),
            }

        attrs_str = self._render_attributes(merged_attributes)

        return self._apply_animations(f'<use{attrs_str} href="#{id_}"/>', element)

    def _build_transforms(self, component: Component) -> list[str]:
        """Return the per-component SVG ``transform`` fragments.

        Ordered so that, joined into one ``transform`` attribute, the scale is
        the rightmost (innermost) transform — applied first, then rotate, then
        translate.
        """
        t = self._resolver.component_transform(component.name())
        rotate = t["rotate"]
        translate_x = t["translateX"]
        translate_y = t["translateY"]
        scale = t["scale"]

        if translate_x == 0 and translate_y == 0 and rotate == 0 and scale == 1:
            return []

        transforms: list[str] = []
        cx = component.width() / 2
        cy = component.height() / 2
        cx_value = Number.format(cx)
        cy_value = Number.format(cy)

        if translate_x != 0 or translate_y != 0:
            x = Number.format((translate_x / 100) * component.width())
            y = Number.format((translate_y / 100) * component.height())
            transforms.append(f"translate({x}, {y})")

        if rotate != 0:
            rotate_value = Number.format(rotate)
            transforms.append(f"rotate({rotate_value}, {cx_value}, {cy_value})")

        if scale != 1:
            scale_value = Number.format(scale)
            neg_cx = Number.format(-cx)
            neg_cy = Number.format(-cy)
            transforms.append(
                f"translate({cx_value}, {cy_value}) scale({scale_value}) "
                f"translate({neg_cx}, {neg_cy})"
            )

        return transforms

    def _render_attributes(self, attributes: dict[str, Any] | None) -> str:
        """Serialize an attribute map to a leading space-prefixed string."""
        if attributes is None:
            return ""

        parts: list[str] = []

        for key, value in attributes.items():
            if value is None:
                continue

            parts.append(
                f'{key}="' + Xml.escape(self._resolve_attribute_value(value)) + '"'
            )

        if len(parts) == 0:
            return ""

        return " " + " ".join(parts)

    def _resolve_attribute_value(self, value: str | dict[str, Any]) -> str:
        """Resolve a single attribute value: literals pass through; references
        are dereferenced through the option resolver.
        """
        if isinstance(value, str):
            return value

        if value.get("type") == "color":
            return self._resolve_color_reference(value["name"])

        return self._resolve_variable(value["name"])

    def _resolve_color_reference(self, name: str) -> str:
        """Resolve a named color into a hex string or a ``url(#…)`` gradient."""
        colors = self._resolver.color(name)
        fill = self._resolver.color_fill(name)

        if fill == "solid" or len(colors) <= 1:
            return colors[0] if len(colors) > 0 else "none"

        return self._build_gradient_def(name, colors, fill)

    def _build_gradient_def(self, name: str, colors: list[str], fill: str) -> str:
        """Build the linear/radial gradient, register it, return its reference."""
        rotation = self._resolver.color_angle(name)
        id_ = f"{name}-color-{self._hash_seed()}"
        tag = "linearGradient" if fill == "linear" else "radialGradient"
        rotate_attr = (
            f' gradientTransform="rotate({Number.format(rotation)}, 0.5, 0.5)"'
            if rotation != 0
            else ""
        )

        stops: list[str] = []
        count = len(colors)

        for i, color in enumerate(colors):
            offset = Number.format(i / (count - 1) * 100)
            stops.append(
                f'<stop offset="{offset}%" stop-color="' + Xml.escape(color) + '"/>'
            )

        self._defs[id_] = (
            f'<{tag} id="{id_}"{rotate_attr}>' + "".join(stops) + f"</{tag}>"
        )

        return f"url(#{id_})"

    def _resolve_value(self, value: str | dict[str, Any]) -> str:
        """Resolve an element value: literals pass through; variables resolved."""
        if isinstance(value, str):
            return value

        if value.get("type") == "variable":
            return self._resolve_variable(value["name"])

        return ""

    def _resolve_variable(self, name: str) -> str:
        """Resolve a built-in variable reference to its current value."""
        if name == "initial":
            return self._initials()[0:1]

        if name == "initials":
            return self._initials()

        if name == "fontWeight":
            return Number.format(self._resolver.font_weight())

        if name == "fontFamily":
            return self._resolver.font_family()

        return ""

    def _initials(self) -> str:
        """Return the seed-derived initials, cached after the first call."""
        if self._cached_initials is None:
            self._cached_initials = Initials.from_seed(self._resolver.seed())

        return self._cached_initials

    def _hash_seed(self) -> str:
        """Return the FNV-1a hex hash of the style source name and the seed.

        Cached after the first call. The style name is part of the hash
        because styles share component and variant names: two avatars of
        different styles with the same seed would otherwise produce identical
        ids and steal each other's ``<defs>`` when inlined on one page.
        """
        if self._cached_seed_hash is None:
            source_name = self._style.meta().source().name() or ""
            self._cached_seed_hash = Fnv1a.hex(
                source_name + ":" + self._resolver.seed()
            )

        return self._cached_seed_hash

    def _animation_hash(self) -> str:
        """Return the FNV-1a hex hash namespacing the animation class and
        keyframe names, cached after the first call.

        Extends the :meth:`_hash_seed` input with the animation speed and, for
        a by-name selection, the sorted names: two renders of the same avatar
        with different speeds or selections inlined on one page must not
        select each other's rules, while identical renders sharing identical
        rules is harmless deduplication. ``True`` adds no name suffix, so
        enabling all animations hashes as before.

        Everything else about an avatar stays out of the hash, so two renders
        of the same style and seed that differ in any other option would share
        their names with different rule bodies. ``idRandomization`` is the way
        out of that collision, and it reaches the animation names through this
        input rather than through the id rewrite, which only knows
        ``id``/``url(#…)``/``href``.
        """
        if self._cached_animation_hash is None:
            selection = self._resolver.animation()
            names = (
                ":" + ",".join(sorted(set(selection)))
                if isinstance(selection, list)
                else ""
            )
            random_suffix = (
                ":" + self._random_suffix() if self._resolver.id_randomization() else ""
            )
            source_name = self._style.meta().source().name() or ""
            self._cached_animation_hash = Fnv1a.hex(
                source_name
                + ":"
                + self._resolver.seed()
                + ":"
                + Number.format(self._resolver.animation_speed())
                + names
                + random_suffix
            )

        return self._cached_animation_hash

    def _active_animations(self, element: Element) -> list[dict[str, Any]]:
        """Return the animation blocks of an element that the ``animation``
        option selects.

        The element check comes first: only styles that carry declarative
        animations may touch the option, so the resolved-options snapshot of
        every other avatar stays free of it.
        """
        animations = element.animations()

        if len(animations) == 0:
            return animations

        selection = self._resolver.animation()

        # ``True`` plays every timeline. A name list plays only the timelines
        # carrying one of those names, so unnamed timelines stay static then.
        if selection is True:
            return animations

        if selection is False:
            return []

        return [
            animation
            for animation in animations
            if (name := animation.get("name")) is not None and name in selection
        ]

    def _attributes_without_animated_opacity(
        self, attributes: dict[str, Any] | None, element: Element
    ) -> dict[str, Any] | None:
        """Strip the ``opacity`` attribute an animated opacity track takes over.

        A track writes the opacity the author means, not a factor on top of the
        element's own value: an element hidden with ``opacity="0"`` is a resting
        state the animation replaces, the way a CSS animation on the element
        itself would. The attribute therefore moves to the animating wrapper,
        where the keyframes override it. With the animation off no wrapper
        exists and the attribute stays where it is.
        """
        # The element check comes first: only styles that carry declarative
        # animations may touch the `animation` option, so the resolved-options
        # snapshot of every other avatar stays free of it.
        if (
            attributes is None
            or attributes.get("opacity") is None
            or len(element.animations()) == 0
        ):
            return attributes

        if not any(
            animation["tracks"].get("opacity") is not None
            for animation in self._active_animations(element)
        ):
            return attributes

        return {key: value for key, value in attributes.items() if key != "opacity"}

    def _apply_animations(self, markup: str, element: Element) -> str:
        """Wrap an element's rendered markup in one ``<g class="…">`` per
        animation track and queue the matching CSS.

        A no-op when the ``animation`` option is off, the element carries no
        animations, or its markup rendered to nothing (the empty-wrapper
        pruning then also prunes the animation).

        Wrapper nesting is block 0 outermost, and within a block the canonical
        track order (translate before rotate before scale, opacity innermost) —
        the composition contract the Figma plugin maps onto node transforms.

        The element's own ``opacity`` rides on the innermost opacity wrapper as
        the resting value the keyframes then override.
        """
        if len(markup) == 0:
            return markup

        active = self._active_animations(element)

        if len(active) == 0:
            return markup

        classes: list[str] = []
        opacity_wrapper = -1

        for animation in active:
            tracks = animation["tracks"]

            for track in _TRACK_ORDER:
                track_data = tracks.get(track)

                if track_data is not None:
                    if track == "opacity":
                        opacity_wrapper = len(classes)

                    classes.append(
                        self._build_animation_css(
                            animation, track, track_data["keyframes"]
                        )
                    )

        own_attributes = element.attributes()
        resting_opacity = (
            own_attributes.get("opacity") if own_attributes is not None else None
        )
        result = markup

        for index in range(len(classes) - 1, -1, -1):
            opacity = (
                self._render_attributes({"opacity": resting_opacity})
                if index == opacity_wrapper and resting_opacity is not None
                else ""
            )

            result = f'<g class="{classes[index]}"{opacity}>{result}</g>'

        return result

    def _build_animation_css(
        self, animation: dict[str, Any], track: str, keyframes: list[dict[str, Any]]
    ) -> str:
        """Generate the ``@keyframes`` block (deduplicated by content, so
        identical tracks on many elements share one block) and the class rule
        for a single track, and return the class name.
        """
        default_easing = animation.get("easing", "linear")
        body = self._keyframes_body(track, keyframes, default_easing)
        keyframes_name = self._keyframes_by_content.get(body)

        if keyframes_name is None:
            keyframes_name = f"dbk-{self._animation_hash()}-{self._keyframes_counter}"
            self._keyframes_counter += 1

            self._keyframes_by_content[body] = keyframes_name
            self._keyframes_css.append(
                "@keyframes " + keyframes_name + "{" + body + "}"
            )

        speed = self._resolver.animation_speed()
        duration = Number.format(animation["duration"] / speed)
        delay = Number.format(animation.get("delay", 0) / speed)
        raw_iterations = animation.get("iterations")
        iterations = (
            "infinite"
            if raw_iterations is None or raw_iterations == "infinite"
            else Number.format(raw_iterations)
        )
        direction = _DIRECTION_CSS[animation.get("direction", "normal")]
        fill = animation.get("fill", "none")

        # Only rotate and scale pivot around a point. Translation and opacity
        # need no origin, so their rules skip the transform-box prefix.
        origin_css = ""

        if track in ("rotate", "scaleX", "scaleY"):
            origin = animation.get("origin", {"x": 50, "y": 50})
            origin_x = Number.format(origin["x"])
            origin_y = Number.format(origin["y"])
            origin_css = (
                f"transform-box:fill-box;transform-origin:{origin_x}% {origin_y}%;"
            )

        class_name = f"dba-{self._animation_hash()}-{self._animation_class_counter}"
        self._animation_class_counter += 1

        # The name comes last in the shorthand so it can never be mistaken for
        # a keyword. All seven tokens are always emitted so every port
        # serializes the same string.
        self._animation_css.append(
            f".{class_name}{{{origin_css}animation:{duration}s "
            f"{self._easing_css(default_easing)} {delay}s {iterations} "
            f"{direction} {fill} {keyframes_name}}}"
        )

        return class_name

    def _keyframes_body(
        self,
        track: str,
        keyframes: list[dict[str, Any]],
        default_easing: str | dict[str, Any],
    ) -> str:
        """Serialize a track's keyframes to a ``@keyframes`` body.

        Endpoints are padded with copies of the nearest keyframe so the resting
        value holds outside the keyframed span, matching Figma's hold
        semantics. A keyframe's easing shapes the segment to the next keyframe
        and is emitted only when it differs from the block default (the rule's
        timing function covers the rest). The last keyframe has no following
        segment, so its easing is never emitted.
        """
        kf_list: list[dict[str, Any]] = list(keyframes)

        if kf_list[0]["at"] > 0:
            kf_list.insert(0, {"at": 0, "value": kf_list[0]["value"]})

        last = kf_list[-1]

        if last["at"] < 100:
            kf_list.append({"at": 100, "value": last["value"]})

        default_css = self._easing_css(default_easing)
        steps: list[str] = []

        for index, keyframe in enumerate(kf_list):
            easing = keyframe.get("easing")
            easing_css = (
                self._easing_css(easing)
                if easing is not None and index < len(kf_list) - 1
                else default_css
            )
            timing = (
                ";animation-timing-function:" + easing_css
                if easing_css != default_css
                else ""
            )
            declaration = self._track_declaration(track, keyframe["value"])

            steps.append(
                Number.format(keyframe["at"]) + "%{" + declaration + timing + "}"
            )

        return "".join(steps)

    def _track_declaration(self, track: str, value: float) -> str:
        """Return the CSS declaration animating one track at one keyframe value."""
        v = Number.format(value)

        if track == "translateX":
            return f"transform:translateX({v}px)"

        if track == "translateY":
            return f"transform:translateY({v}px)"

        if track == "rotate":
            return f"transform:rotate({v}deg)"

        if track == "scaleX":
            return f"transform:scaleX({v})"

        if track == "scaleY":
            return f"transform:scaleY({v})"

        return f"opacity:{v}"

    def _easing_css(self, easing: str | dict[str, Any]) -> str:
        """Serialize an easing to its CSS form. ``hold`` renders as ``step-end``."""
        if isinstance(easing, str):
            return _EASING_KEYWORD_CSS[easing]

        x1 = Number.format(easing["x1"])
        y1 = Number.format(easing["y1"])
        x2 = Number.format(easing["x2"])
        y2 = Number.format(easing["y2"])

        return f"cubic-bezier({x1}, {y1}, {x2}, {y2})"

    def _register_animation_style(self) -> None:
        """Register the accumulated animation CSS as a single ``<style>`` entry
        in the shared ``<defs>`` block, wrapped in a reduced-motion media query
        so users who prefer reduced motion get the static avatar.

        A no-op when no animation CSS was produced.
        """
        if len(self._keyframes_css) == 0:
            return

        # An authored def may carry the id "animation-style", so the CSS
        # takes the next free key rather than replacing that def.
        key = "animation-style"

        while key in self._defs:
            key += "-"

        self._defs[key] = (
            "<style>@media (prefers-reduced-motion:no-preference){"
            + "".join(self._keyframes_css)
            + "".join(self._animation_css)
            + "}</style>"
        )
