/**
 * Validates avatar options against the shared `options.json` schema.
 *
 * The runtime implementation lives in `OptionsValidator.js`, generated by
 * `scripts/compile-schema.mjs` from `@dicebear/schema` via @exodus/schemasafe.
 */
export class OptionsValidator {
  /**
   * Validates the given data and throws `OptionsValidationError` on failure.
   */
  static validate(data: unknown): void;
}
