/**
 * Validates style definitions against the shared `definition.json` schema.
 *
 * The runtime implementation lives in `StyleValidator.js`, generated by
 * `scripts/compile-schema.mjs` from `@dicebear/schema` via @exodus/schemasafe.
 */
export class StyleValidator {
  /**
   * Validates the given data and throws `StyleValidationError` on failure.
   */
  static validate(data: unknown): void;
}
