// Appends schemasafe's license notice to the LICENSE file. The generated
// validators contain code produced by the @exodus/schemasafe compiler, which
// is MIT licensed. This script is intended to run as a prepack hook so the
// extended LICENSE is only present in the published npm package, not in the
// source repository.

import { createRequire } from 'module';
import { readFileSync, writeFileSync } from 'fs';

const require = createRequire(import.meta.url);

const license = readFileSync('./LICENSE', 'utf-8');

if (!license.includes('code generated by @exodus/schemasafe')) {
  const schemasafeLicense = readFileSync(
    require.resolve('@exodus/schemasafe/LICENSE'),
    'utf-8',
  );

  writeFileSync(
    './LICENSE',
    `${license.trimEnd()}

---

This software includes code generated by @exodus/schemasafe
(https://github.com/ExodusMovement/schemasafe):

${schemasafeLicense.trimEnd()}
`,
  );
}
