/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Options {
  colors?: (
    | "amber"
    | "blue"
    | "blueGrey"
    | "brown"
    | "cyan"
    | "deepOrange"
    | "deepPurple"
    | "green"
    | "grey"
    | "indigo"
    | "lightBlue"
    | "lightGreen"
    | "lime"
    | "orange"
    | "pink"
    | "purple"
    | "red"
    | "teal"
    | "yellow"
  )[];
  colorLevel?: 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;
}
