<?php

declare(strict_types=1);

namespace DiceBear;

use DiceBear\Prng\Fnv1a;
use DiceBear\Style\Canvas;
use DiceBear\Style\Element;
use DiceBear\Utils\Initials;
use DiceBear\Utils\License;
use DiceBear\Utils\Number;
use DiceBear\Utils\Xml;

/**
 * Walks a style's element tree and turns it into the final SVG markup.
 *
 * The renderer is single-use: it accumulates `<defs>` entries and per-render
 * caches across method calls, so a fresh instance is required per avatar.
 *
 * @internal
 */
class Renderer
{
    /**
     * The canonical track order, outermost wrapper to innermost. It mirrors
     * the usual translate → rotate → scale transform composition. Every port
     * must wrap in this exact order for the outputs to stay byte-identical.
     */
    private const TRACK_ORDER = [
        'translateX',
        'translateY',
        'rotate',
        'scaleX',
        'scaleY',
        'opacity',
    ];

    private const DIRECTION_CSS = [
        'normal' => 'normal',
        'reverse' => 'reverse',
        'alternate' => 'alternate',
        'alternateReverse' => 'alternate-reverse',
    ];

    private const EASING_KEYWORD_CSS = [
        'linear' => 'linear',
        'ease' => 'ease',
        'easeIn' => 'ease-in',
        'easeOut' => 'ease-out',
        'easeInOut' => 'ease-in-out',
        'hold' => 'step-end',
    ];

    private Style $style;
    private Resolver $resolver;
    /** @var array<string, string> */
    private array $defs = [];
    private ?string $cachedSeedHash = null;
    private ?string $cachedInitials = null;
    private ?string $cachedAnimationHash = null;
    private ?string $cachedRandomSuffix = null;
    /** @var list<string> */
    private array $keyframesCss = [];
    /** @var list<string> */
    private array $animationCss = [];
    /** @var array<string, string> */
    private array $keyframesByContent = [];
    private int $keyframesCounter = 0;
    private int $animationClassCounter = 0;

    public function __construct(Style $style, Resolver $resolver)
    {
        $this->style = $style;
        $this->resolver = $resolver;
    }

    /**
     * Builds the complete SVG document for the avatar.
     */
    public function render(): string
    {
        $canvas = $this->style->canvas();
        $background = $this->renderBackground($canvas);
        $body = $this->renderElements($canvas->elements());

        // Order matters: scale and flip around center, then rotate, translate,
        // and finally clip with border radius (outermost wrapper).
        $body = $this->applyScale($body, $canvas);
        $body = $this->applyFlip($body, $canvas);
        $body = $this->applyRotate($body, $canvas);
        $body = $this->applyTranslate($body, $canvas);
        $body = $this->applyBorderRadius($background . $body, $canvas);

        $this->registerAnimationStyle();

        $metadata = License::xml($this->style->meta());
        $defs = count($this->defs) > 0
            ? '<defs>' . implode('', array_values($this->defs)) . '</defs>'
            : '';
        $size = $this->resolver->size();

        $title = $this->resolver->title();
        $escapedTitle = $title !== null ? Xml::escape($title) : null;

        $width = Number::format($canvas->width());
        $height = Number::format($canvas->height());
        $attrs = [
            'xmlns="http://www.w3.org/2000/svg"',
            "viewBox=\"0 0 {$width} {$height}\"",
        ];

        $rootAttributes = $this->renderAttributes($this->style->attributes());

        if ($rootAttributes !== '') {
            $attrs[] = ltrim($rootAttributes);
        }

        if ($escapedTitle !== null) {
            $attrs[] = 'role="img"';
            $attrs[] = "aria-label=\"{$escapedTitle}\"";
        } else {
            $attrs[] = 'aria-hidden="true"';
        }

        if ($size !== null) {
            $sizeValue = Number::format($size);
            $attrs[] = "width=\"{$sizeValue}\"";
            $attrs[] = "height=\"{$sizeValue}\"";
        }

        $titleElement = $escapedTitle !== null ? "<title>{$escapedTitle}</title>" : '';

        $svg = '<svg ' . implode(' ', $attrs) . '>' . '<!-- Generated by DiceBear (https://www.dicebear.com) -->' . $metadata . $defs . $titleElement . $body . '</svg>';

        if ($this->resolver->idRandomization()) {
            $svg = $this->randomizeIds($svg);
        }

        return $svg;
    }

    /**
     * Wraps `$body` in a flip transform when `flip` is set to anything other
     * than `'none'`.
     */
    private function applyFlip(string $body, Canvas $canvas): string
    {
        $flip = $this->resolver->flip();

        if ($flip === 'none') {
            return $body;
        }

        $w = Number::format($canvas->width());
        $h = Number::format($canvas->height());

        // @phpstan-ignore match.unhandled
        $transform = match ($flip) {
            'horizontal' => "translate({$w}, 0) scale(-1, 1)",
            'vertical' => "translate(0, {$h}) scale(1, -1)",
            'both' => "translate({$w}, {$h}) scale(-1, -1)",
        };

        return "<g transform=\"{$transform}\">{$body}</g>";
    }

    /**
     * Wraps `$body` in a uniform scale transform around the canvas center
     * when the option differs from `1`.
     */
    private function applyScale(string $body, Canvas $canvas): string
    {
        $scale = $this->resolver->scale();

        if ($scale === 1.0) {
            return $body;
        }

        $cx = $canvas->width() / 2;
        $cy = $canvas->height() / 2;
        $cxValue = Number::format($cx);
        $cyValue = Number::format($cy);
        $scaleValue = Number::format($scale);
        $negCx = Number::format(-$cx);
        $negCy = Number::format(-$cy);

        return "<g transform=\"translate({$cxValue}, {$cyValue}) scale({$scaleValue}) translate({$negCx}, {$negCy})\">{$body}</g>";
    }

    /**
     * Clips `$body` to the canvas rectangle (rounded when `borderRadius` is
     * non-zero) and registers the corresponding `clipPath` in `<defs>`. The
     * clip is always applied so transformed content cannot bleed past the
     * canvas bounds, regardless of the consumer's `overflow` setting.
     */
    private function applyBorderRadius(string $body, Canvas $canvas): string
    {
        $radius = $this->resolver->borderRadius();
        $id = 'clip-' . $this->hashSeed();

        $rx = Number::format(($radius / 100) * $canvas->width());
        $ry = Number::format(($radius / 100) * $canvas->height());
        $width = Number::format($canvas->width());
        $height = Number::format($canvas->height());

        $this->defs[$id] = "<clipPath id=\"{$id}\"><rect width=\"{$width}\" height=\"{$height}\" rx=\"{$rx}\" ry=\"{$ry}\"/></clipPath>";

        return "<g clip-path=\"url(#{$id})\">{$body}</g>";
    }

    /**
     * Wraps `$body` in a rotation around the canvas center when `rotate` is
     * non-zero.
     */
    private function applyRotate(string $body, Canvas $canvas): string
    {
        $rotate = $this->resolver->rotate();

        if ($rotate === 0.0) {
            return $body;
        }

        $cx = Number::format($canvas->width() / 2);
        $cy = Number::format($canvas->height() / 2);
        $rotateValue = Number::format($rotate);

        return "<g transform=\"rotate({$rotateValue}, {$cx}, {$cy})\">{$body}</g>";
    }

    /**
     * Wraps `$body` in a translate transform when either `translateX` or
     * `translateY` is non-zero. Offsets are interpreted as percentages of
     * the canvas dimensions.
     */
    private function applyTranslate(string $body, Canvas $canvas): string
    {
        $translateX = $this->resolver->translateX();
        $translateY = $this->resolver->translateY();

        if ($translateX === 0.0 && $translateY === 0.0) {
            return $body;
        }

        $x = Number::format(($translateX / 100) * $canvas->width());
        $y = Number::format(($translateY / 100) * $canvas->height());

        return "<g transform=\"translate({$x}, {$y})\">{$body}</g>";
    }

    /**
     * Returns a `<rect>` filling the canvas with the resolved background
     * color, or an empty string when no background colors are configured.
     */
    private function renderBackground(Canvas $canvas): string
    {
        $colors = $this->resolver->color('background');

        if (count($colors) === 0) {
            return '';
        }

        $fill = Xml::escape($this->resolveColorReference('background'));
        $width = Number::format($canvas->width());
        $height = Number::format($canvas->height());

        return "<rect width=\"{$width}\" height=\"{$height}\" fill=\"{$fill}\"/>";
    }

    /**
     * Returns the hex string that separates this render from every other one
     * under `idRandomization`, drawn once and cached. Uses `random_int()`
     * intentionally — a PRNG-derived value would repeat for the same seed.
     */
    private function randomSuffix(): string
    {
        // 0..0xfffffe, matching the exclusive upper bound of the JS
        // reference's floor(random() * 0xffffff).
        return $this->cachedRandomSuffix ??= str_pad(
            dechex(random_int(0, 0xfffffe)),
            6,
            '0',
            STR_PAD_LEFT
        );
    }

    /**
     * Suffixes every `id` declaration and reference with the render's random
     * suffix so that multiple instances of the same avatar do not collide in
     * a shared document. The animation class and keyframe names carry the
     * same suffix through {@see animationHash}.
     */
    private function randomizeIds(string $svg): string
    {
        $suffix = $this->randomSuffix();
        $ids = [];

        // The missing `u` modifier is deliberate. Without it PCRE reads `\b`
        // as an ASCII boundary, which is how JavaScript reads it, so the same
        // ids are collected here and in the reference. Under `/u` the boundary
        // turns Unicode aware, `Caféid="x"` stops matching, and the rendered
        // markup drifts away from the other implementations.
        if (preg_match_all('/\bid="([^"]+)"/', $svg, $matches)) {
            $ids = array_unique($matches[1]);
        }

        if (count($ids) === 0) {
            return $svg;
        }

        $escaped = array_map(fn($id) => preg_quote($id, '/'), $ids);
        $pattern = '/(id="|url\(#|href="#)(' . implode('|', $escaped) . ')("|\))/';

        return preg_replace_callback($pattern, function ($match) use ($suffix) {
            return $match[1] . $match[2] . '-' . $suffix . $match[3];
        }, $svg);
    }

    /**
     * Renders a list of elements and concatenates their markup.
     *
     * @param list<Element> $elements
     */
    private function renderElements(array $elements): string
    {
        return implode('', array_map(fn($el) => $this->renderElement($el), $elements));
    }

    /**
     * Dispatches a single element to the renderer for its type.
     */
    private function renderElement(Element $element): string
    {
        // @phpstan-ignore match.unhandled
        return match ($element->type()) {
            'element' => $this->renderSvgElement($element),
            'text' => $this->renderTextElement($element),
            'component' => $this->renderComponentElement($element),
        };
    }

    /**
     * Renders an SVG element. The special `defs` name diverts children into
     * the shared `<defs>` block.
     *
     * Element names and attribute names are not escaped here — they are
     * validated by StyleValidator against a strict allowlist schema (no
     * `<script>`, no event handlers). Values are escaped via `Xml::escape()`.
     */
    private function renderSvgElement(Element $element): string
    {
        $name = $element->name();

        if ($name === null) {
            return '';
        }

        if ($name === 'defs') {
            foreach ($element->children() as $child) {
                $rendered = $this->renderElement($child);

                if (strlen($rendered) > 0) {
                    $attrs = $child->attributes();
                    $id = isset($attrs['id']) && is_string($attrs['id']) ? $attrs['id'] : '_' . count($this->defs);
                    $this->defs[$id] = $rendered;
                }
            }

            return '';
        }

        $attrs = $this->renderAttributes(
            $this->attributesWithoutAnimatedOpacity($element->attributes(), $element),
        );
        $children = $this->renderElements($element->children());

        if (strlen($children) === 0) {
            // A wrapper whose children all rendered to nothing, because an
            // optional component came up empty, has no content left to group.
            // It draws nothing either way, but a masked group without content
            // has an empty bounding box, and strict SVG parsers reject the
            // whole document over it. Wrappers that carry an id stay, so
            // references keep resolving.
            $ownAttributes = $element->attributes();

            if (count($element->children()) > 0 && !isset($ownAttributes['id'])) {
                return '';
            }

            return $this->applyAnimations("<{$name}{$attrs}/>", $element);
        }

        return $this->applyAnimations("<{$name}{$attrs}>{$children}</{$name}>", $element);
    }

    /**
     * Renders a text element by escaping its resolved value.
     */
    private function renderTextElement(Element $element): string
    {
        $value = $element->value();

        return $value !== null ? Xml::escape($this->resolveValue($value)) : '';
    }

    /**
     * Resolves a component reference to a chosen variant and emits a `<use>`
     * pointing at a `<defs>` entry that holds the variant body. Aliases of the
     * same source component sharing a variant — and identical components
     * referenced more than once — therefore produce a single `<defs>` entry
     * referenced by every `<use>`, never duplicated SVG markup.
     *
     * Any `attributes` on the component reference are written to the emitted
     * `<use>` tag. A user-supplied `transform` is prepended to the
     * per-component transforms so it acts as the outer (placement) transform,
     * with the style's translate/rotate/scale applied inside it.
     */
    private function renderComponentElement(Element $element): string
    {
        $componentName = $element->name();

        if (!is_string($componentName)) {
            return '';
        }

        $variantName = $this->resolver->variant($componentName);

        if ($variantName === null) {
            return '';
        }

        $components = $this->style->components();
        $component = $components[$componentName] ?? null;

        if ($component === null) {
            return '';
        }

        $variants = $component->variants();
        $variant = $variants[$variantName] ?? null;

        if ($variant === null) {
            return '';
        }

        $id = "{$component->sourceName()}-{$variantName}-{$this->hashSeed()}";

        if (!array_key_exists($id, $this->defs)) {
            $body = $this->renderElements($variant->elements());

            $this->defs[$id] = "<g id=\"{$id}\">{$body}</g>";
        }

        $transforms = $this->buildTransforms($component);
        $userAttributes = $this->attributesWithoutAnimatedOpacity($element->attributes(), $element);
        $mergedAttributes = $userAttributes;

        if (count($transforms) > 0) {
            $userTransform = $userAttributes['transform'] ?? null;
            $allParts = is_string($userTransform) && $userTransform !== ''
                ? [$userTransform, ...$transforms]
                : $transforms;

            $mergedAttributes = $userAttributes ?? [];
            $mergedAttributes['transform'] = implode(' ', $allParts);
        }

        $attrs = $this->renderAttributes($mergedAttributes);

        return $this->applyAnimations("<use{$attrs} href=\"#{$id}\"/>", $element);
    }

    /**
     * Returns the per-component SVG `transform` fragments derived from the
     * component's translate, rotate, and scale options. Translate values are
     * percentages of the component canvas dimensions, matching the
     * semantics of the user-facing `translateX` / `translateY` options.
     *
     * The fragments are ordered so that, when joined into a single
     * `transform` attribute, the scale is the rightmost (innermost)
     * transform — applied first to a point, followed by rotate, then
     * translate.
     *
     * @return list<string>
     */
    private function buildTransforms(Style\Component $component): array
    {
        ['rotate' => $rotate, 'translateX' => $translateX, 'translateY' => $translateY, 'scale' => $scale] =
            $this->resolver->componentTransform($component->name());

        if ($translateX === 0.0 && $translateY === 0.0 && $rotate === 0.0 && $scale === 1.0) {
            return [];
        }

        $transforms = [];
        $cx = $component->width() / 2;
        $cy = $component->height() / 2;
        $cxValue = Number::format($cx);
        $cyValue = Number::format($cy);

        if ($translateX !== 0.0 || $translateY !== 0.0) {
            $x = Number::format(($translateX / 100) * $component->width());
            $y = Number::format(($translateY / 100) * $component->height());
            $transforms[] = "translate({$x}, {$y})";
        }

        if ($rotate !== 0.0) {
            $rotateValue = Number::format($rotate);
            $transforms[] = "rotate({$rotateValue}, {$cxValue}, {$cyValue})";
        }

        if ($scale !== 1.0) {
            $scaleValue = Number::format($scale);
            $negCx = Number::format(-$cx);
            $negCy = Number::format(-$cy);
            $transforms[] = "translate({$cxValue}, {$cyValue}) scale({$scaleValue}) translate({$negCx}, {$negCy})";
        }

        return $transforms;
    }

    /**
     * Serializes an attribute map to a leading space-prefixed string suitable
     * for inlining into a tag. Returns an empty string when there are no
     * attributes to render.
     *
     * @param array<string, mixed>|null $attributes
     */
    private function renderAttributes(?array $attributes): string
    {
        if ($attributes === null) {
            return '';
        }

        $parts = [];

        foreach ($attributes as $key => $value) {
            if ($value === null) {
                continue;
            }

            $parts[] = "{$key}=\"" . Xml::escape($this->resolveAttributeValue($value)) . '"';
        }

        if (count($parts) === 0) {
            return '';
        }

        return ' ' . implode(' ', $parts);
    }

    /**
     * Resolves a single attribute value: literal strings pass through, color
     * and variable references are dereferenced through the option resolver.
     *
     * @param string|array<string, mixed> $value
     */
    private function resolveAttributeValue(string|array $value): string
    {
        if (is_string($value)) {
            return $value;
        }

        if (($value['type'] ?? null) === 'color') {
            return $this->resolveColorReference($value['name']);
        }

        return $this->resolveVariable($value['name']);
    }

    /**
     * Resolves a named color into either a hex string (solid fill / single
     * color) or a `url(#…)` gradient reference, registering the gradient in
     * `<defs>` as a side effect.
     */
    private function resolveColorReference(string $name): string
    {
        $colors = $this->resolver->color($name);
        $fill = $this->resolver->colorFill($name);

        if ($fill === 'solid' || count($colors) <= 1) {
            return $colors[0] ?? 'none';
        }

        return $this->buildGradientDef($name, $colors, $fill);
    }

    /**
     * Builds the `<linearGradient>` or `<radialGradient>` for the given color
     * definition, registers it in `<defs>`, and returns its `url(#…)`
     * reference.
     *
     * @param list<string> $colors
     */
    private function buildGradientDef(string $name, array $colors, string $fill): string
    {
        $rotation = $this->resolver->colorAngle($name);
        $id = "{$name}-color-{$this->hashSeed()}";
        $tag = $fill === 'linear' ? 'linearGradient' : 'radialGradient';
        $rotationValue = Number::format($rotation);
        $rotateAttr = $rotation !== 0.0
            ? " gradientTransform=\"rotate({$rotationValue}, 0.5, 0.5)\""
            : '';

        $stops = [];
        $count = count($colors);

        foreach ($colors as $i => $color) {
            $offset = Number::format($i / ($count - 1) * 100);
            $stops[] = "<stop offset=\"{$offset}%\" stop-color=\"" . Xml::escape($color) . '"/>';
        }

        $this->defs[$id] = "<{$tag} id=\"{$id}\"{$rotateAttr}>" . implode('', $stops) . "</{$tag}>";

        return "url(#{$id})";
    }

    /**
     * Resolves an element value to its final string form. Literal strings
     * pass through; variable references are dereferenced.
     *
     * @param string|array<string, mixed> $value
     */
    private function resolveValue(string|array $value): string
    {
        if (is_string($value)) {
            return $value;
        }

        if (($value['type'] ?? null) === 'variable') {
            return $this->resolveVariable($value['name']);
        }

        return '';
    }

    /**
     * Resolves a built-in variable reference to its current value.
     */
    private function resolveVariable(string $name): string
    {
        // @phpstan-ignore match.unhandled
        return match ($name) {
            'initial' => mb_substr($this->initials(), 0, 1),
            'initials' => $this->initials(),
            'fontWeight' => Number::format($this->resolver->fontWeight()),
            'fontFamily' => $this->resolver->fontFamily(),
        };
    }

    /**
     * Returns the seed-derived initials, cached after the first call.
     */
    private function initials(): string
    {
        return $this->cachedInitials ??= Initials::fromSeed($this->resolver->seed());
    }

    /**
     * Returns the FNV-1a hex hash of the style source name and the seed,
     * cached after the first call. The value is used to derive stable but
     * unique IDs for `<defs>` entries. The style name is part of the hash
     * because styles share component and variant names: two avatars of
     * different styles with the same seed would otherwise produce identical
     * IDs and steal each other's `<defs>` when inlined on one page.
     */
    private function hashSeed(): string
    {
        return $this->cachedSeedHash ??= Fnv1a::hex(
            ($this->style->meta()->source()->name() ?? '') . ':' . $this->resolver->seed()
        );
    }

    /**
     * Returns the FNV-1a hex hash namespacing the animation class and
     * keyframe names, cached after the first call. Extends the
     * {@see hashSeed} input with the animation speed and the state of every
     * named timeline: two renders of the same avatar with
     * different speeds or selections inlined on one page must not select each
     * other's rules, while identical renders sharing identical rules is
     * harmless deduplication. `true` adds no name suffix, so enabling all
     * animations hashes as before.
     *
     * Everything else about an avatar stays out of the hash, so two renders
     * of the same style and seed that differ in any other option would share
     * their names with different rule bodies. `idRandomization` is the way
     * out of that collision, and it reaches the animation names through this
     * input rather than through the id rewrite, which only knows
     * `id`/`url(#…)`/`href`.
     */
    private function animationHash(): string
    {
        if ($this->cachedAnimationHash !== null) {
            return $this->cachedAnimationHash;
        }

        $random = $this->resolver->idRandomization() ? ':' . $this->randomSuffix() : '';

        // Every named timeline the style carries joins the hash with its
        // state, `off` or the factor and offset it plays at, so two renders
        // that differ only in a per-name animation option never share their
        // rules. The style lists its names in byte order already.
        $states = [];

        foreach ($this->style->animationNames() as $name) {
            $states[] = $this->resolver->animationPlays($name)
                ? $name
                    . ':' . Number::format($this->resolver->animationSpeedFor($name))
                    . ':' . Number::format($this->resolver->animationDelayFor($name))
                : $name . ':off';
        }

        $named = count($states) > 0 ? ':' . implode(',', $states) : '';

        return $this->cachedAnimationHash = Fnv1a::hex(
            ($this->style->meta()->source()->name() ?? '')
            . ':' . $this->resolver->seed()
            . ':' . Number::format($this->resolver->animationSpeed())
            . ':' . Number::format($this->resolver->animationDelay())
            . $named
            . $random
        );
    }

    /**
     * Returns the animation blocks of an element that play. The element check
     * comes first: only styles that carry declarative animations may touch
     * the options, so the resolved-options snapshot of every other avatar
     * stays free of them.
     *
     * @return list<array<string, mixed>>
     */
    private function activeAnimations(Element $element): array
    {
        $animations = $element->animations();

        if (count($animations) === 0) {
            return $animations;
        }

        // The global switch is read first so it lands in the resolved options
        // whenever a node carries animations, on or off. Named timelines then
        // follow their own switch when the user set one.
        $this->resolver->animation();

        return array_values(array_filter(
            $animations,
            fn(array $animation) => $this->resolver->animationPlays($animation['name'] ?? null),
        ));
    }

    /**
     * Strips the `opacity` attribute an animated opacity track takes over.
     *
     * A track writes the opacity the author means, not a factor on top of the
     * element's own value: an element hidden with `opacity="0"` is a resting
     * state the animation replaces, the way a CSS animation on the element
     * itself would. The attribute therefore moves to the animating wrapper,
     * where the keyframes override it. With the animation off no wrapper
     * exists and the attribute stays where it is.
     *
     * @param array<string, mixed>|null $attributes
     * @return array<string, mixed>|null
     */
    private function attributesWithoutAnimatedOpacity(?array $attributes, Element $element): ?array
    {
        // The element check comes first: only styles that carry declarative
        // animations may touch the `animation` option, so the resolved-options
        // snapshot of every other avatar stays free of it.
        if (!isset($attributes['opacity']) || count($element->animations()) === 0) {
            return $attributes;
        }

        foreach ($this->activeAnimations($element) as $animation) {
            if (isset($animation['tracks']['opacity'])) {
                unset($attributes['opacity']);

                return $attributes;
            }
        }

        return $attributes;
    }

    /**
     * Wraps an element's rendered markup in one `<g class="…">` per animation
     * track and queues the matching CSS. A no-op when the `animation` option
     * is off, the element carries no animations, or its markup rendered to
     * nothing (the empty-wrapper pruning then also prunes the animation).
     *
     * Wrapper nesting is block 0 outermost, and within a block the canonical
     * track order (translate before rotate before scale, opacity innermost) —
     * the composition contract the Figma plugin maps onto node transforms.
     *
     * The element's own `opacity` rides on the innermost opacity wrapper as
     * the resting value the keyframes then override.
     *
     */
    private function applyAnimations(string $markup, Element $element): string
    {
        if ($markup === '') {
            return $markup;
        }

        $active = $this->activeAnimations($element);

        if (count($active) === 0) {
            return $markup;
        }

        $classes = [];
        $opacityWrapper = -1;

        foreach ($active as $animation) {
            foreach (self::TRACK_ORDER as $track) {
                $trackData = $animation['tracks'][$track] ?? null;

                if ($trackData !== null) {
                    if ($track === 'opacity') {
                        $opacityWrapper = count($classes);
                    }

                    $classes[] = $this->buildAnimationCss($animation, $track, $trackData['keyframes']);
                }
            }
        }

        $ownAttributes = $element->attributes();
        $restingOpacity = $ownAttributes['opacity'] ?? null;
        $result = $markup;

        for ($i = count($classes) - 1; $i >= 0; $i--) {
            $opacity = $i === $opacityWrapper && $restingOpacity !== null
                ? $this->renderAttributes(['opacity' => $restingOpacity])
                : '';

            $result = "<g class=\"{$classes[$i]}\"{$opacity}>{$result}</g>";
        }

        return $result;
    }

    /**
     * Generates the `@keyframes` block (deduplicated by content, so identical
     * tracks on many elements share one block) and the class rule for a
     * single track, and returns the class name.
     *
     * @param array<string, mixed> $animation
     * @param list<array<string, mixed>> $keyframes
     */
    private function buildAnimationCss(array $animation, string $track, array $keyframes): string
    {
        $defaultEasing = $animation['easing'] ?? 'linear';
        $body = $this->keyframesBody($track, $keyframes, $defaultEasing);

        $keyframesName = $this->keyframesByContent[$body] ?? null;

        if ($keyframesName === null) {
            $keyframesName = 'dbk-' . $this->animationHash() . '-' . $this->keyframesCounter++;

            $this->keyframesByContent[$body] = $keyframesName;
            $this->keyframesCss[] = "@keyframes {$keyframesName}{" . $body . '}';
        }

        $speed = $this->resolver->animationSpeedFor($animation['name'] ?? null);
        $duration = Number::format($animation['duration'] / $speed);
        // The user's offset is in seconds of playback, so it is added after
        // the speed has scaled the authored delay.
        $delay = Number::format(
            ($animation['delay'] ?? 0) / $speed + $this->resolver->animationDelayFor($animation['name'] ?? null),
        );
        $iterations = !isset($animation['iterations']) || $animation['iterations'] === 'infinite'
            ? 'infinite'
            : Number::format($animation['iterations']);
        $direction = self::DIRECTION_CSS[$animation['direction'] ?? 'normal'];
        $fill = $animation['fill'] ?? 'none';

        // Only rotate and scale pivot around a point. Translation and opacity
        // need no origin, so their rules skip the transform-box prefix.
        $needsOrigin = $track === 'rotate' || $track === 'scaleX' || $track === 'scaleY';
        $originCss = '';

        if ($needsOrigin) {
            $origin = $animation['origin'] ?? ['x' => 50, 'y' => 50];
            $originX = Number::format($origin['x']);
            $originY = Number::format($origin['y']);
            $originCss = "transform-box:fill-box;transform-origin:{$originX}% {$originY}%;";
        }

        $className = 'dba-' . $this->animationHash() . '-' . $this->animationClassCounter++;
        $easing = $this->easingCss($defaultEasing);

        // The name comes last in the shorthand so it can never be mistaken
        // for a keyword. All seven tokens are always emitted so every port
        // serializes the same string.
        $this->animationCss[] = ".{$className}{"
            . "{$originCss}animation:{$duration}s {$easing} {$delay}s {$iterations} {$direction} {$fill} {$keyframesName}"
            . '}';

        return $className;
    }

    /**
     * Serializes a track's keyframes to a `@keyframes` body. Endpoints are
     * padded with copies of the nearest keyframe so the resting value holds
     * outside the keyframed span, matching Figma's hold semantics. A
     * keyframe's easing shapes the segment to the next keyframe and is
     * emitted only when it differs from the block default (the rule's timing
     * function covers the rest). The last keyframe has no following segment,
     * so its easing is never emitted.
     *
     * @param list<array<string, mixed>> $keyframes
     * @param string|array<string, int|float> $defaultEasing
     */
    private function keyframesBody(string $track, array $keyframes, string|array $defaultEasing): string
    {
        $list = $keyframes;

        if ($list[0]['at'] > 0) {
            array_unshift($list, ['at' => 0, 'value' => $list[0]['value']]);
        }

        $last = $list[count($list) - 1];

        if ($last['at'] < 100) {
            $list[] = ['at' => 100, 'value' => $last['value']];
        }

        $defaultCss = $this->easingCss($defaultEasing);
        $count = count($list);
        $steps = [];

        foreach ($list as $index => $keyframe) {
            $easingCss = isset($keyframe['easing']) && $index < $count - 1
                ? $this->easingCss($keyframe['easing'])
                : $defaultCss;
            $timing = $easingCss !== $defaultCss
                ? ";animation-timing-function:{$easingCss}"
                : '';
            $at = Number::format($keyframe['at']);

            $steps[] = "{$at}%{" . $this->trackDeclaration($track, $keyframe['value']) . $timing . '}';
        }

        return implode('', $steps);
    }

    /**
     * Returns the CSS declaration animating one track at one keyframe value.
     */
    private function trackDeclaration(string $track, int|float $value): string
    {
        $v = Number::format($value);

        // @phpstan-ignore match.unhandled
        return match ($track) {
            'translateX' => "transform:translateX({$v}px)",
            'translateY' => "transform:translateY({$v}px)",
            'rotate' => "transform:rotate({$v}deg)",
            'scaleX' => "transform:scaleX({$v})",
            'scaleY' => "transform:scaleY({$v})",
            'opacity' => "opacity:{$v}",
        };
    }

    /**
     * Serializes an easing to its CSS form. `hold` renders as `step-end`.
     *
     * @param string|array<string, int|float> $easing
     */
    private function easingCss(string|array $easing): string
    {
        if (is_string($easing)) {
            return self::EASING_KEYWORD_CSS[$easing];
        }

        $x1 = Number::format($easing['x1']);
        $y1 = Number::format($easing['y1']);
        $x2 = Number::format($easing['x2']);
        $y2 = Number::format($easing['y2']);

        return "cubic-bezier({$x1}, {$y1}, {$x2}, {$y2})";
    }

    /**
     * Registers the accumulated animation CSS as a single `<style>` entry in
     * the shared `<defs>` block, wrapped in a reduced-motion media query so
     * users who prefer reduced motion get the static avatar. A no-op when no
     * animation CSS was produced.
     */
    private function registerAnimationStyle(): void
    {
        if (count($this->keyframesCss) === 0) {
            return;
        }

        // An authored def may carry the id `animation-style`, so the CSS
        // takes the next free key rather than replacing that def.
        $key = 'animation-style';

        while (array_key_exists($key, $this->defs)) {
            $key .= '-';
        }

        $this->defs[$key] = '<style>@media (prefers-reduced-motion:no-preference){'
            . implode('', $this->keyframesCss)
            . implode('', $this->animationCss)
            . '}</style>';
    }
}
