/**
 * Do not change this file manually! This file was generated with the "Dicebear Exporter"-Plugin for Figma.
 *
 * Plugin: https://www.figma.com/community/plugin/1005765655729342787
 * File: https://www.figma.com/file/gpLBQuklPE2XsOskwwv7QW
 */

import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    base: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['variant01'],
      },
      default: ['variant01'],
    },
    beard: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
    beardProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    body: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
    bodyIcon: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['electric', 'saturn', 'galaxy'],
      },
      default: ['electric', 'saturn', 'galaxy'],
    },
    bodyIconProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 75,
    },
    brows: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
    eyes: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['variant05', 'variant04', 'variant03', 'variant02', 'variant01'],
      },
      default: [
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
    gesture: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'wavePointLongArms',
          'waveOkLongArms',
          'waveLongArms',
          'waveLongArm',
          'pointLongArm',
          'okLongArm',
          'point',
          'ok',
          'hand',
          'handPhone',
        ],
      },
      default: [
        'wavePointLongArms',
        'waveOkLongArms',
        'waveLongArms',
        'waveLongArm',
        'pointLongArm',
        'okLongArm',
        'point',
        'ok',
        'hand',
        'handPhone',
      ],
    },
    gestureProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    glasses: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
    glassesProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 20,
    },
    hair: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant63',
          'variant62',
          'variant61',
          'variant60',
          'variant59',
          'variant58',
          'variant57',
          'variant56',
          'variant55',
          'variant54',
          'variant53',
          'variant52',
          'variant51',
          'variant50',
          'variant49',
          'variant48',
          'variant47',
          'variant46',
          'variant45',
          'variant44',
          'variant43',
          'variant42',
          'variant41',
          'variant40',
          'variant39',
          'variant38',
          'variant37',
          'variant36',
          'variant35',
          'variant34',
          'variant33',
          'variant32',
          'variant31',
          'variant30',
          'variant29',
          'variant28',
          'variant27',
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
          'hat',
        ],
      },
      default: [
        'variant63',
        'variant62',
        'variant61',
        'variant60',
        'variant59',
        'variant58',
        'variant57',
        'variant56',
        'variant55',
        'variant54',
        'variant53',
        'variant52',
        'variant51',
        'variant50',
        'variant49',
        'variant48',
        'variant47',
        'variant46',
        'variant45',
        'variant44',
        'variant43',
        'variant42',
        'variant41',
        'variant40',
        'variant39',
        'variant38',
        'variant37',
        'variant36',
        'variant35',
        'variant34',
        'variant33',
        'variant32',
        'variant31',
        'variant30',
        'variant29',
        'variant28',
        'variant27',
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
        'hat',
      ],
    },
    lips: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant30',
          'variant29',
          'variant28',
          'variant27',
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant30',
        'variant29',
        'variant28',
        'variant27',
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
    nose: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
    },
  },
};
