using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Nodes;
using Json.Schema;

namespace DiceBear.Internal
{
    /// <summary>
    /// Shared plumbing for the style and options validators: schema
    /// compilation and the mapping from JsonSchema.Net failures to
    /// <see cref="ValidationErrorDetail"/>.
    /// </summary>
    /// <remarks>
    /// The JS port has no counterpart for this file — its validators are
    /// standalone code generated by Ajv at build time. Here the two validators
    /// compile their schema at runtime instead and share this helper. Only the
    /// accept and reject decisions are parity-pinned across the ports; the
    /// detail list and the message text are not.
    /// </remarks>
    internal static class SchemaValidator
    {
        private static readonly Lazy<JsonSchema> DefinitionSchema =
            new Lazy<JsonSchema>(() => JsonSchema.FromText(DiceBear.Schema.Definition));

        private static readonly Lazy<JsonSchema> OptionsSchema =
            new Lazy<JsonSchema>(() => JsonSchema.FromText(DiceBear.Schema.Options));

        private static readonly EvaluationOptions Options = new EvaluationOptions
        {
            OutputFormat = OutputFormat.List,
        };

        /// <summary>
        /// Collects every way <paramref name="data"/> violates
        /// <c>definition.json</c>. An empty result means the data is valid.
        /// </summary>
        internal static IReadOnlyList<ValidationErrorDetail> CollectStyleErrors(JsonNode? data) =>
            Collect(DefinitionSchema.Value, data);

        /// <summary>
        /// Collects every way <paramref name="data"/> violates
        /// <c>options.json</c>. An empty result means the data is valid.
        /// </summary>
        internal static IReadOnlyList<ValidationErrorDetail> CollectOptionsErrors(JsonNode? data) =>
            Collect(OptionsSchema.Value, data);

        private static IReadOnlyList<ValidationErrorDetail> Collect(JsonSchema schema, JsonNode? data)
        {
            // JSON cannot represent non-finite numbers, and the Ajv-compiled
            // validators of the JS reference reject them wherever a number is
            // allowed (`type: "number"` compiles to `typeof data == "number" &&
            // isFinite(data)`). A hand-built JsonObject can still hold one, and
            // serializing it would throw instead of reporting a validation
            // failure, so the walk comes first.
            var nonFinite = new List<ValidationErrorDetail>();

            CollectNonFinite(data, string.Empty, nonFinite);

            if (nonFinite.Count > 0)
            {
                return nonFinite;
            }

            var results = schema.Evaluate(ToElement(data), Options);

            if (results.IsValid)
            {
                return Array.Empty<ValidationErrorDetail>();
            }

            var details = new List<ValidationErrorDetail>();

            foreach (var node in results.Details ?? new List<EvaluationResults>())
            {
                if (node.Errors is null)
                {
                    continue;
                }

                foreach (var error in node.Errors)
                {
                    var keyword = string.IsNullOrEmpty(error.Key) ? null : error.Key;
                    // The absolute schema location carries a generated base URI
                    // that changes from run to run, so the pointer is composed
                    // from the evaluation path instead: stable, and shaped like
                    // the `schemaPath` Ajv reports.
                    var schemaPath = "#" + node.EvaluationPath
                        + (keyword is null ? string.Empty : "/" + keyword);

                    details.Add(new ValidationErrorDetail(
                        message: error.Value,
                        instancePath: node.InstanceLocation.ToString(),
                        schemaPath: schemaPath,
                        keyword: keyword));
                }
            }

            // An invalid instance must never come back with an empty detail
            // list, or the caller would read it as valid.
            if (details.Count == 0)
            {
                details.Add(new ValidationErrorDetail(message: "does not match the schema"));
            }

            return details;
        }

        private static JsonElement ToElement(JsonNode? data) => JsonSerializer.SerializeToElement(data);

        private static void CollectNonFinite(JsonNode? node, string path, List<ValidationErrorDetail> into)
        {
            switch (node)
            {
                case JsonArray array:
                    for (var i = 0; i < array.Count; i++)
                    {
                        CollectNonFinite(array[i], path + "/" + i, into);
                    }

                    break;

                case JsonObject obj:
                    foreach (var entry in obj)
                    {
                        CollectNonFinite(entry.Value, path + "/" + PointerSegment(entry.Key), into);
                    }

                    break;

                case JsonValue value:
                    if (value.TryGetValue<double>(out var number)
                        && (double.IsNaN(number) || double.IsInfinity(number)))
                    {
                        into.Add(new ValidationErrorDetail(
                            message: "must be a finite number",
                            instancePath: path));
                    }

                    break;
            }
        }

        /// <summary>
        /// Escapes a JSON pointer segment per RFC 6901 (<c>~</c> to <c>~0</c>,
        /// <c>/</c> to <c>~1</c>).
        /// </summary>
        private static string PointerSegment(string key) =>
            key.Replace("~", "~0").Replace("/", "~1");
    }
}
