/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Top =
  | "longHair"
  | "shortHair"
  | "eyepatch"
  | "hat"
  | "hijab"
  | "turban"
  | "bigHair"
  | "bob"
  | "bun"
  | "curly"
  | "curvy"
  | "dreads"
  | "frida"
  | "fro"
  | "froAndBand"
  | "miaWallace"
  | "longButNotTooLong"
  | "shavedSides"
  | "straight01"
  | "straight02"
  | "straightAndStrand"
  | "dreads01"
  | "dreads02"
  | "frizzle"
  | "shaggy"
  | "shaggyMullet"
  | "shortCurly"
  | "shortFlat"
  | "shortRound"
  | "shortWaved"
  | "sides"
  | "theCaesar"
  | "theCaesarAndSidePart"
  | "winterHat01"
  | "winterHat02"
  | "winterHat03"
  | "winterHat04";
export type Chance = number;
export type Color =
  | "black"
  | "blue"
  | "blue01"
  | "blue02"
  | "blue03"
  | "gray"
  | "gray01"
  | "gray02"
  | "heather"
  | "pastel"
  | "pastelBlue"
  | "pastelGreen"
  | "pastelOrange"
  | "pastelRed"
  | "pastelYellow"
  | "pink"
  | "red"
  | "white";
export type HairColor =
  | "auburn"
  | "black"
  | "blonde"
  | "blondeGolden"
  | "brown"
  | "brownDark"
  | "pastel"
  | "pastelPink"
  | "platinum"
  | "red"
  | "gray"
  | "silverGray";
export type Accessories = "kurt" | "prescription01" | "prescription02" | "round" | "sunglasses" | "wayfarers";
export type FacialHair =
  | "medium"
  | "beardMedium"
  | "light"
  | "beardLight"
  | "majestic"
  | "beardMajestic"
  | "fancy"
  | "moustaceFancy"
  | "magnum"
  | "moustacheMagnum";
export type Clothes =
  | "blazer"
  | "blazerAndShirt"
  | "blazerAndSweater"
  | "sweater"
  | "collarAndSweater"
  | "shirt"
  | "graphicShirt"
  | "shirtCrewNeck"
  | "shirtScoopNeck"
  | "shirtVNeck"
  | "hoodie"
  | "overall";
export type Eyes =
  | "close"
  | "closed"
  | "cry"
  | "default"
  | "dizzy"
  | "xDizzy"
  | "roll"
  | "eyeRoll"
  | "happy"
  | "hearts"
  | "side"
  | "squint"
  | "surprised"
  | "wink"
  | "winkWacky";
export type Eyebrow =
  | "angry"
  | "angryNatural"
  | "default"
  | "defaultNatural"
  | "flat"
  | "flatNatural"
  | "raised"
  | "raisedExcited"
  | "raisedExcitedNatural"
  | "sad"
  | "sadConcerned"
  | "sadConcernedNatural"
  | "unibrow"
  | "unibrowNatural"
  | "up"
  | "upDown"
  | "upDownNatural"
  | "frown"
  | "frownNatural";
export type Mouth =
  | "concerned"
  | "default"
  | "disbelief"
  | "eating"
  | "grimace"
  | "sad"
  | "scream"
  | "screamOpen"
  | "serious"
  | "smile"
  | "tongue"
  | "twinkle"
  | "vomit";
export type Skin = "tanned" | "yellow" | "pale" | "light" | "brown" | "darkBrown" | "black";
export type ClotheGraphics =
  | "skullOutline"
  | "skull"
  | "resist"
  | "pizza"
  | "hola"
  | "diamond"
  | "deer"
  | "cumbia"
  | "bear"
  | "bat";

export interface Options {
  background?: string | "transparent";
  style?: "transparent" | "circle";
  /**
   * @deprecated
   */
  mode?: "include" | "exclude";
  top?: Top[];
  topChance?: Chance;
  hatColor?: Color[];
  hairColor?: HairColor[];
  accessories?: Accessories[];
  accessoriesChance?: Chance;
  accessoriesColor?: Color[];
  facialHair?: FacialHair[];
  facialHairChance?: Chance;
  facialHairColor?: HairColor[];
  clothes?: Clothes[];
  clothesColor?: Color[];
  eyes?: Eyes[];
  eyebrow?: Eyebrow[];
  mouth?: Mouth[];
  skin?: Skin[];
  clotheGraphics?: ClotheGraphics[];
}
