// Generated by scripts/generate-preview-seeds.mjs. Do not edit by hand.
//
// Three rows per avatar style, each searched against that style's own palette so
// no two avatars in a row look alike: the eight a style page opens with, the
// four on its card in the styles index, and the five on its social card. The
// first two spell DICEBEAR and DICE down their initials. No seed appears in more
// than one row, so moving between the three surfaces never shows the same avatar
// twice. Re-run the script after upgrading @dicebear/styles or adding a style.

export const previewRowSeeds: Record<string, string[]> = {
  'adventurer-neutral': ['Dax', 'Izumi', 'Celia', 'Edgar', 'Boris', 'Erik', 'Amara', 'Rocco'],
  adventurer: ['Daphne', 'Imani', 'Cai', 'Emil', 'Berta', 'Ethan', 'Adele', 'Regina'],
  'avataaars-neutral': ['Dax', 'Ida', 'Chiara', 'Elin', 'Beau', 'Enid', 'Anika', 'Rafael'],
  avataaars: ['Dalia', 'Ina', 'Carmen', 'Ella', 'Byron', 'Ethan', 'Alia', 'Renzo'],
  'big-ears-neutral': ['Dante', 'Ines', 'Casper', 'Emery', 'Bianca', 'Elise', 'Agnes', 'Rowan'],
  'big-ears': ['Dorian', 'Iva', 'Chiara', 'Ezra', 'Ben', 'Edda', 'Anika', 'Rowan'],
  'big-smile': ['Dora', 'Ismael', 'Carla', 'Edith', 'Bianca', 'Elias', 'Anton', 'Robin'],
  blobs: ['Dahlia', 'Inaya', 'Cai', 'Ewan', 'Bodhi', 'Emil', 'Aden', 'Ruben'],
  'bottts-neutral': ['Dahlia', 'Ilias', 'Callum', 'Eva', 'Ben', 'Elif', 'Anika', 'Ruben'],
  bottts: ['Dov', 'Ivan', 'Cyrus', 'Emil', 'Brea', 'Elin', 'Arden', 'Renzo'],
  clay: ['Doria', 'Irene', 'Caleb', 'Eva', 'Bente', 'Elio', 'Anouk', 'Robin'],
  constellation: ['Devon', 'Ilias', 'Curtis', 'Efe', 'Beau', 'Erik', 'Anton', 'Rhea'],
  critters: ['Dina', 'Inaya', 'Cato', 'Efe', 'Boris', 'Evren', 'Amir', 'Ruby'],
  'croodles-neutral': ['Dante', 'Inaya', 'Cai', 'Eden', 'Basil', 'Efe', 'Adele', 'Raul'],
  croodles: ['Dana', 'Inaya', 'Cato', 'Efe', 'Baris', 'Erik', 'Anja', 'Ravi'],
  disco: ['Dana', 'Isaac', 'Calla', 'Ezra', 'Bea', 'Edgar', 'Adele', 'Rida'],
  dylan: ['Dante', 'Ilaria', 'Cian', 'Esme', 'Blake', 'Elise', 'Amir', 'Roman'],
  'fun-emoji': ['Dahlia', 'Indira', 'Cian', 'Efe', 'Bianca', 'Elise', 'Amir', 'Rania'],
  glass: ['Dahlia', 'Ilias', 'Caleb', 'Efe', 'Bram', 'Eloise', 'Amir', 'Riley'],
  glyphs: ['Dalia', 'Ilse', 'Caleb', 'Enid', 'Bente', 'Edda', 'Agnes', 'Roshan'],
  icons: ['Dahlia', 'Iona', 'Callum', 'Edgar', 'Berta', 'Ella', 'Aden', 'Reza'],
  identicon: ['Dov', 'Izumi', 'Caspar', 'Eden', 'Brea', 'Enzo', 'Anika', 'Rosa'],
  'initial-face': ['Dahlia', 'Ida', 'Caleb', 'Elise', 'Bilal', 'Ezra', 'Arden', 'Raul'],
  initials: ['Dahlia', 'Idris', 'Cato', 'Edda', 'Basil', 'Erik', 'Adele', 'Ruby'],
  landscape: ['Duncan', 'Isaac', 'Cedric', 'Emil', 'Bram', 'Eden', 'Ava', 'Rocco'],
  loops: ['Dante', 'Imani', 'Callum', 'Elio', 'Basil', 'Emil', 'Adil', 'Renzo'],
  'lorelei-neutral': ['Dina', 'Isaac', 'Cedric', 'Elio', 'Bo', 'Erik', 'Aden', 'Rocco'],
  lorelei: ['Dara', 'Ilse', 'Caspar', 'Erik', 'Berta', 'Emil', 'Alia', 'Regina'],
  micah: ['Duncan', 'Iona', 'Cecile', 'Ella', 'Ben', 'Eva', 'Alec', 'Reza'],
  miniavs: ['Dima', 'Ina', 'Callum', 'Elif', 'Basil', 'Emil', 'Adele', 'Ravi'],
  moods: ['Dita', 'Indira', 'Casper', 'Eva', 'Bo', 'Eloise', 'Amina', 'Remy'],
  'notionists-neutral': ['Dahlia', 'Ilse', 'Casper', 'Emil', 'Boris', 'Ezra', 'Anja', 'Rita'],
  notionists: ['Duncan', 'Ingrid', 'Colin', 'Erik', 'Beau', 'Elif', 'Andre', 'Rida'],
  'open-peeps': ['Dante', 'Ines', 'Caleb', 'Elias', 'Bella', 'Enid', 'Aisha', 'Ravi'],
  personas: ['Dax', 'Imani', 'Ciara', 'Elise', 'Ben', 'Eva', 'Aria', 'Robin'],
  'pixel-art-neutral': ['Devon', 'Ingrid', 'Cyrus', 'Ezra', 'Bela', 'Elba', 'Anders', 'Rocco'],
  'pixel-art': ['Dries', 'Ilse', 'Carla', 'Elena', 'Basil', 'Efe', 'Astrid', 'Roshan'],
  pixelbot: ['Drew', 'Izumi', 'Chiara', 'Ethan', 'Blake', 'Elias', 'Axel', 'Ronan'],
  planets: ['Doria', 'Ina', 'Carmen', 'Elin', 'Basil', 'Enid', 'Ayla', 'Reza'],
  rings: ['Dara', 'Ilan', 'Cosima', 'Evren', 'Beau', 'Elif', 'Ana', 'Ruben'],
  'shape-grid': ['Deniz', 'Ivan', 'Clara', 'Elise', 'Bruno', 'Edda', 'Alia', 'Remy'],
  shapes: ['Deniz', 'Ida', 'Calla', 'Ethan', 'Bilal', 'Efe', 'Anders', 'Raul'],
  sprouts: ['Dov', 'Iva', 'Cecile', 'Evren', 'Bodhi', 'Elio', 'Adil', 'Ronan'],
  squircles: ['Dries', 'Ida', 'Ciara', 'Elba', 'Bodie', 'Edith', 'Agnes', 'Rania'],
  stripes: ['Dion', 'Isabel', 'Cai', 'Elias', 'Bodie', 'Edda', 'Ari', 'Remy'],
  thumbs: ['Drew', 'Ina', 'Curtis', 'Edgar', 'Ben', 'Emery', 'Alba', 'Reese'],
  'toon-head': ['Denver', 'Ilona', 'Chloe', 'Eloise', 'Brenda', 'Evren', 'Anika', 'Remy'],
  triangles: ['Dax', 'Ilse', 'Cato', 'Elio', 'Baris', 'Edgar', 'Adil', 'Rhys'],
  'voxel-art': ['Denver', 'Ilaria', 'Casper', 'Elin', 'Ben', 'Erik', 'Aden', 'Roshan'],
  'voxel-bot': ['Dion', 'Ida', 'Celia', 'Edda', 'Bodhi', 'Emery', 'Alia', 'Rosie'],
  waves: ['Dov', 'Iva', 'Cyrus', 'Eloise', 'Brody', 'Evelyn', 'Ari', 'Rania'],
  weave: ['Dax', 'Ilya', 'Chloe', 'Enid', 'Brody', 'Elif', 'Anders', 'Renzo'],
};

export const styleCardSeeds: Record<string, string[]> = {
  'adventurer-neutral': ['Dina', 'Ingrid', 'Cecile', 'Ezra'],
  adventurer: ['Dora', 'Ivy', 'Cecile', 'Elba'],
  'avataaars-neutral': ['Davi', 'Idris', 'Cedric', 'Emil'],
  avataaars: ['Darius', 'Imani', 'Carla', 'Emil'],
  'big-ears-neutral': ['Daphne', 'Ida', 'Celia', 'Edda'],
  'big-ears': ['Dante', 'Ivy', 'Clara', 'Eli'],
  'big-smile': ['Dorian', 'Ina', 'Callum', 'Ezra'],
  blobs: ['Darius', 'Irene', 'Ciro', 'Esme'],
  'bottts-neutral': ['Dalia', 'Idris', 'Cato', 'Eden'],
  bottts: ['Dax', 'Iker', 'Cian', 'Edgar'],
  clay: ['Dilan', 'Ivy', 'Calla', 'Enid'],
  constellation: ['Diana', 'Ilona', 'Cyrus', 'Elsa'],
  critters: ['Dalia', 'Ida', 'Cosima', 'Elio'],
  'croodles-neutral': ['Delia', 'Ilan', 'Caleb', 'Edith'],
  croodles: ['Doria', 'Idris', 'Calla', 'Elena'],
  disco: ['Dahlia', 'Ilya', 'Cosima', 'Elin'],
  dylan: ['Dahlia', 'Inaya', 'Colin', 'Ella'],
  'fun-emoji': ['Dalia', 'Ida', 'Caleb', 'Edgar'],
  glass: ['Dalia', 'Idris', 'Casper', 'Elio'],
  glyphs: ['Dana', 'Ida', 'Cai', 'Eden'],
  icons: ['Delia', 'Ismael', 'Celine', 'Elise'],
  identicon: ['Dahlia', 'Iker', 'Carla', 'Evelyn'],
  'initial-face': ['Dana', 'Idris', 'Camila', 'Efe'],
  initials: ['Dalia', 'Ida', 'Callum', 'Efe'],
  landscape: ['Delia', 'Isabel', 'Camila', 'Edda'],
  loops: ['Dilara', 'Ina', 'Carla', 'Elif'],
  'lorelei-neutral': ['Dara', 'Ingrid', 'Cai', 'Emil'],
  lorelei: ['Dima', 'Ida', 'Celia', 'Elena'],
  micah: ['Dana', 'Ines', 'Caspar', 'Evelyn'],
  miniavs: ['Dax', 'Ismael', 'Clara', 'Elba'],
  moods: ['Dahlia', 'Ines', 'Ciro', 'Ethan'],
  'notionists-neutral': ['Dalia', 'Idris', 'Cedric', 'Elio'],
  notionists: ['Dalia', 'Irene', 'Cato', 'Emil'],
  'open-peeps': ['Dries', 'Ilias', 'Cyrus', 'Ella'],
  personas: ['Deniz', 'Izumi', 'Casper', 'Ella'],
  'pixel-art-neutral': ['Dorian', 'Ida', 'Chloe', 'Esme'],
  'pixel-art': ['Dahlia', 'Iva', 'Camila', 'Elise'],
  pixelbot: ['Dina', 'Ines', 'Cyrus', 'Emil'],
  planets: ['Deniz', 'Ilan', 'Cai', 'Elsa'],
  rings: ['Dima', 'Izumi', 'Celine', 'Elias'],
  'shape-grid': ['Delia', 'Ismael', 'Ciro', 'Eli'],
  shapes: ['Dion', 'Ilona', 'Cosima', 'Elin'],
  sprouts: ['Davi', 'Idris', 'Calla', 'Eva'],
  squircles: ['Dov', 'Ilaria', 'Chloe', 'Elio'],
  stripes: ['Denver', 'Inaya', 'Chloe', 'Elba'],
  thumbs: ['Dara', 'Iva', 'Cecile', 'Emil'],
  'toon-head': ['Dana', 'Ines', 'Ciro', 'Elise'],
  triangles: ['Dion', 'Ingrid', 'Cyrus', 'Ella'],
  'voxel-art': ['Drew', 'Ingrid', 'Cora', 'Elise'],
  'voxel-bot': ['Drew', 'Inaya', 'Ciro', 'Elsa'],
  waves: ['Davi', 'Ilse', 'Calla', 'Elise'],
  weave: ['Dora', 'Iona', 'Cyrus', 'Elsa'],
};

export const ogTileSeeds: Record<string, string[]> = {
  'adventurer-neutral': ['Dahlia', 'Celine', 'Anja', 'Riley', 'Dora'],
  adventurer: ['Izumi', 'Celia', 'Brenda', 'Ewan', 'Emery'],
  'avataaars-neutral': ['Dahlia', 'Deniz', 'Ilse', 'Carmen', 'Izumi'],
  avataaars: ['Dahlia', 'Anika', 'Ronan', 'Raven', 'Cecile'],
  'big-ears-neutral': ['Dahlia', 'Inaya', 'Elio', 'Ivy', 'Dima'],
  'big-ears': ['Cato', 'Regina', 'Ines', 'Roshan', 'Colin'],
  'big-smile': ['Caleb', 'Denver', 'Anja', 'Enzo', 'Ilya'],
  blobs: ['Dalia', 'Raven', 'Elin', 'Ilaria', 'Emery'],
  'bottts-neutral': ['Dana', 'Dilan', 'Dorian', 'Ilona', 'Izumi'],
  bottts: ['Dahlia', 'Dima', 'Elise', 'Drew', 'Carla'],
  clay: ['Dahlia', 'Dorian', 'Chloe', 'Ilan', 'Callum'],
  constellation: ['Alba', 'Clara', 'Bram', 'Enid', 'Chiara'],
  critters: ['Dahlia', 'Edda', 'Blake', 'Beau', 'Ismael'],
  'croodles-neutral': ['Dahlia', 'Dina', 'Duncan', 'Dorian', 'Drew'],
  croodles: ['Dahlia', 'Bianca', 'Deniz', 'Ivan', 'Bruno'],
  disco: ['Dalia', 'Dion', 'Ingrid', 'Duncan', 'Izumi'],
  dylan: ['Dalia', 'Eva', 'Denver', 'Casper', 'Duncan'],
  'fun-emoji': ['Dax', 'Denver', 'Diana', 'Dorian', 'Duncan'],
  glass: ['Dana', 'Delia', 'Dilan', 'Ilan', 'Ida'],
  glyphs: ['Dahlia', 'Deniz', 'Dilara', 'Dorian', 'Ilona'],
  icons: ['Dalia', 'Ilaria', 'Dorian', 'Diana', 'Ivan'],
  identicon: ['Dalia', 'Delia', 'Ida', 'Bruno', 'Rida'],
  'initial-face': ['Dalia', 'Dion', 'Ilaria', 'Dora', 'Eden'],
  initials: ['Dana', 'Devon', 'Diana', 'Drew', 'Inaya'],
  landscape: ['Alma', 'Ruby', 'Cesar', 'Doria', 'Elba'],
  loops: ['Dahlia', 'Ilan', 'Devon', 'Dion', 'Cecile'],
  'lorelei-neutral': ['Iva', 'Dora', 'Elba', 'Celia', 'Dilara'],
  lorelei: ['Cato', 'Dina', 'Cesar', 'Renzo', 'Rocco'],
  micah: ['Dahlia', 'Elif', 'Delia', 'Robin', 'Bodil'],
  miniavs: ['Ilias', 'Colin', 'Dries', 'Deniz', 'Aria'],
  moods: ['Erik', 'Dilan', 'Ina', 'Emil', 'Bram'],
  'notionists-neutral': ['Dana', 'Dora', 'Iva', 'Celia', 'Renzo'],
  notionists: ['Bela', 'Dina', 'Dorian', 'Denver', 'Elio'],
  'open-peeps': ['Cecile', 'Ayla', 'Chiara', 'Eva', 'Idris'],
  personas: ['Britt', 'Baxter', 'Alia', 'Cedric', 'Evren'],
  'pixel-art-neutral': ['Clara', 'Idris', 'Baxter', 'Andre', 'Calla'],
  'pixel-art': ['Dalia', 'Dorian', 'Ilona', 'Dilan', 'Colin'],
  pixelbot: ['Dax', 'Ilse', 'Bruno', 'Iker', 'Eli'],
  planets: ['Dahlia', 'Esme', 'Ruby', 'Arlo', 'Bruno'],
  rings: ['Dahlia', 'Deniz', 'Iva', 'Cyrus', 'Anja'],
  'shape-grid': ['Dahlia', 'Dina', 'Alma', 'Doria', 'Ciara'],
  shapes: ['Dahlia', 'Celia', 'Rosa', 'Bodie', 'Cai'],
  sprouts: ['Dahlia', 'Ana', 'Rafa', 'Dilara', 'Alba'],
  squircles: ['Dahlia', 'Eloise', 'Dina', 'Cyrus', 'Iva'],
  stripes: ['Dahlia', 'Brody', 'Alec', 'Clara', 'Dora'],
  thumbs: ['Dahlia', 'Delia', 'Elif', 'Dima', 'Ilona'],
  'toon-head': ['Dahlia', 'Ana', 'Ravi', 'Calla', 'Emil'],
  triangles: ['Dahlia', 'Curtis', 'Celia', 'Inaya', 'Drew'],
  'voxel-art': ['Dahlia', 'Rosie', 'Rita', 'Beau', 'Dilan'],
  'voxel-bot': ['Dahlia', 'Ciara', 'Ronan', 'Rhea', 'Ruben'],
  waves: ['Diana', 'Andre', 'Roshan', 'Cato', 'Chloe'],
  weave: ['Dahlia', 'Doria', 'Alia', 'Roman', 'Imani'],
};

/**
 * The eight avatars a style page opens with. Throws rather than falling back,
 * matching getStyleCategory: a style missing here means the table was not
 * regenerated after the style shipped, and a silent default would hide that.
 */
export function getPreviewRowSeeds(styleName: string): string[] {
  return lookUp(previewRowSeeds, styleName, 'preview row');
}

/**
 * The four avatars on a style's card in the index. Shares no seed with that
 * style's preview row, so clicking a card does not reopen the same avatars.
 */
export function getStyleCardSeeds(styleName: string): string[] {
  return lookUp(styleCardSeeds, styleName, 'card row');
}

/** The five avatars on a style's Open Graph card. */
export function getOgTileSeeds(styleName: string): string[] {
  return lookUp(ogTileSeeds, styleName, 'social card row');
}

function lookUp(
  table: Record<string, string[]>,
  styleName: string,
  label: string,
): string[] {
  const seeds = table[styleName];

  if (!seeds) {
    throw new Error(
      `Avatar style "${styleName}" has no ${label}. Run node scripts/generate-preview-seeds.mjs.`,
    );
  }

  return seeds;
}
