import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  title: 'Options',
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    backgroundColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
        'variant06',
        'variant07',
        'variant08',
      ],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
        ['variant06'],
        ['variant07'],
        ['variant08'],
      ],
    },
    eyes: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    eyesColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
        'variant06',
      ],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
        ['variant06'],
      ],
    },
    glasses: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'light07',
          'light06',
          'light05',
          'light04',
          'light03',
          'light02',
          'light01',
          'dark07',
          'dark06',
          'dark05',
          'dark04',
          'dark03',
          'dark02',
          'dark01',
        ],
      },
      default: [
        'light07',
        'light06',
        'light05',
        'light04',
        'light03',
        'light02',
        'light01',
        'dark07',
        'dark06',
        'dark05',
        'dark04',
        'dark03',
        'dark02',
        'dark01',
      ],
      examples: [
        ['light07'],
        ['light06'],
        ['light05'],
        ['light04'],
        ['light03'],
        ['light02'],
        ['light01'],
        ['dark07'],
        ['dark06'],
        ['dark05'],
        ['dark04'],
        ['dark03'],
        ['dark02'],
        ['dark01'],
      ],
    },
    glassesColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['black01', 'black02', 'black03', 'blue01', 'green01', 'red01'],
      examples: [
        ['black01'],
        ['black02'],
        ['black03'],
        ['blue01'],
        ['green01'],
        ['red01'],
      ],
    },
    glassesProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    mouth: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'sad10',
          'sad09',
          'sad08',
          'sad07',
          'sad06',
          'sad05',
          'sad04',
          'sad03',
          'sad02',
          'sad01',
          'happy13',
          'happy12',
          'happy11',
          'happy10',
          'happy09',
          'happy08',
          'happy07',
          'happy06',
          'happy05',
          'happy04',
          'happy03',
          'happy02',
          'happy01',
        ],
      },
      default: [
        'sad10',
        'sad09',
        'sad08',
        'sad07',
        'sad06',
        'sad05',
        'sad04',
        'sad03',
        'sad02',
        'sad01',
        'happy13',
        'happy12',
        'happy11',
        'happy10',
        'happy09',
        'happy08',
        'happy07',
        'happy06',
        'happy05',
        'happy04',
        'happy03',
        'happy02',
        'happy01',
      ],
      examples: [
        ['sad10'],
        ['sad09'],
        ['sad08'],
        ['sad07'],
        ['sad06'],
        ['sad05'],
        ['sad04'],
        ['sad03'],
        ['sad02'],
        ['sad01'],
        ['happy13'],
        ['happy12'],
        ['happy11'],
        ['happy10'],
        ['happy09'],
        ['happy08'],
        ['happy07'],
        ['happy06'],
        ['happy05'],
        ['happy04'],
        ['happy03'],
        ['happy02'],
        ['happy01'],
      ],
    },
    mouthColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['variant01', 'variant02', 'variant03', 'variant04'],
      examples: [['variant01'], ['variant02'], ['variant03'], ['variant04']],
    },
  },
  additionalProperties: false,
};
