/// Walks a style's element tree and turns it into the final SVG markup.
library;

import 'dart:math' as math;

import 'prng/fnv1a.dart';
import 'resolver.dart';
import 'style.dart';
import 'style/canvas.dart';
import 'style/component.dart';
import 'style/element.dart';
import 'utils/initials.dart';
import 'utils/license.dart';
import 'utils/number.dart';
import 'utils/xml.dart';

/// Walks a style's element tree and turns it into the final SVG markup.
///
/// The renderer is single-use: it accumulates `<defs>` entries and per-render
/// caches across method calls, so a fresh instance is required per avatar. A
/// circular color reference encountered during resolution surfaces as a
/// `CircularColorReferenceError` thrown from [render].
class Renderer {
  /// The canonical track order, outermost wrapper to innermost. It mirrors
  /// the usual translate → rotate → scale transform composition. Every port
  /// must wrap in this exact order for the outputs to stay byte-identical.
  static const List<String> _trackOrder = [
    'translateX',
    'translateY',
    'rotate',
    'scaleX',
    'scaleY',
    'opacity',
  ];

  static const Map<String, String> _directionCss = {
    'normal': 'normal',
    'reverse': 'reverse',
    'alternate': 'alternate',
    'alternateReverse': 'alternate-reverse',
  };

  static const Map<String, String> _easingKeywordCss = {
    'linear': 'linear',
    'ease': 'ease',
    'easeIn': 'ease-in',
    'easeOut': 'ease-out',
    'easeInOut': 'ease-in-out',
    'hold': 'step-end',
  };

  final Style _style;
  final Resolver _resolver;

  // Insertion-ordered like the JS Map: updating an existing key keeps its
  // original position — Dart's default map does both natively (Go wrote an
  // orderedDefs helper, Rust uses IndexMap).
  final Map<String, String> _defs = {};
  String? _cachedSeedHash;
  String? _cachedInitials;
  String? _cachedAnimationHash;
  String? _cachedRandomSuffix;
  final List<String> _keyframesCss = [];
  final List<String> _animationCss = [];
  final Map<String, String> _keyframesByContent = {};
  int _keyframesCounter = 0;
  int _animationClassCounter = 0;

  Renderer(Style style, Resolver resolver)
      : _style = style,
        _resolver = resolver;

  /// Builds the complete SVG document for the avatar.
  String render() {
    final canvas = _style.canvas;
    final background = _renderBackground(canvas);
    var body = _renderElements(canvas.elements);

    // Order matters: scale and flip around center, then rotate, translate,
    // and finally clip with border radius (outermost wrapper).
    body = _applyScale(body, canvas);
    body = _applyFlip(body, canvas);
    body = _applyRotate(body, canvas);
    body = _applyTranslate(body, canvas);
    body = _applyBorderRadius('$background$body', canvas);

    _registerAnimationStyle();

    final metadata = licenseXml(_style.meta);
    final defs = _defs.isNotEmpty ? '<defs>${_defs.values.join()}</defs>' : '';

    // Resolve size before title and the root attributes so the resolver memo
    // records the keys in the same order as the JS/PHP/Python ports — the
    // JSON envelope emits the resolved options in first-recorded order.
    final size = _resolver.size();

    final title = _resolver.title();
    final escapedTitle = title != null ? escapeXml(title) : null;

    final attrs = <String>[
      'xmlns="http://www.w3.org/2000/svg"',
      'viewBox="0 0 ${formatNumber(canvas.width)} ${formatNumber(canvas.height)}"',
    ];

    final rootAttributes = _renderAttributes(_style.attributes());

    if (rootAttributes.isNotEmpty) {
      // _renderAttributes returns a leading space; the root attributes sit
      // between the fixed entries, so strip it here like the JS trimStart().
      attrs.add(rootAttributes.trimLeft());
    }

    if (escapedTitle != null) {
      attrs.add('role="img"');
      attrs.add('aria-label="$escapedTitle"');
    } else {
      attrs.add('aria-hidden="true"');
    }

    if (size != null) {
      final sizeValue = formatNumber(size);

      attrs.add('width="$sizeValue"');
      attrs.add('height="$sizeValue"');
    }

    final titleElement =
        escapedTitle != null ? '<title>$escapedTitle</title>' : '';

    var svg = '<svg ${attrs.join(' ')}>'
        '<!-- Generated by DiceBear (https://www.dicebear.com) -->'
        '$metadata$defs$titleElement$body</svg>';

    if (_resolver.idRandomization()) {
      svg = _randomizeIds(svg);
    }

    return svg;
  }

  /// Wraps [body] in a flip transform when `flip` is set to anything other
  /// than `'none'`.
  String _applyFlip(String body, Canvas canvas) {
    final flip = _resolver.flip();

    if (flip == 'none') {
      return body;
    }

    final w = formatNumber(canvas.width);
    final h = formatNumber(canvas.height);
    final String transform;

    switch (flip) {
      case 'horizontal':
        transform = 'translate($w, 0) scale(-1, 1)';
      case 'vertical':
        transform = 'translate(0, $h) scale(1, -1)';
      case 'both':
        transform = 'translate($w, $h) scale(-1, -1)';
      default:
        return body;
    }

    return '<g transform="$transform">$body</g>';
  }

  /// Wraps [body] in a uniform scale transform around the canvas center when
  /// the option differs from `1`.
  String _applyScale(String body, Canvas canvas) {
    final scale = _resolver.scale();

    if (scale == 1) {
      return body;
    }

    final cx = canvas.width / 2;
    final cy = canvas.height / 2;

    return '<g transform="translate(${formatNumber(cx)}, ${formatNumber(cy)}) '
        'scale(${formatNumber(scale)}) '
        'translate(${formatNumber(-cx)}, ${formatNumber(-cy)})">$body</g>';
  }

  /// Clips [body] to the canvas rectangle (rounded when `borderRadius` is
  /// non-zero) and registers the corresponding `clipPath` in `<defs>`. The
  /// clip is always applied so transformed content cannot bleed past the
  /// canvas bounds, regardless of the consumer's `overflow` setting.
  String _applyBorderRadius(String body, Canvas canvas) {
    final radius = _resolver.borderRadius();
    final id = 'clip-${_hashSeed()}';

    final rx = formatNumber(radius / 100 * canvas.width);
    final ry = formatNumber(radius / 100 * canvas.height);

    _defs[id] = '<clipPath id="$id">'
        '<rect width="${formatNumber(canvas.width)}" '
        'height="${formatNumber(canvas.height)}" rx="$rx" ry="$ry"/>'
        '</clipPath>';

    return '<g clip-path="url(#$id)">$body</g>';
  }

  /// Wraps [body] in a rotation around the canvas center when `rotate` is
  /// non-zero.
  String _applyRotate(String body, Canvas canvas) {
    final rotate = _resolver.rotate();

    if (rotate == 0) {
      return body;
    }

    final cx = canvas.width / 2;
    final cy = canvas.height / 2;

    return '<g transform="rotate(${formatNumber(rotate)}, '
        '${formatNumber(cx)}, ${formatNumber(cy)})">$body</g>';
  }

  /// Wraps [body] in a translate transform when either `translateX` or
  /// `translateY` is non-zero. Offsets are interpreted as percentages of the
  /// canvas dimensions.
  String _applyTranslate(String body, Canvas canvas) {
    final tx = _resolver.translateX();
    final ty = _resolver.translateY();

    if (tx == 0 && ty == 0) {
      return body;
    }

    final x = formatNumber(tx / 100 * canvas.width);
    final y = formatNumber(ty / 100 * canvas.height);

    return '<g transform="translate($x, $y)">$body</g>';
  }

  /// Returns a `<rect>` filling the canvas with the resolved background
  /// color, or an empty string when no background colors are configured.
  /// This is the first resolver call of the render, so
  /// `backgroundColorFill` and `backgroundColor` open the snapshot.
  String _renderBackground(Canvas canvas) {
    final colors = _resolver.color('background');

    if (colors.isEmpty) {
      return '';
    }

    return '<rect width="${formatNumber(canvas.width)}" '
        'height="${formatNumber(canvas.height)}" '
        'fill="${escapeXml(_resolveColorReference('background'))}"/>';
  }

  /// Returns the hex string that separates this render from every other one
  /// under `idRandomization`, drawn once and cached. Process randomness
  /// ([math.Random], the JS `Math.random()`) is intentional — a PRNG-derived
  /// value would repeat for the same seed.
  String _randomSuffix() {
    // floor(random * 0xffffff) yields 0..0xfffffe (exclusive upper bound),
    // matching the JS reference rather than a masked 0..0xffffff.
    return _cachedRandomSuffix ??= (_random.nextDouble() * 0xffffff)
        .floor()
        .toRadixString(16)
        .padLeft(6, '0');
  }

  /// Suffixes every `id` declaration and reference with the render's random
  /// suffix so that multiple instances of the same avatar do not collide in a
  /// shared document. The animation class and keyframe names carry the same
  /// suffix through [_animationHash].
  String _randomizeIds(String svg) {
    final suffix = _randomSuffix();

    // A Dart Set keeps insertion order, like the JS Set the reference fills.
    final ids = <String>{
      for (final match in _idDeclaration.allMatches(svg)) match[1]!,
    };

    if (ids.isEmpty) {
      return svg;
    }

    final escaped = [
      for (final id in ids)
        id.replaceAllMapped(_regExpSpecials, (m) => '\\${m[0]}'),
    ];
    final pattern =
        RegExp('(id="|url\\(#|href="#)(${escaped.join('|')})("|\\))');

    return svg.replaceAllMapped(
      pattern,
      (m) => '${m[1]}${m[2]}-$suffix${m[3]}',
    );
  }

  /// Renders a list of elements and concatenates their markup.
  String _renderElements(List<ElementNode> elements) =>
      [for (final element in elements) _renderElement(element)].join();

  /// Dispatches a single element to the renderer for its type.
  String _renderElement(ElementNode element) {
    switch (element.type) {
      case 'element':
        return _renderSvgElement(element);
      case 'text':
        return _renderTextElement(element);
      case 'component':
        return _renderComponentElement(element);
      default:
        return '';
    }
  }

  /// Renders an SVG element. The special `defs` name diverts children into
  /// the shared `<defs>` block.
  ///
  /// Element names and attribute names are not escaped here — they are
  /// validated against a strict allowlist schema (no `<script>`, no event
  /// handlers). Values are escaped via [escapeXml].
  String _renderSvgElement(ElementNode element) {
    final name = element.name;

    if (name == null || name.isEmpty) {
      return '';
    }

    if (name == 'defs') {
      for (final child in element.children) {
        final rendered = _renderElement(child);

        if (rendered.isNotEmpty) {
          // The def key is the child's literal `id` attribute (not a
          // color/variable reference object), else a positional `_N` key
          // evaluated at insertion time.
          final id = child.attributes?['id'];
          final key = id is String ? id : '_${_defs.length}';

          _defs[key] = rendered;
        }
      }

      return '';
    }

    final children = _renderElements(element.children);

    // A wrapper whose children all rendered to nothing, because an optional
    // component came up empty, has no content left to group. It draws
    // nothing either way, but a masked group without content has an empty
    // bounding box, and strict SVG parsers reject the whole document over
    // it. Wrappers that carry an id stay, so references keep resolving.
    if (children.isEmpty &&
        element.children.isNotEmpty &&
        element.attributes?['id'] == null) {
      return '';
    }

    // The animation switches are read once the element is known to render,
    // after its children, so the resolved options record them in one order
    // regardless of the attributes the element carries.
    final active = _playingAnimations(element);
    final attrs = _renderAttributes(
      _attributesWithoutAnimatedOpacity(element.attributes, active),
    );

    if (children.isEmpty) {
      return _applyAnimations('<$name$attrs/>', element, active);
    }

    return _applyAnimations('<$name$attrs>$children</$name>', element, active);
  }

  /// Renders a text element by escaping its resolved value.
  String _renderTextElement(ElementNode element) {
    final value = element.value;

    return value != null ? escapeXml(_resolveValue(value)) : '';
  }

  /// Resolves a component reference to a chosen variant and emits a `<use>`
  /// pointing at a `<defs>` entry that holds the variant body. Aliases of the
  /// same source component sharing a variant — and identical components
  /// referenced more than once — therefore produce a single `<defs>` entry
  /// referenced by every `<use>`, never duplicated SVG markup.
  ///
  /// Any `attributes` on the component reference are written to the emitted
  /// `<use>` tag. A user-supplied `transform` is prepended to the
  /// per-component transforms so it acts as the outer (placement) transform,
  /// with the style's translate/rotate/scale applied inside it.
  String _renderComponentElement(ElementNode element) {
    final componentName = element.name;

    if (componentName == null) {
      return '';
    }

    final variantName = _resolver.variant(componentName);

    if (variantName == null || variantName.isEmpty) {
      return '';
    }

    final component = _style.components[componentName];

    if (component == null) {
      return '';
    }

    final variant = component.variants()[variantName];

    if (variant == null) {
      return '';
    }

    // The def ID uses the source name, so aliases sharing a variant produce
    // one <g> def and several <use> references.
    final id = '${component.sourceName}-$variantName-${_hashSeed()}';

    if (!_defs.containsKey(id)) {
      final body = _renderElements(variant.elements());

      _defs[id] = '<g id="$id">$body</g>';
    }

    final transforms = _buildTransforms(component);
    final active = _playingAnimations(element);
    final userAttributes =
        _attributesWithoutAnimatedOpacity(element.attributes, active);
    Map<String, Object?>? mergedAttributes = userAttributes;

    if (transforms.isNotEmpty) {
      final userTransform = userAttributes?['transform'];
      final allParts = userTransform is String && userTransform.isNotEmpty
          ? [userTransform, ...transforms]
          : transforms;

      // Assigning to an existing `transform` key keeps its position in the
      // attribute order; a new key is appended — the JS object spread
      // semantics (Dart maps behave the same way).
      mergedAttributes = {...?userAttributes};
      mergedAttributes['transform'] = allParts.join(' ');
    }

    final attrs = _renderAttributes(mergedAttributes);

    return _applyAnimations('<use$attrs href="#$id"/>', element, active);
  }

  /// Returns the per-component SVG `transform` fragments derived from the
  /// component's translate, rotate, and scale options. Translate values are
  /// percentages of the component canvas dimensions, matching the semantics
  /// of the user-facing `translateX` / `translateY` options.
  ///
  /// The fragments are ordered so that, when joined into a single `transform`
  /// attribute, the scale is the rightmost (innermost) transform — applied
  /// first to a point, followed by rotate, then translate.
  List<String> _buildTransforms(Component component) {
    final transform = _resolver.componentTransform(component.name);
    final rotate = transform.rotate;
    final translateX = transform.translateX;
    final translateY = transform.translateY;
    final scale = transform.scale;

    if (translateX == 0 && translateY == 0 && rotate == 0 && scale == 1) {
      return const [];
    }

    final transforms = <String>[];
    final cx = component.width / 2;
    final cy = component.height / 2;
    final cxValue = formatNumber(cx);
    final cyValue = formatNumber(cy);

    if (translateX != 0 || translateY != 0) {
      final x = formatNumber(translateX / 100 * component.width);
      final y = formatNumber(translateY / 100 * component.height);

      transforms.add('translate($x, $y)');
    }

    if (rotate != 0) {
      transforms.add('rotate(${formatNumber(rotate)}, $cxValue, $cyValue)');
    }

    if (scale != 1) {
      transforms.add('translate($cxValue, $cyValue) '
          'scale(${formatNumber(scale)}) '
          'translate(${formatNumber(-cx)}, ${formatNumber(-cy)})');
    }

    return transforms;
  }

  /// Serializes an attribute map to a leading space-prefixed string suitable
  /// for inlining into a tag. Returns an empty string when there are no
  /// attributes to render. Entries render in map insertion order — SVG
  /// attribute order is load-bearing for byte parity.
  String _renderAttributes(Map<String, Object?>? attributes) {
    if (attributes == null) {
      return '';
    }

    final parts = <String>[];

    for (final entry in attributes.entries) {
      final value = entry.value;

      if (value == null) {
        continue;
      }

      parts.add('${entry.key}="${escapeXml(_resolveAttributeValue(value))}"');
    }

    if (parts.isEmpty) {
      return '';
    }

    return ' ${parts.join(' ')}';
  }

  /// Resolves a single attribute value: literal strings pass through, color
  /// and variable references are dereferenced through the option resolver.
  String _resolveAttributeValue(Object value) {
    if (value is String) {
      return value;
    }

    final reference = value as Map<String, Object?>;
    final name = reference['name'] as String;

    if (reference['type'] == 'color') {
      return _resolveColorReference(name);
    }

    return _resolveVariable(name);
  }

  /// Resolves a named color into either a hex string (solid fill / single
  /// color) or a `url(#…)` gradient reference, registering the gradient in
  /// `<defs>` as a side effect.
  String _resolveColorReference(String name) {
    final colors = _resolver.color(name);
    final fill = _resolver.colorFill(name);

    if (fill == 'solid' || colors.length <= 1) {
      return colors.isNotEmpty ? colors[0] : 'none';
    }

    return _buildGradientDef(name, colors, fill);
  }

  /// Builds the `<linearGradient>` or `<radialGradient>` for the given color
  /// definition, registers it in `<defs>`, and returns its `url(#…)`
  /// reference. This is the only caller of `colorAngle`, so the angle is
  /// drawn — and recorded in the snapshot — only when a gradient is built.
  String _buildGradientDef(String name, List<String> colors, String fill) {
    final rotation = _resolver.colorAngle(name);
    final id = '$name-color-${_hashSeed()}';
    final tag = fill == 'linear' ? 'linearGradient' : 'radialGradient';
    final rotateAttr = rotation != 0
        ? ' gradientTransform="rotate(${formatNumber(rotation)}, 0.5, 0.5)"'
        : '';
    final stops = StringBuffer();

    for (var i = 0; i < colors.length; i++) {
      final offset = formatNumber(i / (colors.length - 1) * 100);

      stops.write(
        '<stop offset="$offset%" stop-color="${escapeXml(colors[i])}"/>',
      );
    }

    _defs[id] = '<$tag id="$id"$rotateAttr>$stops</$tag>';

    return 'url(#$id)';
  }

  /// Resolves an element value to its final string form. Literal strings pass
  /// through; variable references are dereferenced.
  String _resolveValue(Object value) {
    if (value is String) {
      return value;
    }

    final reference = value as Map<String, Object?>;

    if (reference['type'] == 'variable') {
      return _resolveVariable(reference['name'] as String);
    }

    return '';
  }

  /// Resolves a built-in variable reference to its current value.
  String _resolveVariable(String name) {
    switch (name) {
      case 'initial':
        // charAt(0) would return a lone surrogate (ill-formed XML) for
        // supplementary-plane initials; take the full first code point
        // instead, like the JS/PHP/Python/Rust/Go ports.
        final initials = _initials();

        return initials.isEmpty
            ? ''
            : String.fromCharCode(initials.runes.first);
      case 'initials':
        return _initials();
      case 'fontWeight':
        return formatNumber(_resolver.fontWeight());
      case 'fontFamily':
        return _resolver.fontFamily();
      default:
        return '';
    }
  }

  /// Returns the seed-derived initials, cached after the first call.
  String _initials() => _cachedInitials ??= initialsFromSeed(_resolver.seed());

  /// Returns the FNV-1a hex hash of the style source name and seed, cached
  /// after the first call. The value is used to derive stable but unique IDs
  /// for `<defs>` entries; the source name keeps same-seed avatars of
  /// different styles from colliding when inlined on one page.
  String _hashSeed() => _cachedSeedHash ??=
      fnv1aHex('${_style.meta.source().name() ?? ''}:${_resolver.seed()}');

  /// Returns the FNV-1a hex hash namespacing the animation class and keyframe
  /// names, cached after the first call. Extends the [_hashSeed] input with
  /// the animation speed and delay and the state of every named timeline the
  /// style carries: two renders of the same avatar with different speeds,
  /// delays, or switches inlined on one page must not select each other's
  /// rules, while identical renders sharing identical rules is harmless
  /// deduplication.
  ///
  /// Everything else about an avatar stays out of the hash, so two renders of
  /// the same style and seed that differ in any other option would share their
  /// names with different rule bodies. `idRandomization` is the way out of
  /// that collision, and it reaches the animation names through this input
  /// rather than through the id rewrite, which only knows
  /// `id`/`url(#…)`/`href`.
  String _animationHash() {
    final cached = _cachedAnimationHash;

    if (cached != null) {
      return cached;
    }

    final random = _resolver.idRandomization() ? ':${_randomSuffix()}' : '';

    // Every named timeline the style carries joins the hash with its state,
    // `off` or the factor and offset it plays at, in code unit order (the
    // order [Style.animationNames] keeps), so two renders that differ only in
    // a per-name switch, speed, or delay option never share their rules. A
    // style without named timelines adds no part.
    final states = [
      for (final name in _style.animationNames)
        _resolver.animationPlays(name)
            ? '$name:${formatNumber(_resolver.animationSpeedFor(name))}:'
                '${formatNumber(_resolver.animationDelayFor(name))}'
            : '$name:off',
    ];
    final named = states.isEmpty ? '' : ':${states.join(',')}';

    return _cachedAnimationHash = fnv1aHex(
      '${_style.meta.source().name() ?? ''}:${_resolver.seed()}:'
      '${formatNumber(_resolver.animationSpeed())}:'
      '${formatNumber(_resolver.animationDelay())}$named$random',
    );
  }

  /// Wraps an element's rendered markup in one `<g class="…">` per animation
  /// track and queues the matching CSS. A no-op when no animation plays on
  /// the element ([active] empty) or its markup rendered to nothing (the
  /// empty-wrapper pruning then also prunes the animation).
  ///
  /// Wrapper nesting is block 0 outermost, and within a block the canonical
  /// track order (translate before rotate before scale, opacity innermost) —
  /// the composition contract the Figma plugin maps onto node transforms.
  ///
  /// The element's own `opacity` rides on the innermost opacity wrapper as the
  /// resting value the keyframes then override.
  String _applyAnimations(
    String markup,
    ElementNode element,
    List<Map<String, Object?>> active,
  ) {
    if (markup.isEmpty || active.isEmpty) {
      return markup;
    }

    final classes = <String>[];
    var opacityWrapper = -1;

    for (final animation in active) {
      final tracks = animation['tracks'] as Map<String, Object?>;

      for (final track in _trackOrder) {
        final trackData = tracks[track] as Map<String, Object?>?;

        if (trackData != null) {
          if (track == 'opacity') {
            opacityWrapper = classes.length;
          }

          classes.add(_buildAnimationCss(
            animation,
            track,
            trackData['keyframes'] as List<Object?>,
          ));
        }
      }
    }

    final restingOpacity = element.attributes?['opacity'];
    var result = markup;

    for (var i = classes.length - 1; i >= 0; i--) {
      final opacity = i == opacityWrapper && restingOpacity != null
          ? _renderAttributes({'opacity': restingOpacity})
          : '';

      result = '<g class="${classes[i]}"$opacity>$result</g>';
    }

    return result;
  }

  /// Returns the timelines of [element] that play. The element check comes
  /// first: only styles that carry declarative animations may touch the
  /// options, so the resolved-options snapshot of every other avatar stays
  /// free of them. The global switch is read next so it lands in the
  /// resolved options whenever a node carries animations, on or off. Named
  /// timelines then follow their own switch when the user set one.
  List<Map<String, Object?>> _playingAnimations(ElementNode element) {
    final animations = element.animations;

    if (animations.isEmpty) {
      return const [];
    }

    _resolver.animation();

    return [
      for (final entry in animations)
        if (_resolver.animationPlays(
          (entry as Map<String, Object?>)['name'] as String?,
        ))
          entry,
    ];
  }

  /// Strips the `opacity` attribute an animated opacity track takes over.
  ///
  /// A track writes the opacity the author means, not a factor on top of the
  /// element's own value: an element hidden with `opacity="0"` is a resting
  /// state the animation replaces, the way a CSS animation on the element
  /// itself would. The attribute therefore moves to the animating wrapper,
  /// where the keyframes override it. With the animation off no wrapper
  /// exists and the attribute stays where it is.
  ///
  /// [active] is the element's playing animations as [_playingAnimations]
  /// returns them, read once by the caller and shared with the wrapper step.
  Map<String, Object?>? _attributesWithoutAnimatedOpacity(
    Map<String, Object?>? attributes,
    List<Map<String, Object?>> active,
  ) {
    if (attributes == null || attributes['opacity'] == null) {
      return attributes;
    }

    for (final animation in active) {
      final tracks = animation['tracks'] as Map<String, Object?>;

      if (tracks['opacity'] != null) {
        final rest = {...attributes};
        rest.remove('opacity');

        return rest;
      }
    }

    return attributes;
  }

  /// Generates the `@keyframes` block (deduplicated by content, so identical
  /// tracks on many elements share one block) and the class rule for a single
  /// track, and returns the class name.
  String _buildAnimationCss(
    Map<String, Object?> animation,
    String track,
    List<Object?> keyframes,
  ) {
    final defaultEasing = animation['easing'] ?? 'linear';
    final body = _keyframesBody(track, keyframes, defaultEasing);

    var keyframesName = _keyframesByContent[body];

    if (keyframesName == null) {
      keyframesName = 'dbk-${_animationHash()}-${_keyframesCounter++}';

      _keyframesByContent[body] = keyframesName;
      _keyframesCss.add('@keyframes $keyframesName{$body}');
    }

    final name = animation['name'] as String?;
    final speed = _resolver.animationSpeedFor(name);
    final duration = formatNumber((animation['duration'] as num) / speed);

    // The user's offset is wall clock seconds, so it is added after the speed
    // has scaled the authored delay.
    final delay = formatNumber(
      (animation['delay'] as num? ?? 0) / speed +
          _resolver.animationDelayFor(name),
    );
    final rawIterations = animation['iterations'];
    final iterations = rawIterations is num
        ? formatNumber(rawIterations.toDouble())
        : 'infinite';
    final direction = _directionCss[animation['direction']] ?? 'normal';
    final fill = animation['fill'] as String? ?? 'none';

    // Only rotate and scale pivot around a point. Translation and opacity
    // need no origin, so their rules skip the transform-box prefix.
    final needsOrigin =
        track == 'rotate' || track == 'scaleX' || track == 'scaleY';
    var originCss = '';

    if (needsOrigin) {
      final origin = animation['origin'] as Map<String, Object?>?;
      final x = formatNumber((origin?['x'] as num? ?? 50).toDouble());
      final y = formatNumber((origin?['y'] as num? ?? 50).toDouble());

      originCss = 'transform-box:fill-box;transform-origin:$x% $y%;';
    }

    final className = 'dba-${_animationHash()}-${_animationClassCounter++}';

    // The name comes last in the shorthand so it can never be mistaken for a
    // keyword. All seven tokens are always emitted so every port serializes
    // the same string.
    _animationCss.add(
      '.$className{${originCss}animation:${duration}s '
      '${_easingCss(defaultEasing)} ${delay}s $iterations $direction $fill '
      '$keyframesName}',
    );

    return className;
  }

  /// Serializes a track's keyframes to a `@keyframes` body. Endpoints are
  /// padded with copies of the nearest keyframe so the resting value holds
  /// outside the keyframed span, matching Figma's hold semantics. A
  /// keyframe's easing shapes the segment to the next keyframe and is
  /// emitted only when it differs from the block default (the rule's timing
  /// function covers the rest). The last keyframe has no following segment,
  /// so its easing is never emitted.
  String _keyframesBody(
    String track,
    List<Object?> keyframes,
    Object defaultEasing,
  ) {
    final list = <({double at, double value, Object? easing})>[];

    for (final entry in keyframes) {
      final keyframe = entry as Map<String, Object?>;

      list.add((
        at: (keyframe['at'] as num).toDouble(),
        value: (keyframe['value'] as num).toDouble(),
        easing: keyframe['easing'],
      ));
    }

    if (list.first.at > 0) {
      list.insert(0, (at: 0, value: list.first.value, easing: null));
    }

    final last = list.last;

    if (last.at < 100) {
      list.add((at: 100, value: last.value, easing: null));
    }

    final defaultCss = _easingCss(defaultEasing);
    final body = StringBuffer();

    for (var i = 0; i < list.length; i++) {
      final keyframe = list[i];
      final easing = keyframe.easing;
      final easingCss = easing != null && i < list.length - 1
          ? _easingCss(easing)
          : defaultCss;
      final timing = easingCss != defaultCss
          ? ';animation-timing-function:$easingCss'
          : '';

      body.write(
        '${formatNumber(keyframe.at)}%'
        '{${_trackDeclaration(track, keyframe.value)}$timing}',
      );
    }

    return body.toString();
  }

  /// Returns the CSS declaration animating one track at one keyframe value.
  String _trackDeclaration(String track, double value) {
    final v = formatNumber(value);

    switch (track) {
      case 'translateX':
        return 'transform:translateX(${v}px)';
      case 'translateY':
        return 'transform:translateY(${v}px)';
      case 'rotate':
        return 'transform:rotate(${v}deg)';
      case 'scaleX':
        return 'transform:scaleX($v)';
      case 'scaleY':
        return 'transform:scaleY($v)';
      default:
        // `opacity` — the only remaining schema-valid track name.
        return 'opacity:$v';
    }
  }

  /// Serializes an easing to its CSS form. `hold` renders as `step-end`.
  String _easingCss(Object easing) {
    if (easing is String) {
      return _easingKeywordCss[easing] ?? 'linear';
    }

    final bezier = easing as Map<String, Object?>;

    return 'cubic-bezier(${formatNumber((bezier['x1'] as num).toDouble())}, '
        '${formatNumber((bezier['y1'] as num).toDouble())}, '
        '${formatNumber((bezier['x2'] as num).toDouble())}, '
        '${formatNumber((bezier['y2'] as num).toDouble())})';
  }

  /// Registers the accumulated animation CSS as a single `<style>` entry in
  /// the shared `<defs>` block, wrapped in a reduced-motion media query so
  /// users who prefer reduced motion get the static avatar. A no-op when no
  /// animation CSS was produced.
  void _registerAnimationStyle() {
    if (_keyframesCss.isEmpty) {
      return;
    }

    // An authored def may carry the id `animation-style`, so the CSS takes
    // the next free key rather than replacing that def.
    var key = 'animation-style';

    while (_defs.containsKey(key)) {
      key += '-';
    }

    _defs[key] = '<style>@media (prefers-reduced-motion:no-preference)'
        '{${_keyframesCss.join()}${_animationCss.join()}}</style>';
  }
}

// Shared process-randomness source for _randomizeIds.
final math.Random _random = math.Random();

final RegExp _idDeclaration = RegExp(r'\bid="([^"]+)"');

// The JS reference's regex-escape set: [.*+?^${}()|[\]\\].
final RegExp _regExpSpecials = RegExp(r'[.*+?^${}()|[\]\\]');
