/// Walks a style's element tree and turns it into the final SVG markup.
library;

import 'dart:math' as math;

import 'prng/fnv1a.dart';
import 'resolver.dart';
import 'style.dart';
import 'style/canvas.dart';
import 'style/component.dart';
import 'style/element.dart';
import 'utils/initials.dart';
import 'utils/license.dart';
import 'utils/number.dart';
import 'utils/xml.dart';

/// Walks a style's element tree and turns it into the final SVG markup.
///
/// The renderer is single-use: it accumulates `<defs>` entries and per-render
/// caches across method calls, so a fresh instance is required per avatar. A
/// circular color reference encountered during resolution surfaces as a
/// `CircularColorReferenceError` thrown from [render].
class Renderer {
  final Style _style;
  final Resolver _resolver;

  // Insertion-ordered like the JS Map: updating an existing key keeps its
  // original position — Dart's default map does both natively (Go wrote an
  // orderedDefs helper, Rust uses IndexMap).
  final Map<String, String> _defs = {};
  String? _cachedSeedHash;
  String? _cachedInitials;

  Renderer(Style style, Resolver resolver)
      : _style = style,
        _resolver = resolver;

  /// Builds the complete SVG document for the avatar.
  String render() {
    final canvas = _style.canvas;
    final background = _renderBackground(canvas);
    var body = _renderElements(canvas.elements);

    // Order matters: scale and flip around center, then rotate, translate,
    // and finally clip with border radius (outermost wrapper).
    body = _applyScale(body, canvas);
    body = _applyFlip(body, canvas);
    body = _applyRotate(body, canvas);
    body = _applyTranslate(body, canvas);
    body = _applyBorderRadius('$background$body', canvas);

    final metadata = licenseXml(_style.meta);
    final defs = _defs.isNotEmpty ? '<defs>${_defs.values.join()}</defs>' : '';

    // Resolve size before title and the root attributes so the resolver memo
    // records the keys in the same order as the JS/PHP/Python ports — the
    // JSON envelope emits the resolved options in first-recorded order.
    final size = _resolver.size();

    final title = _resolver.title();
    final escapedTitle = title != null ? escapeXml(title) : null;

    final attrs = <String>[
      'xmlns="http://www.w3.org/2000/svg"',
      'viewBox="0 0 ${formatNumber(canvas.width)} ${formatNumber(canvas.height)}"',
    ];

    final rootAttributes = _renderAttributes(_style.attributes());

    if (rootAttributes.isNotEmpty) {
      // _renderAttributes returns a leading space; the root attributes sit
      // between the fixed entries, so strip it here like the JS trimStart().
      attrs.add(rootAttributes.trimLeft());
    }

    if (escapedTitle != null) {
      attrs.add('role="img"');
      attrs.add('aria-label="$escapedTitle"');
    } else {
      attrs.add('aria-hidden="true"');
    }

    if (size != null) {
      final sizeValue = formatNumber(size);

      attrs.add('width="$sizeValue"');
      attrs.add('height="$sizeValue"');
    }

    final titleElement =
        escapedTitle != null ? '<title>$escapedTitle</title>' : '';

    var svg = '<svg ${attrs.join(' ')}>'
        '<!-- Generated by DiceBear (https://dicebear.com) -->'
        '$metadata$defs$titleElement$body</svg>';

    if (_resolver.idRandomization()) {
      svg = _randomizeIds(svg);
    }

    return svg;
  }

  /// Wraps [body] in a flip transform when `flip` is set to anything other
  /// than `'none'`.
  String _applyFlip(String body, Canvas canvas) {
    final flip = _resolver.flip();

    if (flip == 'none') {
      return body;
    }

    final w = formatNumber(canvas.width);
    final h = formatNumber(canvas.height);
    final String transform;

    switch (flip) {
      case 'horizontal':
        transform = 'translate($w, 0) scale(-1, 1)';
      case 'vertical':
        transform = 'translate(0, $h) scale(1, -1)';
      case 'both':
        transform = 'translate($w, $h) scale(-1, -1)';
      default:
        return body;
    }

    return '<g transform="$transform">$body</g>';
  }

  /// Wraps [body] in a uniform scale transform around the canvas center when
  /// the option differs from `1`.
  String _applyScale(String body, Canvas canvas) {
    final scale = _resolver.scale();

    if (scale == 1) {
      return body;
    }

    final cx = canvas.width / 2;
    final cy = canvas.height / 2;

    return '<g transform="translate(${formatNumber(cx)}, ${formatNumber(cy)}) '
        'scale(${formatNumber(scale)}) '
        'translate(${formatNumber(-cx)}, ${formatNumber(-cy)})">$body</g>';
  }

  /// Clips [body] to the canvas rectangle (rounded when `borderRadius` is
  /// non-zero) and registers the corresponding `clipPath` in `<defs>`. The
  /// clip is always applied so transformed content cannot bleed past the
  /// canvas bounds, regardless of the consumer's `overflow` setting.
  String _applyBorderRadius(String body, Canvas canvas) {
    final radius = _resolver.borderRadius();
    final id = 'clip-${_hashSeed()}';

    final rx = formatNumber(radius / 100 * canvas.width);
    final ry = formatNumber(radius / 100 * canvas.height);

    _defs[id] = '<clipPath id="$id">'
        '<rect width="${formatNumber(canvas.width)}" '
        'height="${formatNumber(canvas.height)}" rx="$rx" ry="$ry"/>'
        '</clipPath>';

    return '<g clip-path="url(#$id)">$body</g>';
  }

  /// Wraps [body] in a rotation around the canvas center when `rotate` is
  /// non-zero.
  String _applyRotate(String body, Canvas canvas) {
    final rotate = _resolver.rotate();

    if (rotate == 0) {
      return body;
    }

    final cx = canvas.width / 2;
    final cy = canvas.height / 2;

    return '<g transform="rotate(${formatNumber(rotate)}, '
        '${formatNumber(cx)}, ${formatNumber(cy)})">$body</g>';
  }

  /// Wraps [body] in a translate transform when either `translateX` or
  /// `translateY` is non-zero. Offsets are interpreted as percentages of the
  /// canvas dimensions.
  String _applyTranslate(String body, Canvas canvas) {
    final tx = _resolver.translateX();
    final ty = _resolver.translateY();

    if (tx == 0 && ty == 0) {
      return body;
    }

    final x = formatNumber(tx / 100 * canvas.width);
    final y = formatNumber(ty / 100 * canvas.height);

    return '<g transform="translate($x, $y)">$body</g>';
  }

  /// Returns a `<rect>` filling the canvas with the resolved background
  /// color, or an empty string when no background colors are configured.
  /// This is the first resolver call of the render, so
  /// `backgroundColorFill` and `backgroundColor` open the snapshot.
  String _renderBackground(Canvas canvas) {
    final colors = _resolver.color('background');

    if (colors.isEmpty) {
      return '';
    }

    return '<rect width="${formatNumber(canvas.width)}" '
        'height="${formatNumber(canvas.height)}" '
        'fill="${escapeXml(_resolveColorReference('background'))}"/>';
  }

  /// Suffixes every `id` declaration and reference with a random hex string
  /// so that multiple instances of the same avatar do not collide in a shared
  /// document. Process randomness ([math.Random], the JS `Math.random()`) is
  /// intentional — a PRNG-derived suffix would produce the same ID for the
  /// same seed.
  String _randomizeIds(String svg) {
    // floor(random * 0xffffff) yields 0..0xfffffe (exclusive upper bound),
    // matching the JS reference rather than a masked 0..0xffffff.
    final suffix = (_random.nextDouble() * 0xffffff)
        .floor()
        .toRadixString(16)
        .padLeft(6, '0');

    // A Dart Set keeps insertion order, like the JS Set the reference fills.
    final ids = <String>{
      for (final match in _idDeclaration.allMatches(svg)) match[1]!,
    };

    if (ids.isEmpty) {
      return svg;
    }

    final escaped = [
      for (final id in ids)
        id.replaceAllMapped(_regExpSpecials, (m) => '\\${m[0]}'),
    ];
    final pattern =
        RegExp('(id="|url\\(#|href="#)(${escaped.join('|')})("|\\))');

    return svg.replaceAllMapped(
      pattern,
      (m) => '${m[1]}${m[2]}-$suffix${m[3]}',
    );
  }

  /// Renders a list of elements and concatenates their markup.
  String _renderElements(List<ElementNode> elements) =>
      [for (final element in elements) _renderElement(element)].join();

  /// Dispatches a single element to the renderer for its type.
  String _renderElement(ElementNode element) {
    switch (element.type) {
      case 'element':
        return _renderSvgElement(element);
      case 'text':
        return _renderTextElement(element);
      case 'component':
        return _renderComponentElement(element);
      default:
        return '';
    }
  }

  /// Renders an SVG element. The special `defs` name diverts children into
  /// the shared `<defs>` block.
  ///
  /// Element names and attribute names are not escaped here — they are
  /// validated against a strict allowlist schema (no `<script>`, no event
  /// handlers). Values are escaped via [escapeXml].
  String _renderSvgElement(ElementNode element) {
    final name = element.name;

    if (name == null || name.isEmpty) {
      return '';
    }

    if (name == 'defs') {
      for (final child in element.children) {
        final rendered = _renderElement(child);

        if (rendered.isNotEmpty) {
          // The def key is the child's literal `id` attribute (not a
          // color/variable reference object), else a positional `_N` key
          // evaluated at insertion time.
          final id = child.attributes?['id'];
          final key = id is String ? id : '_${_defs.length}';

          _defs[key] = rendered;
        }
      }

      return '';
    }

    final attrs = _renderAttributes(element.attributes);
    final children = _renderElements(element.children);

    if (children.isEmpty) {
      return '<$name$attrs/>';
    }

    return '<$name$attrs>$children</$name>';
  }

  /// Renders a text element by escaping its resolved value.
  String _renderTextElement(ElementNode element) {
    final value = element.value;

    return value != null ? escapeXml(_resolveValue(value)) : '';
  }

  /// Resolves a component reference to a chosen variant and emits a `<use>`
  /// pointing at a `<defs>` entry that holds the variant body. Aliases of the
  /// same source component sharing a variant — and identical components
  /// referenced more than once — therefore produce a single `<defs>` entry
  /// referenced by every `<use>`, never duplicated SVG markup.
  ///
  /// Any `attributes` on the component reference are written to the emitted
  /// `<use>` tag. A user-supplied `transform` is prepended to the
  /// per-component transforms so it acts as the outer (placement) transform,
  /// with the style's translate/rotate/scale applied inside it.
  String _renderComponentElement(ElementNode element) {
    final componentName = element.name;

    if (componentName == null) {
      return '';
    }

    final variantName = _resolver.variant(componentName);

    if (variantName == null || variantName.isEmpty) {
      return '';
    }

    final component = _style.components[componentName];

    if (component == null) {
      return '';
    }

    final variant = component.variants()[variantName];

    if (variant == null) {
      return '';
    }

    // The def ID uses the source name, so aliases sharing a variant produce
    // one <g> def and several <use> references.
    final id = '${component.sourceName}-$variantName-${_hashSeed()}';

    if (!_defs.containsKey(id)) {
      final body = _renderElements(variant.elements());

      _defs[id] = '<g id="$id">$body</g>';
    }

    final transforms = _buildTransforms(component);
    final userAttributes = element.attributes;
    Map<String, Object?>? mergedAttributes = userAttributes;

    if (transforms.isNotEmpty) {
      final userTransform = userAttributes?['transform'];
      final allParts = userTransform is String && userTransform.isNotEmpty
          ? [userTransform, ...transforms]
          : transforms;

      // Assigning to an existing `transform` key keeps its position in the
      // attribute order; a new key is appended — the JS object spread
      // semantics (Dart maps behave the same way).
      mergedAttributes = {...?userAttributes};
      mergedAttributes['transform'] = allParts.join(' ');
    }

    final attrs = _renderAttributes(mergedAttributes);

    return '<use$attrs href="#$id"/>';
  }

  /// Returns the per-component SVG `transform` fragments derived from the
  /// component's translate, rotate, and scale options. Translate values are
  /// percentages of the component canvas dimensions, matching the semantics
  /// of the user-facing `translateX` / `translateY` options.
  ///
  /// The fragments are ordered so that, when joined into a single `transform`
  /// attribute, the scale is the rightmost (innermost) transform — applied
  /// first to a point, followed by rotate, then translate.
  List<String> _buildTransforms(Component component) {
    final transform = _resolver.componentTransform(component.name);
    final rotate = transform.rotate;
    final translateX = transform.translateX;
    final translateY = transform.translateY;
    final scale = transform.scale;

    if (translateX == 0 && translateY == 0 && rotate == 0 && scale == 1) {
      return const [];
    }

    final transforms = <String>[];
    final cx = component.width / 2;
    final cy = component.height / 2;
    final cxValue = formatNumber(cx);
    final cyValue = formatNumber(cy);

    if (translateX != 0 || translateY != 0) {
      final x = formatNumber(translateX / 100 * component.width);
      final y = formatNumber(translateY / 100 * component.height);

      transforms.add('translate($x, $y)');
    }

    if (rotate != 0) {
      transforms.add('rotate(${formatNumber(rotate)}, $cxValue, $cyValue)');
    }

    if (scale != 1) {
      transforms.add('translate($cxValue, $cyValue) '
          'scale(${formatNumber(scale)}) '
          'translate(${formatNumber(-cx)}, ${formatNumber(-cy)})');
    }

    return transforms;
  }

  /// Serializes an attribute map to a leading space-prefixed string suitable
  /// for inlining into a tag. Returns an empty string when there are no
  /// attributes to render. Entries render in map insertion order — SVG
  /// attribute order is load-bearing for byte parity.
  String _renderAttributes(Map<String, Object?>? attributes) {
    if (attributes == null) {
      return '';
    }

    final parts = <String>[];

    for (final entry in attributes.entries) {
      final value = entry.value;

      if (value == null) {
        continue;
      }

      parts.add('${entry.key}="${escapeXml(_resolveAttributeValue(value))}"');
    }

    if (parts.isEmpty) {
      return '';
    }

    return ' ${parts.join(' ')}';
  }

  /// Resolves a single attribute value: literal strings pass through, color
  /// and variable references are dereferenced through the option resolver.
  String _resolveAttributeValue(Object value) {
    if (value is String) {
      return value;
    }

    final reference = value as Map<String, Object?>;
    final name = reference['name'] as String;

    if (reference['type'] == 'color') {
      return _resolveColorReference(name);
    }

    return _resolveVariable(name);
  }

  /// Resolves a named color into either a hex string (solid fill / single
  /// color) or a `url(#…)` gradient reference, registering the gradient in
  /// `<defs>` as a side effect.
  String _resolveColorReference(String name) {
    final colors = _resolver.color(name);
    final fill = _resolver.colorFill(name);

    if (fill == 'solid' || colors.length <= 1) {
      return colors.isNotEmpty ? colors[0] : 'none';
    }

    return _buildGradientDef(name, colors, fill);
  }

  /// Builds the `<linearGradient>` or `<radialGradient>` for the given color
  /// definition, registers it in `<defs>`, and returns its `url(#…)`
  /// reference. This is the only caller of `colorAngle`, so the angle is
  /// drawn — and recorded in the snapshot — only when a gradient is built.
  String _buildGradientDef(String name, List<String> colors, String fill) {
    final rotation = _resolver.colorAngle(name);
    final id = '$name-color-${_hashSeed()}';
    final tag = fill == 'linear' ? 'linearGradient' : 'radialGradient';
    final rotateAttr = rotation != 0
        ? ' gradientTransform="rotate(${formatNumber(rotation)}, 0.5, 0.5)"'
        : '';
    final stops = StringBuffer();

    for (var i = 0; i < colors.length; i++) {
      final offset = formatNumber(i / (colors.length - 1) * 100);

      stops.write(
        '<stop offset="$offset%" stop-color="${escapeXml(colors[i])}"/>',
      );
    }

    _defs[id] = '<$tag id="$id"$rotateAttr>$stops</$tag>';

    return 'url(#$id)';
  }

  /// Resolves an element value to its final string form. Literal strings pass
  /// through; variable references are dereferenced.
  String _resolveValue(Object value) {
    if (value is String) {
      return value;
    }

    final reference = value as Map<String, Object?>;

    if (reference['type'] == 'variable') {
      return _resolveVariable(reference['name'] as String);
    }

    return '';
  }

  /// Resolves a built-in variable reference to its current value.
  String _resolveVariable(String name) {
    switch (name) {
      case 'initial':
        // charAt(0) would return a lone surrogate (ill-formed XML) for
        // supplementary-plane initials; take the full first code point
        // instead, like the JS/PHP/Python/Rust/Go ports.
        final initials = _initials();

        return initials.isEmpty
            ? ''
            : String.fromCharCode(initials.runes.first);
      case 'initials':
        return _initials();
      case 'fontWeight':
        return formatNumber(_resolver.fontWeight());
      case 'fontFamily':
        return _resolver.fontFamily();
      default:
        return '';
    }
  }

  /// Returns the seed-derived initials, cached after the first call.
  String _initials() => _cachedInitials ??= initialsFromSeed(_resolver.seed());

  /// Returns the FNV-1a hex hash of the style source name and seed, cached
  /// after the first call. The value is used to derive stable but unique IDs
  /// for `<defs>` entries; the source name keeps same-seed avatars of
  /// different styles from colliding when inlined on one page.
  String _hashSeed() => _cachedSeedHash ??=
      fnv1aHex('${_style.meta.source().name() ?? ''}:${_resolver.seed()}');
}

// Shared process-randomness source for _randomizeIds.
final math.Random _random = math.Random();

final RegExp _idDeclaration = RegExp(r'\bid="([^"]+)"');

// The JS reference's regex-escape set: [.*+?^${}()|[\]\\].
final RegExp _regExpSpecials = RegExp(r'[.*+?^${}()|[\]\\]');
