export { hair } from './hair.js';
export { face } from './face.js';
export { mouth } from './mouth.js';
export { ear } from './ear.js';
export { eyes } from './eyes.js';
export { cheek } from './cheek.js';
export { nose } from './nose.js';
export { sideburn } from './sideburn.js';
export { frontHair } from './frontHair.js';
