import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  title: 'Options',
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    backgroundColor: {
      title: 'Background Color',
      type: 'array',
      uniqueItems: true,
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'amber',
        'blue',
        'blueGrey',
        'brown',
        'cyan',
        'deepOrange',
        'deepPurple',
        'green',
        'grey',
        'indigo',
        'lightBlue',
        'lightGreen',
        'lime',
        'orange',
        'pink',
        'purple',
        'red',
        'teal',
        'yellow',
      ],
      examples: [
        ['amber'],
        ['blue'],
        ['blueGrey'],
        ['brown'],
        ['cyan'],
        ['deepOrange'],
        ['deepPurple'],
        ['green'],
        ['grey'],
        ['indigo'],
        ['lightBlue'],
        ['lightGreen'],
        ['lime'],
        ['orange'],
        ['pink'],
        ['purple'],
        ['red'],
        ['teal'],
        ['yellow'],
      ],
    },
    fontSize: {
      title: 'Font Size',
      type: 'integer',
      minimum: 1,
      maximum: 100,
      default: 50,
    },
    chars: {
      title: 'Chars',
      type: 'number',
      minimum: 0,
      maximum: 2,
      default: 2,
    },
    bold: {
      title: 'Bold',
      type: 'boolean',
    },
  },
  additionalProperties: false,
};
