import type { StyleSchema } from '@dicebear/core';

export const schema: StyleSchema = {
  title: 'Options',
  $schema: 'http://json-schema.org/draft-07/schema#',
  properties: {
    base: {
      type: 'array',
      items: { type: 'string', enum: ['default'] },
      default: ['default'],
      examples: [['default']],
    },
    earrings: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant06',
          'variant01',
          'variant02',
          'variant03',
          'variant04',
          'variant05',
        ],
      },
      default: [
        'variant06',
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
      ],
      examples: [
        ['variant06'],
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
      ],
    },
    earringsColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'silver',
        'gold',
        'bronze',
        'black',
        'white',
        'red',
        'green',
        'blue',
      ],
      examples: [
        ['silver'],
        ['gold'],
        ['bronze'],
        ['black'],
        ['white'],
        ['red'],
        ['green'],
        ['blue'],
      ],
    },
    earringsProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    eyebrows: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
        ],
      },
      default: [
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
      ],
      examples: [
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
      ],
    },
    eyes: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant26'],
        ['variant25'],
        ['variant24'],
        ['variant23'],
        ['variant22'],
        ['variant21'],
        ['variant20'],
        ['variant19'],
        ['variant18'],
        ['variant17'],
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    features: {
      type: 'array',
      items: { type: 'string', enum: ['blush', 'birthmark', 'freckles'] },
      default: ['blush', 'birthmark', 'freckles'],
      examples: [['blush'], ['birthmark'], ['freckles']],
    },
    featuresProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 5,
    },
    glasses: {
      type: 'array',
      items: {
        type: 'string',
        enum: ['variant01', 'variant02', 'variant03', 'variant04', 'variant05'],
      },
      default: [
        'variant01',
        'variant02',
        'variant03',
        'variant04',
        'variant05',
      ],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
      ],
    },
    glassesProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 10,
    },
    hair: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'short16',
          'short15',
          'short14',
          'short13',
          'short12',
          'short11',
          'short10',
          'short09',
          'short08',
          'short07',
          'short06',
          'short05',
          'short04',
          'short03',
          'long20',
          'short02',
          'short01',
          'long19',
          'long18',
          'long17',
          'long16',
          'long15',
          'long14',
          'long13',
          'long12',
          'long11',
          'long10',
          'long09',
          'long08',
          'long07',
          'long06',
          'long05',
          'long04',
          'long03',
          'long02',
          'long01',
          'short19',
          'long26',
          'long25',
          'short18',
          'long24',
          'long23',
          'long22',
          'short17',
          'long21',
        ],
      },
      default: [
        'short16',
        'short15',
        'short14',
        'short13',
        'short12',
        'short11',
        'short10',
        'short09',
        'short08',
        'short07',
        'short06',
        'short05',
        'short04',
        'short03',
        'long20',
        'short02',
        'short01',
        'long19',
        'long18',
        'long17',
        'long16',
        'long15',
        'long14',
        'long13',
        'long12',
        'long11',
        'long10',
        'long09',
        'long08',
        'long07',
        'long06',
        'long05',
        'long04',
        'long03',
        'long02',
        'long01',
        'short19',
        'long26',
        'long25',
        'short18',
        'long24',
        'long23',
        'long22',
        'short17',
        'long21',
      ],
      examples: [
        ['short16'],
        ['short15'],
        ['short14'],
        ['short13'],
        ['short12'],
        ['short11'],
        ['short10'],
        ['short09'],
        ['short08'],
        ['short07'],
        ['short06'],
        ['short05'],
        ['short04'],
        ['short03'],
        ['long20'],
        ['short02'],
        ['short01'],
        ['long19'],
        ['long18'],
        ['long17'],
        ['long16'],
        ['long15'],
        ['long14'],
        ['long13'],
        ['long12'],
        ['long11'],
        ['long10'],
        ['long09'],
        ['long08'],
        ['long07'],
        ['long06'],
        ['long05'],
        ['long04'],
        ['long03'],
        ['long02'],
        ['long01'],
        ['short19'],
        ['long26'],
        ['long25'],
        ['short18'],
        ['long24'],
        ['long23'],
        ['long22'],
        ['short17'],
        ['long21'],
      ],
    },
    hairColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: [
        'red01',
        'red02',
        'red03',
        'blonde01',
        'blonde02',
        'blonde03',
        'brown01',
        'brown02',
        'black',
        'gray',
        'green',
        'blue',
        'pink',
        'purple',
      ],
      examples: [
        ['red01'],
        ['red02'],
        ['red03'],
        ['blonde01'],
        ['blonde02'],
        ['blonde03'],
        ['brown01'],
        ['brown02'],
        ['black'],
        ['gray'],
        ['green'],
        ['blue'],
        ['pink'],
        ['purple'],
      ],
    },
    hairProbability: {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      default: 100,
    },
    mouth: {
      type: 'array',
      items: {
        type: 'string',
        enum: [
          'variant30',
          'variant29',
          'variant28',
          'variant27',
          'variant26',
          'variant25',
          'variant24',
          'variant23',
          'variant22',
          'variant21',
          'variant20',
          'variant19',
          'variant18',
          'variant17',
          'variant16',
          'variant15',
          'variant14',
          'variant13',
          'variant12',
          'variant11',
          'variant10',
          'variant09',
          'variant08',
          'variant07',
          'variant06',
          'variant05',
          'variant04',
          'variant03',
          'variant02',
          'variant01',
        ],
      },
      default: [
        'variant30',
        'variant29',
        'variant28',
        'variant27',
        'variant26',
        'variant25',
        'variant24',
        'variant23',
        'variant22',
        'variant21',
        'variant20',
        'variant19',
        'variant18',
        'variant17',
        'variant16',
        'variant15',
        'variant14',
        'variant13',
        'variant12',
        'variant11',
        'variant10',
        'variant09',
        'variant08',
        'variant07',
        'variant06',
        'variant05',
        'variant04',
        'variant03',
        'variant02',
        'variant01',
      ],
      examples: [
        ['variant30'],
        ['variant29'],
        ['variant28'],
        ['variant27'],
        ['variant26'],
        ['variant25'],
        ['variant24'],
        ['variant23'],
        ['variant22'],
        ['variant21'],
        ['variant20'],
        ['variant19'],
        ['variant18'],
        ['variant17'],
        ['variant16'],
        ['variant15'],
        ['variant14'],
        ['variant13'],
        ['variant12'],
        ['variant11'],
        ['variant10'],
        ['variant09'],
        ['variant08'],
        ['variant07'],
        ['variant06'],
        ['variant05'],
        ['variant04'],
        ['variant03'],
        ['variant02'],
        ['variant01'],
      ],
    },
    skinColor: {
      type: 'array',
      items: {
        type: 'string',
        pattern:
          '^([0-9a-zA-Z]+|#[a-fA-F0-9]{3}|#[a-fA-F0-9]{4}|#[a-fA-F0-9]{6}|#[a-fA-F0-9]{8})$',
      },
      default: ['variant02', 'variant03', 'variant04', 'variant05'],
      examples: [
        ['variant01'],
        ['variant02'],
        ['variant03'],
        ['variant04'],
        ['variant05'],
      ],
    },
  },
  additionalProperties: false,
};
