name: Test

on:
  push:
    branches:
      - '*.x'
  pull_request:
    branches:
      - '*.x'
  workflow_call: {}

jobs:
  test-js:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24, 25]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npx turbo run build --filter='!@dicebear/docs' --filter='!@dicebear/editor'
      - run: npx turbo run test

  test-php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4', '8.5']

    steps:
      - uses: actions/checkout@v5
      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring
      - name: Install dependencies
        working-directory: src/php/core
        run: composer install --no-interaction --prefer-dist
      - name: Run PHPStan
        working-directory: src/php/core
        run: vendor/bin/phpstan analyse --no-progress
      - name: Run tests
        working-directory: src/php/core
        run: vendor/bin/phpunit

  test-python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@v5
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: src/python/core
        run: pip install -e ".[dev]"
      - name: Run Ruff
        working-directory: src/python/core
        run: |
          ruff check .
          ruff format --check .
      - name: Run mypy
        working-directory: src/python/core
        run: mypy src
      - name: Run tests
        working-directory: src/python/core
        run: pytest
