/// Shared plumbing for the style and options validators: schema compilation
/// and the mapping from `json_schema` failures to [ValidationErrorDetail].
///
/// The JS port has no counterpart for this file — its validators are
/// standalone code generated by Ajv at build time. Here the two validators
/// compile their schema at runtime instead and share this helper.
library;

import 'package:json_schema/json_schema.dart' as json_schema;

import '../error/validation_error.dart';

/// The schemas are registered under their published CDN URIs, mirroring the
/// Go port: a relative or filesystem-derived base URI would leak the
/// consumer's environment into validation error output. Keep the version in
/// sync with the `dicebear_schema` dependency in `pubspec.yaml`.
const String schemaBaseUrl =
    'https://cdn.hopjs.net/npm/@dicebear/schema@2.0.1/dist/';

/// Compiles a draft-07 schema from its raw JSON [raw], registered under
/// [schemaBaseUrl] + [name].
json_schema.JsonSchema compileSchema(String name, String raw) {
  // The embedded schemas only use internal `#/definitions/...` references, so
  // the synchronous, fetch-free `create` is sufficient.
  return json_schema.JsonSchema.create(
    raw,
    schemaVersion: json_schema.SchemaVersion.draft7,
    fetchedFromUri: Uri.parse('$schemaBaseUrl$name'),
  );
}

/// Validates [data] against [schema] and maps every failure to a
/// [ValidationErrorDetail]. An empty result means the data is valid.
///
/// Unlike Ajv (which stops at the first violation), every failure is
/// reported; only accept/reject decisions are parity-pinned, the detail
/// list and message text are not.
List<ValidationErrorDetail> collectErrors(
  json_schema.JsonSchema schema,
  Object? data,
) {
  // JSON cannot represent non-finite numbers, and the Ajv-compiled
  // validators of the JS reference reject them wherever a number is allowed
  // (`type: "number"` compiles to `typeof data == "number" && isFinite(data)`).
  // `package:json_schema` only checks `is num`, and its minimum/maximum
  // comparisons are always false for NaN — without this walk, Dart would be
  // the only port to accept NaN/Infinity (Go validates marshalled JSON bytes
  // and Rust's JSON numbers cannot hold them) and would render broken SVG
  // like `viewBox="0 0 NaN 100"`.
  final nonFinite = <ValidationErrorDetail>[];
  _collectNonFinite(data, '', nonFinite);

  if (nonFinite.isNotEmpty) {
    return nonFinite;
  }

  final results = schema.validate(data);

  return [
    for (final error in results.errors)
      ValidationErrorDetail(
        instancePath: error.instancePath,
        message: error.message,
      ),
  ];
}

void _collectNonFinite(
  Object? node,
  String path,
  List<ValidationErrorDetail> out,
) {
  if (node is double && !node.isFinite) {
    out.add(
      ValidationErrorDetail(
        instancePath: path,
        message: 'must be a finite number',
      ),
    );
  } else if (node is List) {
    for (var i = 0; i < node.length; i++) {
      _collectNonFinite(node[i], '$path/$i', out);
    }
  } else if (node is Map) {
    for (final entry in node.entries) {
      _collectNonFinite(
          entry.value, '$path/${_pointerSegment(entry.key)}', out);
    }
  }
}

/// Escapes a JSON pointer segment per RFC 6901 (`~` → `~0`, `/` → `~1`).
String _pointerSegment(Object? key) {
  return key.toString().replaceAll('~', '~0').replaceAll('/', '~1');
}
